### ISSUE TITLE
FALCON-integrate crashing 

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#135]
Hi, Chris/Jason,

I'm sure this is a problem with my environment, but maybe you can point me to where to look.

These steps work fine:
```sh
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout 0.3.0
make init
make virtualenv
make check
```
make check says:
```
> make check
. /net/gs/vol1/home/dgordon/falcon150710/FALCON-integrate/fc_env/bin/activate; which python
/net/gs/vol1/home/dgordon/falcon150710/FALCON-integrate/fc_env/bin/python
```
Looks good, no?

The problem occurs with:

    make -j install

The gcc compiles occur without error but then python crashes (repeatedly) with:
```
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    install_requires=install_requires
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
make[1]: *** [build-FALCON] Error 1
make[1]: *** Waiting for unfinished jobs....
```
Which version of python is required?  (I've been using python 2.7.3)  Any other things to check?

Thanks!
David

**Comment by dgordon562** [comment]
another clue:

It is crashing in ~/falcon150710/FALCON-integrate/pypeFLOW:

> python setup.py build
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    'rdfextras >= 0.1'
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
(fc_env){dgordon}e186:~/falcon150710/FALCON-integrate/pypeFLOW

**Comment by dgordon562** [comment]
Another clue:

It is also crashing in:

. /net/gs/vol1/home/dgordon/falcon150710/FALCON-integrate/fc_env/bin/activate
cd /net/gs/vol1/home/dgordon/falcon150710/FALCON-integrate/FALCON; python setup.py build
python setup.py build

However, if, after the "activate" command, I:

module load anaconda
then it works!

However, if I load anaconda first and then activate the virtual environment, it crashes.

This means that I can't load anaconda before  "make -j install" because the "activate" will come later.

So the virtual environment is not loading something that setup.py needs and that anaconda loads.

Your thoughts?

**Comment by pb-cdunn** [comment]
Exactly. python **virtualenv** is an oddball. We let it own everything by installing executables into its own `bin`. But as you said, `module load` works *after* the virtualenv is activated.

I recommend setting up your environment in your shell, including `activate` followed by `module load`. Then, you can run

    make -C FALCON-make install

**FALCON-integrate** is only the integration package, and it must be understood that integration will be slightly different for varioius environments. You can ignore the `makefile` there, or (what I would do, if possible) you can *branch* **FALCON-integrate** and change the `makefile`. The `%` simply delegates any unknown rule to **FALCON-make/makefile**. You change that to use `module load`, remove it, or whatever you want.

**Comment by dgordon562** [comment]
Thanks, Chris!  I think I succeeded.

I will mention that, after all of the customization of FALCON-integrate I did, I think the old way (without FALCON-integrate) took me less time.
