### ISSUE TITLE
File out.00001.fasta, Line 1: Pacbio header line format error

### ISSUE THREAD

**Issue by cariaso** [PacificBiosciences/FALCON#145]
it has finished preparing the 0-rawreads/preads now should be starting on 1-preads_ovl
when sge tries to run
prepare_pdb.sh

it fails on the step:

fasta2DB -v preads -f/mnt/work/falcon/run2/1-preads_ovl/input_preads.fofn
Adding 'out.00001' ...
File out.00001.fasta, Line 1: Pacbio header line format error

when I run

head /mnt/work/falcon/run2/0-rawreads/preads/out.00001.fasta

I see

>00000000_0
CTCGGGCTGTGCGTGCGTGGCG...(seq looks fine)
>00000001_0
TCCATGAGGCCTGTCACCGACTC...

sge_log/prepare_pdb.sh-build_pdb-build_pdb.o570

ends with

fasta2DB -v preads -f/mnt/work/falcon/run2/1-preads_ovl/input_preads.fofn
+ fasta2DB -v preads -f/mnt/work/falcon/run2/1-preads_ovl/input_preads.fofn
Adding 'out.00001' ...
File out.00001.fasta, Line 1: Pacbio header line format error
touch /mnt/work/falcon/run2/1-preads_ovl/pdb_build_done.exit
+ touch /mnt/work/falcon/run2/1-preads_ovl/pdb_build_done.exit

**Comment by pb-jchin** [comment]
check https://github.com/PacificBiosciences/FALCON/wiki#important-changes 
you need the "--output_dformat"

**Comment by cariaso** [comment]
I can see this is similar to
https://github.com/PacificBiosciences/FALCON/issues/137
but in my case 
1-preads_ovl/input_preads.fofn
exists and seems correct (ie it contains)
/mnt/work/falcon/run2/0-rawreads/preads/out.00001.fasta
/mnt/work/falcon/run2/0-rawreads/preads/out.00002.fasta
...
/mnt/work/falcon/run2/0-rawreads/preads/out.00288.fasta
/mnt/work/falcon/run2/0-rawreads/preads/out.00289.fasta

**Comment by cariaso** [comment]
ok, trying --output_dformat now

**Comment by cariaso** [comment]
still crashing with the end of the log reading

2015-07-24 20:34:51,689 - pypeflow.controller - INFO - Total # of running threads: 2; alive tasks: 1; sleep=1.000000
2015-07-24 20:34:51,689 - pypeflow.controller - INFO - Total # of running threads: 2; alive tasks: 1; sleep=1.000000
2015-07-24 20:34:52,596 - fc_run - INFO - '/mnt/work/falcon/run2/1-preads_ovl/pdb_build_done.exit' generated. job: 'prepare_pdb.sh-build_pdb-build_pdb' exited.
2015-07-24 20:34:52,596 - fc_run - INFO - '/mnt/work/falcon/run2/1-preads_ovl/pdb_build_done.exit' generated. job: 'prepare_pdb.sh-build_pdb-build_pdb' exited.
2015-07-24 20:34:52,597 - fc_run - WARNING - '/mnt/work/falcon/run2/1-preads_ovl/pdb_build_done' is missing. job: 'prepare_pdb.sh-build_pdb-build_pdb' failed!
2015-07-24 20:34:52,597 - fc_run - WARNING - '/mnt/work/falcon/run2/1-preads_ovl/pdb_build_done' is missing. job: 'prepare_pdb.sh-build_pdb-build_pdb' failed!
2015-07-24 20:34:52,690 - pypeflow.controller - INFO - message for task://localhost/build_pdb: 'fail'
2015-07-24 20:34:52,690 - pypeflow.controller - INFO - message for task://localhost/build_pdb: 'fail'
2015-07-24 20:34:52,690 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/build_pdb'...
2015-07-24 20:34:52,690 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/build_pdb'...
2015-07-24 20:34:52,712 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
2015-07-24 20:34:52,712 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
2015-07-24 20:34:52,713 - pypeflow.controller - WARNING - #tasks=1066, #alive=0
2015-07-24 20:34:52,713 - pypeflow.controller - WARNING - #tasks=1066, #alive=0
Traceback (most recent call last):
  File "/mnt/work/falcon/fc_env/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.3.0', 'fc_run.py')
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/mnt/work/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(*sys.argv)
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 869, in main
    main1(*argv)
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 772, in main1
    wf.refreshTargets([pdb_build_done])
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/mnt/work/falcon/fc_env/local/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'

**Comment by pb-jchin** [comment]
you need to remove the 1-pread_ovl directory and re-run it.
