### ISSUE TITLE
fc_run.py stopped

### ISSUE THREAD

**Issue by kendeda** [PacificBiosciences/FALCON#151]
Hi All,

We installed FALCON and ran fc_run.py on SGE, but it stopped in the middle of running.

Error log is shown as below,
````
2015-07-28 09:30:43,957 - pypeflow.controller - INFO - #jobsReadyToBeSubmitted: 0
2015-07-28 09:30:43,957 - pypeflow.controller - INFO - #jobsReadyToBeSubmitted: 0
2015-07-28 09:30:43,957 - pypeflow.controller - INFO - Total # of running threads: 21; alive tasks: 20; sleep=1.000000
2015-07-28 09:30:43,957 - pypeflow.controller - INFO - Total # of running threads: 21; alive tasks: 20; sleep=1.000000
2015-07-28 09:30:44,051 - fc_run - INFO - '/tools/falcon2/test/0-rawreads/preads/c_00020_done.exit' generated. job: 'c_00020.sh-ct_00020-ct_00020' exited.
2015-07-28 09:30:44,051 - fc_run - INFO - '/tools/falcon2/test/0-rawreads/preads/c_00020_done.exit' generated. job: 'c_00020.sh-ct_00020-ct_00020' exited.
2015-07-28 09:30:44,052 - fc_run - WARNING - '/tools/falcon2/test/0-rawreads/preads/c_00020_done' is missing. job: 'c_00020.sh-ct_00020-ct_00020' failed!
2015-07-28 09:30:44,052 - fc_run - WARNING - '/tools/falcon2/test/0-rawreads/preads/c_00020_done' is missing. job: 'c_00020.sh-ct_00020-ct_00020' failed!
2015-07-28 09:30:44,957 - pypeflow.controller - INFO - message for task://localhost/ct_00020: 'fail'
2015-07-28 09:30:44,957 - pypeflow.controller - INFO - message for task://localhost/ct_00020: 'fail'
2015-07-28 09:30:44,958 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/ct_00020'...
2015-07-28 09:30:44,958 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/ct_00020'...
2015-07-28 09:30:44,962 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
2015-07-28 09:30:44,962 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
2015-07-28 09:30:45,863 - pypeflow.controller - WARNING - #tasks=88, #alive=19
2015-07-28 09:30:45,863 - pypeflow.controller - WARNING - #tasks=88, #alive=19
2015-07-28 09:30:47,865 - pypeflow.controller - WARNING - Now, #tasks=88, #alive=19
2015-07-28 09:30:47,865 - pypeflow.controller - WARNING - Now, #tasks=88, #alive=19
2015-07-28 09:30:48,599 - fc_run - WARNING - shutdown_event received (Keyboard Interrupt maybe?), 'rp_00017.sh-m_00017_raw_reads-m_00017_raw_reads' not finished.
2015-07-28 09:30:48,599 - fc_run - WARNING - shutdown_event received (Keyboard Interrupt maybe?), 'rp_00017.sh-m_00017_raw_reads-m_00017_raw_reads' not finished.
~
~
2015-07-28 09:30:54,858 - pypeflow.controller - WARNING - Now, #tasks=88, #alive=0
Traceback (most recent call last):
  File "/tools/falcon2/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.3.0', 'fc_run.py')
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(*sys.argv)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 869, in main
    main1(*argv)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 744, in main1
    wf.refreshTargets(updateFreq = wait_time) # larger number better for more jobs
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/tools/falcon2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'

```

What is the cause? Do you have any idea?

FYI, I show my environment below,
>$ uname -a
>Linux pacbio-rs 2.6.18-308.4.1.el5 #1 SMP Tue Apr 17 17:08:00 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

>$ python --version
>Python 2.7.6

>$ gcc --version
>gcc (GCC) 4.8.3
>Copyright (C) 2013 Free Software Foundation, Inc.
>This is free software; see the source for copying conditions.  There is NO
>warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

fc_run.cfg is shown,
```
[General]
# list of files of the initial subread fasta files
input_fofn = input.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

# Cluster queue setting
sge_option_da = -pe smp 8 -q all.q
sge_option_la = -pe smp 2 -q all.q
sge_option_pda = -pe smp 8 -q all.q
sge_option_pla = -pe smp 2 -q all.q
sge_option_fc = -pe smp 24 -q all.q
sge_option_cns = -pe smp 8 -q all.q

# concurrency settgin
pa_concurrent_jobs = 32
cns_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

# error correction consensus optione
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

# overlap filtering options
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10
```

Thank you.

**Comment by pb-cdunn** [comment]
This will be relatively easy to debug. Just look in the sge logs to learn why `0-rawreads/preads/c_00020.sh` failed. You can also try with `job_type=local` to eliminate SGE as a possible cause, and to capture stderr nearer to .sh files.

Also, we expect everyone to try **FALCON-integrate** at least once before anything else. See `README.md` and `travish.sh` (which is the script that runs in TravisCI). We cannot debug everyone's integration environment.

**Comment by kendeda** [comment]
Thank you for the advice. I'll try to debug it.
