### ISSUE TITLE
Falcon Error!! when try to run example test

### ISSUE THREAD

**Issue by BeeKi20** [PacificBiosciences/FALCON#187]
Dear, pb-cdunn

After I install Falcon version v0.3.0 as follows "The easy way" on this link

https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation-for-v0.3.0

Everything looks fine event if I I run "make test" then I got the complete result in /run/synth0/
So I try to run another example in /run/ folder ,lambda. First, I activate python package by
`. ~/FALCON-integrate/fc_env/bin/activate`  and then go to lambda directory and type
`fc_run.py fc_run.cfg`  and got this error in fc_run.log:

```
2015-09-07 08:52:17,144 - fc_run - WARNING - Contents of '/home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/prepare_pdb.sh.log':
trap 'touch /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/pdb_build_done.exit' EXIT
+ trap 'touch /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/pdb_build_done.exit' EXIT
source /home/beeki/FALCON-integrate/fc_env/bin/activate
+ source /home/beeki/FALCON-integrate/fc_env/bin/activate
# This file must be used with "source bin/activate" *from bash*
# you cannot run it directly

Mon Sep  7 15:52:17 ICT 2015
fasta2DB -v preads -f/home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/input.fofn
+ fasta2DB -v preads -f/home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/input.fofn
fasta2DB: Cannot open /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/data/lambda-creads.fasta for 'r'
touch /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/pdb_build_done.exit
+ touch /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/pdb_build_done.exit

2015-09-07 08:52:17,145 - fc_run - INFO - Cmd 'bash /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/prepare_pdb.sh 1> /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/prepare_pdb.sh.log 2>&1' (job 'prepare_pdb.sh-build_pdb-build_pdb') returned 256.
```
So I go back to the /run/synth0/ and try to run the same way with lambda. Everything works fine. I'm so confuse why??? When I run falcon with another example I always got this error?

Thank you for your response

**Comment by pb-cdunn** [comment]
> Cannot open /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/data/lambda-creads.fasta for 'r'

That file is missing. We do not currently distribute most  test-data. Someday, we might make them available via S3. For now, only the synth0 example is available via dropbox, and it was fetched when you ran `make check`.

If you can find reads elsewhere, the settings for the examples (fc_run.cfg) should work.

**Comment by BeeKi20** [comment]
Thank you for your quick response but when I change path to find reads elsewhere in input.fofn.
I got this error in pypeflow.log

Exception: Cmd 'bash /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/prepare_pdb.sh 1> /home/beeki/FALCON-integrate/FALCON-examples/run/lambda/1-preads_ovl/prepare_pdb.sh.log 2>&1' (job 'prepare_pdb.sh-build_pdb-build_pdb') returned 256.
2015-09-08 02:25:32,206 - pypeflow.controller - INFO - message for task://localhost/build_pdb: 'fail'
2015-09-08 02:25:32,206 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/build_pdb'...
2015-09-08 02:25:32,206 - pypeflow.controller - DEBUG - task status: task:///home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/make_fofn_abs_preads, 'done', used slots: 1
2015-09-08 02:25:32,206 - pypeflow.controller - DEBUG - task status: task:///home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/make_fofn_abs_raw, 'done', used slots: 1
2015-09-08 02:25:32,206 - pypeflow.controller - DEBUG - task status: task://localhost/build_pdb, 'fail', used slots: 1
2015-09-08 02:25:32,206 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Please wait for all threads / processes to terminate !
! Also, maybe use 'ps' or 'qstat' to check all threads,!
! processes and/or jobs are terminated cleanly.        !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2015-09-08 02:25:32,223 - pypeflow.controller - WARNING - #tasks=3, #alive=0
Traceback (most recent call last):
  File "/home/beeki/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.3.0', 'fc_run.py')
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(*sys.argv)
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 869, in main
    main1(*argv)
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.3.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 772, in main1
    wf.refreshTargets([pdb_build_done]) 
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/beeki/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 704, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'

Thank you

**Comment by pb-cdunn** [comment]
The answer is probably in `FALCON-examples/run/lambda/1-preads_ovl/prepare_pdb.sh.log`.

**Comment by pb-cdunn** [comment]
Please re-open if this recurs with more information.

**Comment by yilunhuangyue** [comment]
have you solve the problem? I meet the same problem

**Comment by pb-cdunn** [comment]
`synth0` works? If so, the problem is probably that you are missing the data for `lambda`. You can try running `git-sym update` in the lambda directory of **FALCON-examples**.

**Comment by yilunhuangyue** [comment]
I did't use the example, because my machine is not connected to the internet. I download some pacbio data from https://www.dropbox.com/s/v6wwpn40gedj470 for testing. the fc_run.cfg was copied from the Falcon-example/run/ecoli, and I used job_type = local . The program end with the error:
Traceback (most recent call last):
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_run.py')
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(*sys.argv)
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 566, in main
    main1(*argv)
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 447, in main1
    wf.refreshTargets(updateFreq = wait_time) # larger number better for more jobs, need to call to run jobs here or the # of concurrency is changed
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home02/huangyue/software/falcon/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 706, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'

And 1-preads_ovl、2-asm-falcon was both empty. I am confued now. I don't know where is the problem. could you give me some advices? thanks a lot.

**Comment by pb-cdunn** [comment]
We can't debug your system remotely. Some task is failing. That task needs to be debugged. It should be possible to isolate the problem.
