### ISSUE TITLE
Quiver installed successfully but while running throwing error

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/FALCON#229]
Quiver installed successfully but while running throwing below error
quiver 
Traceback (most recent call last):
File "/usr/local/bin/variantCaller", line 4, in 
import('pkg_resources').run_script('GenomicConsensus==1.1.0', 'variantCaller')
File "build/bdist.linux-x86_64/egg/pkg_resources/init.py", line 735, in run_script

File "build/bdist.linux-x86_64/egg/pkg_resources/init.py", line 1652, in run_script

File "/home/bionivid-server/.local/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/EGG-INFO/scripts/variantCaller", line 3, in 
from GenomicConsensus.main import main
File "/home/bionivid-server/.local/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/main.py", line 42, in 
from pbcore.io import AlignmentSet
File "/usr/local/lib/python2.7/dist-packages/pbcore/io/init.py", line 38, in 
from .align import *
File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/init.py", line 32, in 
from BamIO import *
File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 45, in 
from .PacBioBamIndex import PacBioBamIndex
File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/PacBioBamIndex.py", line 40, in 
from .BamSupport import IncompatibleFile
File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/BamSupport.py", line 58, in 
complementAscii = np.vectorize(ASCII_COMPLEMENT_MAP.get, otypes=[np.int8])
File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1818, in __init
nin, ndefault = _get_nargs(pyfunc)
File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1750, in _get_nargs
"failed to determine the number of arguments for %s" % (obj))
ValueError: failed to determine the number of arguments for

Can anyone please tell me where I am going wrong

**Comment by pb-cdunn** [comment]
Possibly you have an incompatible version of pbcore or numpy.

Please re-file this issue here: https://github.com/PacificBiosciences/GenomicConsensus/issues/new

**Comment by pb-cdunn** [comment]
I see that you already did, 4 days ago: PacificBiosciences/GenomicConsensus#29

Well, you might get a response when they have more time.
