### ISSUE TITLE
kmer_match.count might be zero for some hybrid assembly cases 

### ISSUE THREAD

**Issue by pb-jchin** [PacificBiosciences/FALCON#24]
an issue report by @lexnederbragt in email using `falcon` for hybrid reads 
 
Than I saw something. I ran this command

```
/node/work/lex/falcon/fc_env/bin/fc_run.py fc_run.cfg
```
and save stdin and stdout, and the file contains this:
```
Traceback (most recent call last):
  File "/node/work/lex/falcon/fc_env/bin/fc_graph_to_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.2.1', 'fc_graph_to_contig.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 505, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1245, in run_script
  File "/node/work/lex/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_graph_to_contig.py", line 300, in <module>
    aln_data, x, y = get_aln_data(base_seq, seq)
  File "/node/work/lex/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_graph_to_contig.py", line 68, in get_aln_data
    x,y = zip( * [ (kmer_match.query_pos[i], kmer_match.target_pos[i]) for i in range(kmer_match.count)] )
ValueError: need more than 0 values to unpack
 No target specified, assuming "assembly" as target
```

The root cause is the aligner can't find any k-mer match for the two sequences represent the two branches in a bubble. I have not seen this in non-hybrid case.   There might be something weird of the two sequences to be aligned.

**Comment by lexnederbragt** [comment]
(Not a hybrid assembly, based on corrected reads from PBcR/MHAP)

**Comment by pb-jchin** [comment]
@lexnederbragt, thanks.  Is it possible to get the two sequences that cause trouble?

**Comment by lexnederbragt** [comment]
Sure, but how do I find out which one they are?
