### ISSUE TITLE
falcon error when running ecoli example

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/FALCON#273]
Hi, 

I was trying to install falcon on a server locally but have come across the following issue (falcon ran okay on other server but not this one). Any comments would be greatly appreciated:
```
$ fc_run.py fc_run.cfg logging.ini

2016-01-14 08:34:16,579 - fc_run - INFO - fc_run started with configuration fc_run.cfg
 No target specified, assuming "assembly" as target
```

-- then waited for a minute until the logs below pop up - 

```
2016-01-14 08:35:12,739 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/lustre2/home/ishengtsai/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/lustre2/home/ishengtsai/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 571, in _refreshTargets
    tSortedURLs = PypeGraph(rdfGraph, connectedPypeNodes).tSort( )
  File "/lustre2/home/ishengtsai/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 109, in __init__
    for row in self._RDFGraph.query('SELECT ?s ?o WHERE {?s pype:prereq ?o . }', initNs=dict(pype=pypeNS)):
  File "build/bdist.linux-x86_64/egg/rdflib/graph.py", line 1007, in query
    query_object, initBindings, initNs, **kwargs))
  File "/lustre2/home/ishengtsai/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg/rdfextras/sparql/processor.py", line 31, in query
    strOrQuery = rdfextras.sparql.parser.parse(strOrQuery)
  File "/lustre2/home/ishengtsai/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg/rdfextras/sparql/parser.py", line 794, in parse
    return Query.parseString(stuff)[0]
  File "/home/tk6/.local/lib/python2.7/site-packages/pyparsing-2.0.6-py2.7.egg/pyparsing.py", line 1120, in parseString
    self.streamline()
... (dozens of recursive calls to streamline()) ...
  File "/home/tk6/.local/lib/python2.7/site-packages/pyparsing-2.0.6-py2.7.egg/pyparsing.py", line 2354, in streamline
    self.errmsg = "Expected " + str(self)
  File "/home/tk6/.local/lib/python2.7/site-packages/pyparsing-2.0.6-py2.7.egg/pyparsing.py", line 2555, in __str__
    self.strRepr = "{" + " | ".join(_ustr(e) for e in self.exprs) + "}"
MemoryError
```

**Comment by pb-cdunn** [comment]
Interesting. I didn't know RDFGraph used recursion that way. It almost exceeds the stack-depth.

Anyway, it looks like Python ran out of memory. You'll have to examine why on that specific system, and for the specific input.

**Comment by ishengtsai** [comment]
Hi ,

After testing several possible solutions, I realised it's the incompatibility of python versions. It's now working fine if it points to the python in the falcon package.
