### ISSUE TITLE
incomplete run because 1 pread job failure - how to resolve/restart/ignore

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/FALCON#277]
Hi,

After many falcon runs on at least 5+ species, I finally came across a new species which failed for the first time. I tried to restart falcon by just restarting with the same commands:

$  nohup fc_run.py fc_run.cfg logging.ini &

but there is always one job that seems to fail. The log where failure is shown in both pypeflow.log and nohup.out below. My question is whether this job can be skipped/rescued/restarted, and if so, how do I restart it efficiently? Do I just change the settings in fc_run.cfg, rerun with fc_run.py, and hope this works the next time?

Best,
Jason

section of pypeflow.log  where failure is shown

2016-01-24 09:39:22,142 - pypeflow.task - ERROR - PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',
 'inputDataObjs': {'rdb_build_done': PypeLocalFile('file://localhost/mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-preads_ovl/pdb_build_done', '/mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-pr
eads_ovl/pdb_build_done')},
 'mutableDataObjs': {},
 'outputDataObjs': {'job_done': PypeLocalFile('file://localhost/mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-preads_ovl/job_447f81ef/job_447f81ef_done', '/mnt/nas1/ijt/SpeciesC/falcon_run_
cov108/1-preads_ovl/job_447f81ef/job_447f81ef_done')},
 'parameters': {'config': {'cns_concurrent_jobs': 8,
                           'falcon_sense_option': '--output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat',
                           'falcon_sense_skip_contained': 'False',
                           'input_fofn_fn': 'input.fofn',
                           'input_type': 'raw',
                           'install_prefix': '/home/ijt/bin/FALCON-integrate/fc_env',
                           'job_type': 'local',
                           'length_cutoff': 1000,
                           'length_cutoff_pr': 1000,
                           'openending': False,
                           'overlap_filtering_setting': '--max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24',
                           'ovlp_DBsplit_option': '-x500 -s400',
                           'ovlp_HPCdaligner_option': '-v -M30 -dal128 -t16 -h60 -e.96 -l500 -s1000',
                           'ovlp_concurrent_jobs': 15,
                           'pa_DBsplit_option': '-x500 -s400',
                           'pa_HPCdaligner_option': '-v -M30 -dal128 -t4 -e.70 -l1000 -s1000',
                           'pa_concurrent_jobs': 15,
                           'sge_option_cns': '',
                           'sge_option_da': '',
                           'sge_option_fc': '',
                           'sge_option_la': '',
                           'sge_option_pda': '',
                           'sge_option_pla': '',
                           'target': 'assembly',
                           'use_tmpdir': False},
                'cwd': '/mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-preads_ovl/job_447f81ef',
                'daligner_cmd': 'daligner_p -v -h60 -t16 -H1000 -e0.96 -l500 -s1000 preads.12 preads.1 preads.2 preads.3 preads.4 preads.5 preads.6 preads.7 preads.8 preads.9 preads.10 preads.11 preads.12',
                'db_prefix': 'preads',
                'job_uid': '447f81ef',
                'nblock': 62}}
Traceback (most recent call last):
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 328, in __call__
    return self.runInThisThread(*argv, **kwargv)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 361, in runInThisThread
    self.run(*argv, **kwargv)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 263, in run
    rtn = self._runTask(self, *argv, **kwargv)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 178, in _runTask
    return self._taskFun(self)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 190, in task_run_daligner
    run_script(job_data, job_type = config["job_type"])
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 61, in run_script
    raise Exception(msg)
Exception: Cmd 'bash /mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-preads_ovl/job_447f81ef/rj_447f81ef.sh 1> /mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-preads_ovl/job_447f81ef/rj_447f81ef.sh.log 2>&1' (job 'rj_447f81ef.sh-d_447f81ef_preads-d_447f81ef_preads') returned 35072.

nohup.out Output below

2016-01-26 11:14:38,107 - pypeflow.controller - WARNING - Now, #tasks=301, #alive=1
2016-01-26 11:14:39,695 - fc_run - INFO - '/mnt/nas1/ijt/SpeciesC/falcon_run_cov108/1-preads_ovl/job_53abaad5/job_53abaad5_done.exit' generated. job: 'rj_53abaad5.sh-d_53abaad5_preads-d_53abaad5_preads' exited.
2016-01-26 11:14:39,726 - pypeflow.controller - WARNING - Now, #tasks=301, #alive=0
Traceback (most recent call last):
  File "/home/ijt/bin/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_run.py')
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(*sys.argv)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 566, in main
    main1(*argv)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 543, in main1
    wf.refreshTargets(updateFreq = wait_time) #all
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/ijt/bin/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 706, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'

**Comment by pb-cdunn** [comment]
> After many falcon runs on at least 5+ species, I finally came across a new species which failed for the first time.

Good! 5 of 6 is pretty good for experimental code.

> My question is whether this job can be skipped/rescued/restarted, and if so, how do I restart it efficiently?

I understand what you're saying. Only 1 job failed, and you'd like to get *some* output anyway. Typically, skipping one set of data will only reduce coverage, so there might still be enough useful data for a final assembly.

If the job failed because of an intermittent failure in your system, simply restart. Finished tasks are skipped quickly.

However, if you need to adjust settings, then other tasks might end up re-running too. We plan to do something about that, but not soon.

Your best shot in that case is to alter the generated `.sh` files for *that task only*. Then, run it manually. If you get good data from **daligner**, you can create the `_done` file by hand. *Then*, you can restart the whole workflow and let it continue on.

That's all I can offer for now.

**Comment by ishengtsai** [comment]
Hi Chris,

The problem is when I completed the job manually by running that xxx.sh. But when I restarted falcon using  fc_run.py, it seems to me that fc_run.py recreates all the job_\S\d+ and m_\d+ folders and finished running with 1 job failure again.

Any suggestions? Which part of fc_run.cfg should I be looking at?

Thanks.

**Comment by pb-cdunn** [comment]
See these:
* https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/
* https://dazzlerblog.wordpress.com/command-guides/dazz_db-command-guide/

**Comment by bredeson** [comment]
Hey @ishengtsai,

If you have run the `rj_*.sh` script manually, have you made sure that the corresponding `job_*_done` file is present (and has a more current timestamp than the output `*.las` files)? If you are absolutely sure that the manual `rj_*.sh` job completed successfully, then you may touch the `job_*_done` file yourself (but this is probably not recommended because the `rj_*.sh` script should do this for you if it completes).  I've also found that deleting the `job_*_done.exit` files helps the pipeline restart when there has been a previous failure; otherwise the pipeline get tripped up if there is a `job_*_done.exit` file without also a `job_*_done` file.

`find 0-rawreads -name "job_*_done.exit" | while read file; do rm $file; done`

**Comment by pb-cdunn** [comment]
> I've also found that deleting the job_*_done.exit files helps the pipeline restart when there has been a previous failure; otherwise the pipeline gets tripped up if there is a job_*_done.exit file without also a job_*_done file.

Exactly. That is the current behavior.

Eventually (probably within about 2 weeks) we will separate success (the "done" files) from script completion/exit-status in an obvious way.
