### ISSUE TITLE
fc_ovlp_stats type error when run with no arguments, should give usage instructions

### ISSUE THREAD

**Issue by bwlang** [PacificBiosciences/FALCON#312]
```
[31055]starting ovlp_stats
Traceback (most recent call last):
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/bin/fc_ovlp_stats.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_ovlp_stats.py')
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_ovlp_stats.py", line 5, in <module>
    main(sys.argv)
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/ovlp_stats.py", line 115, in main
    ovlp_stats(**vars(args))
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/ovlp_stats.py", line 99, in ovlp_stats
    try_run_ovlp_stats(n_core, fofn, min_len)
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/ovlp_stats.py", line 79, in try_run_ovlp_stats
    file_list = io.validated_fns(fofn)
  File "/mnt/home/langhorst/src/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/util/io.py", line 157, in validated_fns
    fns = open(fofn).read().strip().split("\n")
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by pb-jchin** [comment]
can you check if your "las.fofn" is valid? what's your command line call?

**Comment by bwlang** [comment]
I just ran it within the top level assembly directory... did not specify
any command line arguments - maybe I missed some documentation...
las.fofn looks valid to me

-rw-rw-r-- 1 langhorst langhorst 16702 Mar 24 15:09 2-asm-falcon/las.fofn
and it's one line per file  pointing to the 1-preads_ovl las_files, which
are resolvable symlinks

top ten lines hexdumped from the first file:
0000000 c1ea 0033 0000 0000 03e8 0000 0014 0000
0000010 0029 0000 0c68 0000 0000 0000 3039 0000
0000020 23ba 0000 0001 0000 3917 000e 99b9 0003
0000030 0033 0000 0005 0333 0007 03e3 0002 03e6
0000040 0004 03e8 0002 03ea 0002 03e8 0007 03e5
0000050 0006 03e4 0004 03e4 0002 0157 0008 0000
0000060 0014 0000 252c 0000 0000 0000 3039 0000
0000070 0b0b 0000 0000 0000 3917 000e bf30 0003
0000080 0033 0000 0002 01e2 000a 03eb 0006 03e5
0000090 0002 0159 000e 0000 001c 0000 1884 0000

I also tried running it in the 2-asm directory, same error.

**Comment by bwlang** [comment]
seems to work fine once i specify the --fofn argument.

**Comment by pb-cdunn** [comment]
That's a reasonable change. We'll add that. Thanks.
