### ISSUE TITLE
falcon immediate crash...doesn't like fasta file?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#32]
Hi, Jason,

I'm now trying yeast and drosophila test datasets.  These are filtered pacbio reads.  (fastq which I converted to fasta).

falcon immediately crashes with this:

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 317, in __call__
    runFlag = self._getRunFlag()
  File "/net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 147, in _getRunFlag
    runFlag = any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters) for f in self._compareFunctions] )
  File "/net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in timeStampCompare
    if min(outputDataObjsTS) < max(inputDataObjsTS):
ValueError: max() arg is an empty sequence

There is one other clue:  In the sge_logs directory build_rdb-af03c270.o4030757 says:

File yeast_filtered.fasta, Line 488307: Pacbio header line name inconsisten
DBsplit: Cannot open ./raw_reads.db for 'r'
cat: raw_reads.db: No such file or directory
HPCdaligner: Cannot open ./raw_reads.db for 'r'

I do notice that the header lines for your ecoli dataset have RQ=0.808 on each line while my 
dataset for yeast and drosophila do not.  Could that be the problem?

Thanks!

**Comment by pb-jchin** [comment]
please check https://github.com/PacificBiosciences/FALCON/issues/27
