### ISSUE TITLE
Job failure: job_0001_done.exit' found but job_0001_done' is missing

### ISSUE THREAD

**Issue by pmhenry** [PacificBiosciences/FALCON#337]
I am running falcon on SLURM for assembly of a ~75Mb genome and continually get a failure saying that jobs_done.exit was found but jobs.done was not. However, there are no _done or _done.exit files in the specified directories. It seems that the program thinks the _done.exit file exists when it does not and then cancels the job before it starts?

The the scripts rj_0000.sh, rj_0001.sh, etc. that failed work when run individually. I restarted fc_run.py after these had finished and it seems to be working now. Just wanted to call attention to this as it was mentioned in [issue #263](https://github.com/PacificBiosciences/FALCON/issues/263) that you may be interested in case studies of glitches, and it seems to be the same problem.

```

[INFO] Skipping already done task: task://localhost/cns_check
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2694
[INFO]tick: 1, #updatedTasks: 0
[INFO] Skipping already done task: task://localhost/build_pdb
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2698
[INFO]tick: 1, #updatedTasks: 0
[INFO]Running task from function task_run_daligner()
[INFO]Running task from function task_run_daligner()
[INFO]Queued 'task://localhost/d_0000_preads' ...
[INFO]Running task from function task_run_daligner()
[INFO]Queued 'task://localhost/d_0001_preads' ...
[INFO]Queued 'task://localhost/d_0002_preads' ...
[INFO](SLURM) '/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0000/rj_0000.sh'
[INFO](SLURM) '/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0002/rj_0002.sh'
[INFO](SLURM) '/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0001/rj_0001.sh'
Submitted batch job 1103251
Submitted batch job 1103253
Submitted batch job 1103252
[INFO]tick: 2, #updatedTasks: 3
[INFO]tick: 4, #updatedTasks: 3
[INFO]tick: 8, #updatedTasks: 3
[INFO]tick: 16, #updatedTasks: 3
[INFO]'/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0001/job_0001_done.exit' found.
[WARNING]'/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0001/job_0001_done' is missing. job: 'rj_0001.sh-d_0001_preads-d_0001_preads' failed!
[INFO]'/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0002/job_0002_done.exit' found.
[WARNING]'/share/pilot-pmhenry/1315-falcon/1-preads_ovl/job_0002/job_0002_done' is missing. job: 'rj_0002.sh-d_0002_preads-d_0002_preads' failed!
[INFO]Failure ('fail'). Joining 'task://localhost/d_0001_preads'...
[INFO]Failure ('fail'). Joining 'task://localhost/d_0002_preads'...
[ERROR]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 2 failure(s) with 0 successes so far.'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Please wait for all threads / processes to terminate !
! Also, maybe use 'ps' or 'qstat' to check all threads,!
! processes and/or jobs are terminated cleanly.        !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING]#tasks=3, #alive=1
[WARNING]Now, #tasks=3, #alive=1
[WARNING]shutdown_event received (Keyboard Interrupt maybe?), 'rj_0000.sh-d_0000_preads-d_0000_preads' not finished.
[INFO]Deleting the job by 'scancel' now...
[WARNING]Now, #tasks=3, #alive=1
[WARNING]Now, #tasks=3, #alive=1
[WARNING]Now, #tasks=3, #alive=0
Traceback (most recent call last):
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.4.0', 'fc_run.py')
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/afs/genomecenter.ucdavis.edu/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 611, in main
    main1(*argv)
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 558, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/software/falcon/0.4.2/x86_64-linux-ubuntu14.04/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 2 failure(s) with 0 successes so far.'
```

**Comment by pb-cdunn** [comment]
Try `fc_run1`. It uses a different system which avoids those glitches.

**Comment by pb-cdunn** [comment]
Oh, I forget. That doesn't have slurm support quite yet. Soon. You can hack that bit of pypeFLOW pretty easily though.

**Comment by pmhenry** [comment]
Yes it wasn't hard to get around. Thanks!
