### ISSUE TITLE
fc_run.py crashing immediately with traceback similar to that when different SMRTcells are mixed in same fasta file

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#34]
Hi, Jason,

Traceback is below.  I know this looks like the traceback when one has sequences in the same fasta file that differ in the characters prior to the "/".  However, I checked (by program) and this is not the case.  Is there any other cause of this error?  Anything I can do to debug it?

Thanks,
David

> fc_run.py fc_run_human.cfg
 No target specified, assuming "assembly" as target 
Your job 4035833 ("build_rdb-92665f66") has been submitted
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 317, in __call__
    runFlag = self._getRunFlag()
  File "/net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 147, in _getRunFlag
    runFlag = any( [ f(self.inputDataObjs, self.outputDataObjs, self.parameters) for f in self._compareFunctions] )
  File "/net/gs/vol1/home/dgordon/falcon/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 812, in timeStampCompare
    if min(outputDataObjsTS) < max(inputDataObjsTS):
ValueError: max() arg is an empty sequence

(several more like this in different threads)

**Comment by pb-jchin** [comment]
This error usually happen when some files that should be generated is not there or there was some problem. The code fail to get the "data objects" and compare their dependence. please check the configuration file and the input.fofn to ensure all data is there.

**Comment by dgordon562** [comment]
800 files, 40,000 sequences in each file.  So checked the input using 2 separate programs.  No problems found.

Any patch you could supply that could report which file is causing the problem?

Otherwise the only way I can think of is to run it on 1st and last 400, then after determining which batch it is, running it on first/last 200 files of that 400, then 1st/last 100...   Any better ideas?

**Comment by dgordon562** [comment]
Narrowed the problem down significantly.  falcon doesn't like ANY of my input fasta files.  In fact, if I give it just 1 sequence in just one fasta file, it still crashes.  Here is the first few lines of one sequence on which falcon crashes.   Can you immediately spot the problem?

>m130928_232712_42213_c100518541910000001823079209281310_s1_p0/6/0_10258
CCCAAAAGAGAAGAGAATTTATTCAGTTTACTGTTTAGGGCACATGAATT
AAGAAGAGTTTCTTCTGAATGGTAAATATTTGTAATTATCTCTTCTTTTA
AAGTCAGATAGATCAGCTGGCAAAGCCATATGGTTTGGTGCCGTTTTGAT
.
.
.

**Comment by pb-jchin** [comment]
Do you miss the ">" of the fasta file?

**Comment by dgordon562** [comment]
No, it is there.  Just didn't copy into the message.   I'm narrowing down the problem, though...  hold on...

**Comment by dgordon562** [comment]
OK.  Found the problem:  falcon doesn't like input files named *.fa  They must be named *.fasta
This file works:
m130928_1_207.subreads.fasta
but a file with identical contents named:
m130928_1_207.subreads.fa
fails.

**Comment by pb-jchin** [comment]
oh.. this is easy now. Gene's daligner code needs the file extension as "*.fasta", not ".fa"
