### ISSUE TITLE
FALCON:make virtualenv: undefined symbol: _PyUnicodeUCS4_AsDefaultEncodedString

### ISSUE THREAD

**Issue by liuqianhn** [PacificBiosciences/FALCON#373]
Hello,

I am installing FALCON. But when I run "make virtualenv", I got the following errors. Any suggestions? Thank you very much! 

The python and OS used are "Python 2.7.9 [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2".
```
> _Installing setuptools, pip, wheel...
>   Complete output from command /home/ql/exomeS...fc_env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
>   Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ql/exomeSoftware/FALCON-integrate/virtualenv/virtualenv_support/pip-7.0.3-py2.py3-none-any.whl/pip/__init__.py", line 4, in <module>
>   File "/opt/python/lib/python2.7/logging/__init__.py", line 26, in <module>
>     import sys, os, time, cStringIO, traceback, warnings, weakref, collections
>   File "/opt/python/lib/python2.7/collections.py", line 9, in <module>
>     from operator import itemgetter as _itemgetter, eq as _eq
> ImportError: /home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS4_AsDefaultEncodedString
> ----------------------------------------
> ...Installing setuptools, pip, wheel...done.
> Traceback (most recent call last):
>   File "virtualenv/virtualenv.py", line 2363, in <module>
>     main()
>   File "virtualenv/virtualenv.py", line 832, in main
>     symlink=options.symlink)
>   File "virtualenv/virtualenv.py", line 1004, in create_environment
>     install_wheel(to_install, py_executable, search_dirs)
>   File "virtualenv/virtualenv.py", line 969, in install_wheel
>     'PIP_NO_INDEX': '1'
>   File "virtualenv/virtualenv.py", line 910, in call_subprocess
>     % (cmd_desc, proc.returncode))
> OSError: Command /home/ql/exomeS...fc_env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
> make: *** [virtualenv] Error 1_
```

**Comment by pb-cdunn** [comment]
This explains your problem:
* https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/CWU07_b1VZY
* https://mail.python.org/pipermail/python-list/2014-February/665940.html
* https://mail.python.org/pipermail/python-list/2014-February/665947.html
You *might* be able to get this working by learning which `libpython.so` is used by your **python** *without* the virtualenv, and then set `LD_LIBRARY_PATH` to include that directory.

We could avoid this problem by switching to Python3, but not everyone can install Python3 on their system. There is no solution which will satisfy everyone.

Good luck!
