### ISSUE TITLE
TaskFailureError: 'Counted 1 failures and Exception of Cmd qsub in the test example for ecoli

### ISSUE THREAD

**Issue by liuqianhn** [PacificBiosciences/FALCON#378]
Hi,

FALCON is an excellent tool. I want to use it in my future work. But after the installation of FALCON, I am trying to run " make run-ecoli" at https://github.com/pb-cdunn/FALCON-examples as test example. I obtained the following exception and error. Could you please help me for letting me know why this exception occurs here? How to solve it? Thank you very much. 
```python
Traceback (most recent call last):
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 328, in __call__
    return self.runInThisThread(*argv, **kwargv)
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 361, in runInThisThread
    self.run(*argv, **kwargv)
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 263, in run
    rtn = self._runTask(self, *argv, **kwargv)
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 178, in _runTask
    return self._taskFun(self)
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 118, in task_build_rdb
    run_script(job_data, job_type = config["job_type"])
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 61, in run_script
    raise Exception(msg)
**Exception: Cmd 'qsub -N prepare_rdb.sh-task_build_rdb-task_build_rdb -pe smp 8 -q production -o /home/ql/exomeSoftware/FALCON-integrate/FALCON-examples/run/ecoli/sge_log -j y                 -S /bin/bash /home/ql/exomeSoftware/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/prepare_rdb.sh' (job 'prepare_rdb.sh-task_build_rdb-task_build_rdb') returned 256.**
2016-05-31 16:02:02,865 - pypeflow.controller - INFO - message for task:///home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb: 'fail'
2016-05-31 16:02:02,865 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task:///home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb'...
2016-05-31 16:02:02,865 - pypeflow.controller - DEBUG - task status: task:///home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb, 'fail', used slots: 1
2016-05-31 16:02:02,865 - pypeflow.controller - DEBUG - task status: task:///home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_make_fofn_abs_raw, 'done', used slots: 1
2016-05-31 16:02:02,866 - pypeflow.controller - ERROR - Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/ql/exomeSoftware/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 706, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
**TaskFailureError: 'Counted 1 failures.'**
2016-05-31 16:02:02,867 - pypeflow.controller - WARNING - #tasks=2, #alive=0
```
Best regards,
Qian Liu

**Comment by pb-cdunn** [comment]
Always try the smaller example first. Were you able to obtain the data for `FALCON-examples/run/synth0`?

Also, always run with `job_type=local` at least once before trying `job_type=sge`.

Finally, even with your set-up, you can probably debug this by looking for log-files. Maybe in `sge_logs`?

**Comment by liuqianhn** [comment]
Thank you very much for your reply.

As you suggested, I have used "fc_run.py fc_run.cfg" under "FALCON-examples/run/synth0", and under "FALCON-examples/run/ecoli" with job_type=local. No errors occur.

Once I commented job_type=local, the same error occurred. What made the difference? 

Thank you very much.

**Comment by pb-cdunn** [comment]
> Once I commented job_type=local in fc_run.cfg in the folder of "FALCON-examples/run/ecoli", the same error occurred. But no error occured after the comment of job_type=local in fc_run.cfg in the folder of "FALCON-examples/run/synth0". What made the difference?

Interesting. I have no idea. You need to view the log-files on your own machine. In theory, those go into `sge_log/*`. If not, then try running the `qsub` command directly from your shell. Somewhere, an error message must give us a clue.

**Comment by liuqianhn** [comment]
Hi, FALCON team,

Thank you very much for your help.

I have fixed the problems now. The problems was caused by the inappropriate cfg files.
