### ISSUE TITLE
FALCON ecoli test case fails

### ISSUE THREAD

**Issue by StefanReuscher** [PacificBiosciences/FALCON#384]
Dear All,

I wanted to give FALCON a try to assemble my rice genome. For now I am unfortunately stuck with running the test case with the three ecoli files.
I installed FALCON via github in my home directory on a cluster using the UNEVA grid engine.
I start the virtual environment:
```
FC=fc_env
. /home/ol-assembler/$FC/bin/activate
```
then I run FALCON:
`fc_run.py fc_run_ecoli.cfg`

my .cfg is:
```
[General]
job_type=sge
input_fofn = input.fofn
input_type = raw
length_cutoff = 12000
genome_size = 4500000
length_cutoff_pr = 12000

#debug is our queue for running toy examples
sge_option_da = -pe mpi 8 -l debug
sge_option_pda = -pe mpi 8 -l debug
sge_option_pla = -pe mpi 2 -l debug
sge_option_fc = -pe mpi 24 -l debug
sge_option_cns = -pe mpi 8 -l debug

pa_concurrent_jobs = 32
cns_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t16 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```

This will run for ca. 15 min and then come down crashing.

```
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='J347c4575c4de990d73d33fcf1e9f288c783dd90a4bec7f123bd5db4f7ecf95d3', cmd='/bin/bash rp_00012.sh', rundir='/lustre3/home/ol-assembler/FALCON-integrate/ecoli_test/0-rawreads/m_00012', options={'sge_option': '-pe mpi 2 -l debug', 'job_type': None}), lang_exe='/bin/bash'))
[INFO]Queued 'task://localhost/m_00001_raw_reads' ...
[INFO]Queued 'task://localhost/m_00010_raw_reads' ...
[INFO]Queued 'task://localhost/m_00003_raw_reads' ...
[INFO]Queued 'task://localhost/m_00020_raw_reads' ...
[INFO]Queued 'task://localhost/m_00009_raw_reads' ...
[INFO]Queued 'task://localhost/m_00013_raw_reads' ...
[INFO]Queued 'task://localhost/m_00016_raw_reads' ...
[INFO]Queued 'task://localhost/m_00014_raw_reads' ...
[INFO]Queued 'task://localhost/m_00005_raw_reads' ...
[INFO]Queued 'task://localhost/m_00015_raw_reads' ...
[INFO]Queued 'task://localhost/m_00002_raw_reads' ...
[INFO]Queued 'task://localhost/m_00012_raw_reads' ...
[INFO]Queued 'task://localhost/m_00018_raw_reads' ...
[INFO]Queued 'task://localhost/m_00019_raw_reads' ...
[INFO]Queued 'task://localhost/m_00008_raw_reads' ...
[INFO]Queued 'task://localhost/m_00011_raw_reads' ...
[INFO]Queued 'task://localhost/m_00006_raw_reads' ...
[INFO]Queued 'task://localhost/m_00004_raw_reads' ...
[INFO]Queued 'task://localhost/m_00017_raw_reads' ...
[INFO]Queued 'task://localhost/m_00007_raw_reads' ...
[INFO]tick: 4, #updatedTasks: 20, sleep_time=0.100000
[INFO]tick: 8, #updatedTasks: 20, sleep_time=0.500000
[ERROR]Task Fred{'URL': 'task://localhost/m_00010_raw_reads'} failed with exit-code=256
[INFO]Failure ('fail'). Joining 'task://localhost/m_00010_raw_reads'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            
  warnings.warn(shutdown_msg)
[ERROR]Task Fred{'URL': 'task://localhost/m_00020_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00002_raw_reads'} failed with exit-code=256
[WARNING]#tasks=20, #alive=19
[INFO]!qdel J9655e4cb6decc8
ol-assembler has deleted job 7057738
[INFO]!qdel J057b56348bc405
ol-assembler has registered the job 7057739 for deletion
[INFO]!qdel J65a44907471de9
The job J65a44907471de9 of user(s) ol-assembler does not exist
#more attempts at deleting jobs...
[ERROR]Task Fred{'URL': 'task://localhost/m_00012_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00004_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00014_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00005_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00015_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00008_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00018_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00001_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00011_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00006_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00013_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00019_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00007_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00009_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00016_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00017_raw_reads'} failed with exit-code=256
[ERROR]Task Fred{'URL': 'task://localhost/m_00003_raw_reads'} failed with exit-code=256
[WARNING]Now, #tasks=20, #alive=0
Traceback (most recent call last):
  File "/lustre3/home/ol-assembler/fc_env/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.5-git.efb7462bab77a1ccca8ed9afae98c5933583214a-', 'fc_run.py')
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.5_git.efb7462bab77a1ccca8ed9afae98c5933583214a_-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.5_git.efb7462bab77a1ccca8ed9afae98c5933583214a_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 542, in main
    main1(argv[0], args.config, args.logger)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/falcon_kit-0.5_git.efb7462bab77a1ccca8ed9afae98c5933583214a_-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 391, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/lustre3/home/ol-assembler/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```
The dirs 1-preads_ovl and 2-asm-falcon are empty. ls -l 0-rawreads shows lots of job_XXXXX and m_XXXXX dirs.

I dont even know where to start debugging. I googled the Task Fred error code=256 but no luck here.

I would appreciate any advice.

Greetings,

Stefan

**Comment by pb-cdunn** [comment]
To start, look in

    0-rawreads/m_00001/pwatcher.dir/stderr

**Comment by StefanReuscher** [comment]
Great advice. This file indicated LAmerge ran out of memory. By default our cluster allows 4 GB. So changing the .cfg to
```
sge_option_da = -pe mpi 8 -l debug
sge_option_la = -pe mpi 2 -l debug -l s_vmem=16G -l mem_req=16G
sge_option_pda = -pe mpi 8 -l debug
sge_option_pla = -pe mpi 2 -l debug -l s_vmem=16G -l mem_req=16G
sge_option_fc = -pe mpi 24 -l debug
sge_option_cns = -pe mpi 8 -l debug
```
worked. It ran longer, for about 30 min, but then crashed again. 

```
[INFO]Success ('done'). Joining 'task://localhost/ct_00008'...
[INFO]Running task from function check_r_cns_task()
[WARNING]Missing taskObj.generated_script_fn for task. Maybe we did not need it? Skipping and continuing.
[INFO]Queued 'task://localhost/cns_check' ...
[INFO]Success ('done'). Joining 'task://localhost/cns_check'...
[INFO]Running task from function task_report_pre_assembly()
[INFO]Report inputs: {'i_raw_reads_db_fn': '/lustre3/home/ol-assembler/FALCON-integrate/ecoli_test/0-rawreads/raw_reads.db', 'i_preads_fofn_fn': '/lustre3/home/ol-assembler/FALCON-integrate/ecoli_test/1-preads_ovl/input_preads.fofn', 'length_cutoff': 12000, 'genome_length': 4500000}
[14150]$ DBdump -h /lustre3/home/ol-assembler/FALCON-integrate/ecoli_test/0-rawreads/raw_reads.db >
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
```
There is a input_preads.fofn with the correct paths to the preads, but nothing else in 1-preads_ovl. There also is a raw_reads.db in 0-rawreads.
DBdump is part of DAZZ_DB. While I have DBrm DBshow DBsplit DBstats fasta2DB the DB_dump is not in the install instructions. Do I need DB_dump too ?

**Comment by StefanReuscher** [comment]
For completion, I manually copied DBdump from FALCON-integrate/DAZZ_DB to ~/$FC/bin/. That worked. Either I got the install wrong or you guys might want to update this page
[https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Complete-example](url)

I also put my final .cfg here just in case (running on the Japanese NIG supercomputer facitily):

```
[General]
job_type=sge
input_fofn = input.fofn
input_type = raw
length_cutoff = 12000
genome_size = 4500000
length_cutoff_pr = 12000

sge_option_da = -pe mpi 8 -l short -l s_vmem=16G -l mem_req=16G #short queue cause it was  most empty of all the queues this time
sge_option_la = -pe mpi 2 -l short -l s_vmem=16G -l mem_req=16G
sge_option_pda = -pe mpi 8 -l short -l s_vmem=16G -l mem_req=16G
sge_option_pla = -pe mpi 2 -l short -l s_vmem=16G -l mem_req=16G
sge_option_fc = -pe mpi 16 -l short -l s_vmem=16G -l mem_req=16G
sge_option_cns = -pe mpi 8 -l short -l s_vmem=16G -l mem_req=16G

pa_concurrent_jobs = 32
cns_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t16 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```

I ended up also running fc_run.py in a wrapper job like:
`qsub -l short fc_wrapper.sh`

where fc_wrapper.sh is:
```
#!/bin/sh
#$ -S /bin/sh
#$ -N FALCON_ecoli_test
#$ -cwd
export FC=fc_env
. /home/ol-assembler/$FC/bin/activate
fc_run.py /home/ol-assembler/FALCON-integrate/ecoli_test/fc_run_ecoli_mpi.cfg
```

**Comment by pb-cdunn** [comment]
It's better to follow this:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki

The `install` rule in the makefile is also used by our TravisCI test, so it's more likely to work for you. But I've updated the other wiki too. Thanks for letting us know what was missing.
