### ISSUE TITLE
falcon failes for example directory as well as for running the genome which we sequenced also

### ISSUE THREAD

**Issue by madhubioinfo** [PacificBiosciences/FALCON#389]
Hi am trying to run for the example data as well as for the genome which we sequenced it gives the following error Help needed 

```py
['/usr/local/bin/fc_run.py', 'fc_run.cfg']
2016-06-18 01:34:06,513 - fc_run - INFO - fc_run started with configuration fc_run.cfg
2016-06-18 01:34:06,513 - fc_run - INFO - fc_run started with configuration fc_run.cfg
 No target specified, assuming "assembly" as target
Traceback (most recent call last):
  File "/usr/local/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.4.0', 'fc_run.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 583, in main
    main1(*argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 403, in main1
    config = support.get_config(support.parse_config(input_config_fn))
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/run_support.py", line 181, in get_config
    "sge_option_da": config.get('General', 'sge_option_da'),
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 669, in _interpolate
    option, section, rawval, e.args[0])
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
        section: [General]
        option : sge_option_da
        key    : jobqueue
        rawval : -pe smp 8 -q %(jobqueue)s
```

**Comment by pb-cdunn** [comment]
You need to set `jobqueue` somewhere in your cfg. See
* https://docs.python.org/2/library/configparser.html
