### ISSUE TITLE
Falcon error

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/FALCON#394]
I'm running falcon and I have the following error message:
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/FALCON-integrate/pypeFLOW/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            
  warnings.warn(shutdown_msg)
[WARNING]#tasks=27, #alive=12
[INFO]Sending signal(9) to pgid=-62362 (pid=62362) based on heartbeat='heartbeat-Je57a2dc6b053cc6be08ec1e000f23ee186ae68efc60f83e256334299e46336e1'
[INFO]Sending signal(9) to pgid=-57951 (pid=57951) based on heartbeat='heartbeat-J8d98f80e0fd18264e2fbb6ccdaac6c4ac00761e856bd3afa3b6db5b485cec732'
[INFO]Sending signal(9) to pgid=-63386 (pid=63386) based on heartbeat='heartbeat-J7772b58b12343b488534a457e6a24cfe702037822c455d9572f3c3678d2111d8'
[INFO]Sending signal(9) to pgid=-62853 (pid=62853) based on heartbeat='heartbeat-J41648dc4896e006fc49135780c4cedad625fc57d56aac7372c29fccae35e63f9'
[INFO]Sending signal(9) to pgid=-50171 (pid=50171) based on heartbeat='heartbeat-J711a749b710796ed15e7c4c058c7ff916f875c7be95a373ce5c05293c35b4b72'
[INFO]Sending signal(9) to pgid=-26774 (pid=26774) based on heartbeat='heartbeat-J91bb9901d7a266431061efc322f3008a07af377bf70a12f0be6c3fa204def945'
[INFO]Sending signal(9) to pgid=-11798 (pid=11798) based on heartbeat='heartbeat-Jb45fe5176561dce791c1c722fc8a6b81b4920f244162ea8439bffa8168f741f6'
[INFO]Sending signal(9) to pgid=-5548 (pid=5548) based on heartbeat='heartbeat-J8b338ce3163ae8a153388d247cdf057035eb86aee4d5896b22c9848b5551148c'
[INFO]Sending signal(9) to pgid=-63537 (pid=63537) based on heartbeat='heartbeat-J64e1b5b233369e5b4e88749205e68196cc77508f9e5a007861b0a4700e9e2ce3'
[INFO]Sending signal(9) to pgid=-56973 (pid=56973) based on heartbeat='heartbeat-Jd5f94bb653a0ed6a9a055383c3494bc541e8a8e5440642224446ed67d2ef3c87'
[INFO]Sending signal(9) to pgid=-64873 (pid=64873) based on heartbeat='heartbeat-Jece18e1dfff0c049d4b031a0268e8195ab9d04edb24e1a560caed3c622d69001'
[ERROR]Task Fred{'URL': 'task://localhost/d_0012_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_0023_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_0013_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_0016_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_0024_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_001a_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_001f_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_0008_raw_reads'} failed with exit-code=99
[ERROR]Task Fred{'URL': 'task://localhost/d_0019_raw_reads'} failed with exit-code=99
[WARNING]Now, #tasks=27, #alive=0
Traceback (most recent call last): 
  File "/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 542, in main
    main1(argv[0], args.config, args.logger)
  File "/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 387, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 197, in alive
    fred.endrun(status)
  File "/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 83, in endrun
    code = int(status.split()[1])
IndexError: list index out of range

Actually for the first fun I have this error message and then I make it run successfully (I just changed the sge options to be empty because I set "job_type = local") even though I don't understand how. Then I run falcon again with another seed_coverage setting in the config file and have again this error message. So what's the cause of this error? Thanks!

**Comment by pb-jchin** [comment]
If you run it again, you might want to have a clean working directory to have a fresh start.  (This may not desirable for large genome though. In such cases, you should know how to manage large amount of jobs on your cluster.)

**Comment by danshu** [comment]
Actually I run falcon in a new directory in local mode.

**Comment by pb-cdunn** [comment]
File "/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 83, in endrun
    code = int(status.split()[1])
    IndexError: list index out of range

I think this is fixed in `master` branch. What happens is that a job finishes and creates the `exit` file, then it writes the exit-code of the sub-process into that file, but because of lag in the network file system, the version of that file with an exit code is not immediately visible to the main program (the run which spawns the qsub jobs or background processes). The fix was to create the first with a different filename, then move it, which is an atomic operation.

**Comment by danshu** [comment]
Thanks for your explanation! Because I'm using FALCON-integrate 0.63/0.64, so has this been fixed in  0.7.1 or should I just use master branch of FALCON-integrate?

**Comment by pb-cdunn** [comment]
Always prefer a "release". But for now, `master` is the same as `0.7.1`.
