### ISSUE TITLE
FALCOM START ERROR

### ISSUE THREAD

**Issue by CHEKNP** [PacificBiosciences/FALCON#407]
I have already install Falcon in my computer, but when I start to run, it come out the error message. What wrong with Falcon？ How to solve this problem? Thanks!
```
### [INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target 
/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:317: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task:///home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_make_fofn_abs_raw
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_build_rdb()
[INFO]script_fn:'/home/timothy/software/falcon/test/0-rawreads/prepare_rdb.sh'
[INFO]jobid=J2273dea25d8374e83a3f1788ffedee8b00fa5f7623e19679e3c4e715b5b00ff2
[INFO]starting job Job(jobid='J2273dea25d8374e83a3f1788ffedee8b00fa5f7623e19679e3c4e715b5b00ff2', cmd='/bin/bash prepare_rdb.sh', rundir='/home/timothy/software/falcon/test/0-rawreads', options={'sge_option': '-pe smp 8 -q bigmem', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='J2273dea25d8374e83a3f1788ffedee8b00fa5f7623e19679e3c4e715b5b00ff2', cmd='/bin/bash prepare_rdb.sh', rundir='/home/timothy/software/falcon/test/0-rawreads', options={'sge_option': '-pe smp 8 -q bigmem', 'job_type': None}), lang_exe='/bin/bash'))
[ERROR]Task Fred{'URL': 'task:///home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb'} failed with exit-code=256
[INFO]Queued 'task:///home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb' ...
[INFO]Failure ('fail'). Joining 'task:///home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            
  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "/home/timothy/software/falcon/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023', 'fc_run.py')
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 559, in main
    main1(argv[0], args.config, args.logger)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 325, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 382, in run
    wf.refreshTargets([rdb_build_done])
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

**Comment by pb-cdunn** [comment]
You can get a lot of information by looking in `pwatcher.dir/stderr` in the directory of a failed job.

But in general, you need to run first with `job_type=local`. In fact, you should run `make test` first, which will run a tiny test-case in `FALCON-examples/run/synth0`.

**Comment by CHEKNP** [comment]
Thanks for your kindly help. I have already set the job_type=local. While, in the mypwatcher fold, it do not contain a stderr fold. And it also come out an problems. What is wrong with it ? Here it says:

- 
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run_ecoli.cfg
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[INFO] No target specified, assuming "assembly" as target 
/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:317: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task:///home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_make_fofn_abs_raw
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task:///home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 4
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task://localhost/d_0000_raw_reads
[INFO] Skipping already done task: task://localhost/rda_check
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 5
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task://localhost/m_00001_raw_reads
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 8
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task://localhost/ct_00001
[INFO] Skipping already done task: task://localhost/cns_check
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_report_pre_assembly()
[INFO]Report inputs: {'i_raw_reads_db_fn': '/home/timothy/software/falcon/ecoli/0-rawreads/raw_reads.db', 'i_preads_fofn_fn': '/home/timothy/software/falcon/ecoli/1-preads_ovl/input_preads.fofn', 'length_cutoff': 12000, 'genome_length': 0}
[5054]$ DBdump -h /home/timothy/software/falcon/ecoli/0-rawreads/raw_reads.db >
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            
  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=1
[WARNING]Now, #tasks=1, #alive=0
Traceback (most recent call last):
  File "/home/timothy/software/falcon/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023', 'fc_run.py')
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 559, in main
    main1(argv[0], args.config, args.logger)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 325, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 443, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 131, in alive
    fred.generate() # -> taskObj->generated_script_fn by convention
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 62, in generate
    self.__target()
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 276, in __call__
    return self.runInThisThread(*argv, **kwargv)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 296, in runInThisThread
    return self.run(*argv, **kwargv)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/pwatcher_bridge.py", line 312, in run
    rtn = self._runTask(self, *argv, **kwargv)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 190, in _runTask
    return self._taskFun(self)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 145, in task_report_pre_assembly
    report_dict = stats_preassembly.calc_dict(**kwds)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 191, in calc_dict
    stats_preads = stats_from_sorted_readlengths(preads)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 101, in stats_from_sorted_readlengths
    p95 = percentile(read_lens, 0.95)
  File "/home/timothy/software/falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 95, in percentile
    return read_lens[int(len(read_lens)*p)]
IndexError: list index out of range

-

**Comment by pb-cdunn** [comment]
That happens when `read_lens` has length 0, which should never happen.

Try the tiny test-case first. After that, you may have to debug. Everyone's system is different. From the stack-trace, I would first try repeating the `DBdump` command.
