### ISSUE TITLE
Falcon_unzip keeps crashing

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [PacificBiosciences/FALCON#429]
Yesterday I re-installed to most recent FALCON and FALCON_UNZIP versions.

FALCON run through smoothly. But FALCON_UNZIP keeps crashing.

This is the output on the console (not everything, just before the crash message to the enc):
```py
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 505, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 347, in __call__
>     return self.runInThisThread(*argv, **kwargv)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 368, in runInThisThread
>     self.run(*argv, **kwargv)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 276, in run
>     rtn = self._runTask(self, *argv, **kwargv)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 190, in _runTask
>     return self._taskFun(self)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/falcon_unzip-0.1.0-py2.7.egg/falcon_unzip/unzip.py", line 217, in task_run_blasr
>     run_script(job_data, job_type = config["job_type"])
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/falcon_unzip-0.1.0-py2.7.egg/falcon_unzip/unzip.py", line 101, in run_script
>     rc = _run_script(job_data)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/falcon_unzip-0.1.0-py2.7.egg/falcon_unzip/unzip.py", line 71, in _run_script_local
>     system(cmd, check=True)
>   File "/home/bioinf/falcon/FALCON-integrate_2016Aug/fc_env/lib/python2.7/site-packages/falcon_unzip-0.1.0-py2.7.egg/falcon_unzip/unzip.py", line 28, in system
>     raise Exception(msg)
> Exception: Call 'bash /home/bioinf/falcon/FALCON-integrate_2016Aug/FGA2_2/./3-unzip/0-phasing/000060F/aln_000060F.sh 1> /home/bioinf/falcon/FALCON-integrate_2016Aug/FGA2_2/./3-unzip/0-phasing/000060F/aln_000060F.sh.log 2>&1' returned 32512.
```
And this is my config file for FALCON_UNZIP:
```ini
> [General]
> job_type = local
> 
> [Unzip]
> input_fofn= input.fofn
> 
> smrt_bin=
> 
> jobqueue =
> sge_phasing=
> sge_quiver=
> sge_track_reads=
> sge_blasr_aln=
> sge_hasm=
> unzip_concurrent_jobs = 1
> quiver_concurrent_jobs = 1
> 
```
And here the config for the FALCON run before (sinze this is more of a test, the parametrization is far from optimal):
```ini
> [General]
> job_type = local
> 
> input_fofn = input.fofn
> 
> input_type = raw
> 
> length_cutoff = 13000
> 
> length_cutoff_pr = 12000
> 
> jobqueue = production
> sge_option_da =
> sge_option_la =
> sge_option_pda =
> sge_option_pla =
> sge_option_fc =
> sge_option_cns =
> 
> pa_concurrent_jobs = 4
> cns_concurrent_jobs = 4
> ovlp_concurrent_jobs = 4
> 
> pa_HPCdaligner_option =  -v -B4 -t4 -e.70 -l1000 -s1000
> ovlp_HPCdaligner_option = -v -B4 -t4 -h60 -e.96 -l500 -s1000
> 
> pa_DBsplit_option = -x500 -s100
> ovlp_DBsplit_option = -x500 -s100
> 
> falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 10
> 
> overlap_filtering_setting = --min_cov 1 --max_cov 3000 --max_diff 2000 --bestn 10 --n_core 20
```

**Comment by pb-cdunn** [comment]
> `/home/bioinf/falcon/FALCON-integrate_2016Aug/FGA2_2/./3-unzip/0-phasing/000060F/aln_000060F.sh.log`

Have you examined that log-file?

**Comment by MichaelsGITIGIT** [comment]
Shame on me. I forgot to install blasr.

Thx!

**Comment by pb-cdunn** [comment]
Someday, we'll add something to validate dependencies early and transparently. todo.
