### ISSUE TITLE
slurm

### ISSUE THREAD

**Issue by hermeseduardo** [PacificBiosciences/FALCON#438]
trying to run one of the examples of Falcon, with SLURM so far getting the error message bellow, any hint?
```py
Traceback (most recent call last):
  File "/apps/falcon/0.3.0/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023', 'fc_run.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1504, in run_script
    
  File "/apps/falcon/0.3.0/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 1, in <module>
    from falcon_kit.mains.run1 import main
  File "/apps/falcon/0.3.0/lib/python2.7/site-packages/falcon_kit-0.7+git.6bb263a10520cf6fe6ea7caa0ce1cf39f847c023-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 5, in <module>
    from pypeflow.pwatcher_bridge import PypeProcWatcherWorkflow, MyFakePypeThreadTaskBase
ImportError: No module named pypeflow.pwatcher_bridge
```

**Comment by pb-cdunn** [comment]
Your **FALCON** and **pypeFLOW** are not consistent versions. Try **FALCON-integrate**; maybe its wiki can help.
