### ISSUE TITLE
submitting jobs on SLURM (q parameter)

### ISSUE THREAD

**Issue by brkldj** [PacificBiosciences/FALCON#473]
Hi,

after installing Falcon on a SLURM cluster I want to run it on the test E. coli data. My fc_run.cfg is heavily inspired by @JohnUrban's [Issue 50](https://github.com/PacificBiosciences/FALCON-integrate/issues/50) and I paste it at the bottom. I assume that I should start fc_run.py and this script will submit jobs to the cluster.

fc_run.py quickly crashed (see the log below) and it looks like it is due to the "q" parameter that SLURM does not like. Since it is not in the config file, what can I do about it?

```
[brkldj@int2 falcon_ecoli]$ ~/software/FALCON-integrate/fc_env/bin/fc_run.py fc_run.Slurm.cfg
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.Slurm.cfg
[INFO] No target specified, assuming "assembly" as target 
/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/run_support.py:341: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_make_fofn_abs_raw()
[INFO]script_fn:'noop.sh'
[INFO]jobid=Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878
[INFO]starting job Job(jobid='Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878', cmd='/bin/bash noop.sh', rundir='/lustre4/0/taof/falcon_ecoli', options={'job_queue': 'default', 'sge_option': '', 'job_type': 'SLURM'})
[INFO]!sbatch -J Jfaddbf7fb358bc -q default  -D /lustre4/0/taof/falcon_ecoli/mypwatcher/jobs/Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878 -o stdout -e stderr --wrap="/bin/bash /lustre4/0/taof/falcon_ecoli/mypwatcher/wrappers/run-Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878.bash"
sbatch: invalid option -- 'q'
Try "sbatch --help" for more information
[ERROR]In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSlurm(MetaJob(job=Job(jobid='Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878', cmd='/bin/bash noop.sh', rundir='/lustre4/0/taof/falcon_ecoli', options={'job_queue': 'default', 'sge_option': '', 'job_type': 'SLURM'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 520, in cmd_run
    state.submit_background(bjob)
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 411, in submit
    system(sge_cmd, checked=True) # TODO: Capture sbatch-jobid
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 539, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 256 <- 'sbatch -J Jfaddbf7fb358bc -q default  -D /lustre4/0/taof/falcon_ecoli/mypwatcher/jobs/Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878 -o stdout -e stderr --wrap="/bin/bash /lustre4/0/taof/falcon_ecoli/mypwatcher/wrappers/run-Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878.bash"'
[WARNING]  File "/home/brkldj/software/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 662, in main
    main1(argv[0], args.config, args.logger)
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 423, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 457, in run
    wf.refreshTargets([fofn_abs_task])
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 199, in alive
    fred.endrun('UNSUBMITTED')
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 92, in endrun
    log.warning(''.join(traceback.format_stack()))

[ERROR]Task Fred{'URL': 'task:///nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw'}
 is UNSUBMITTED, meaning job-submission somehow failed. Possibly a re-start would work. Otherwise, you need to investigate.
[INFO]Queued 'task:///nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw' ...
[INFO]Failure ('fail'). Joining 'task:///nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            
  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "/home/brkldj/software/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 662, in main
    main1(argv[0], args.config, args.logger)
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 423, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/nfs/home3/brkldj/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 457, in run
    wf.refreshTargets([fofn_abs_task])
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/nfs/home3/brkldj/software/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

fc_run.cfg:
```
[General]
# list of files of the initial subread fasta files
input_fofn = input.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

# Cluster queue setting
job_type = SLURM
jobqueue = serial
sge_option_da = --ntasks 1 --nodes 1 --cpus-per-task 8 --mem 10g --time 00:20:00 
sge_option_la = --ntasks 1 --nodes 1 --cpus-per-task 2 --mem 10g --time 00:05:00 
sge_option_pda = --ntasks 1 --nodes 1 --cpus-per-task 8 --mem 15g --time 00:20:00 
sge_option_pla = --ntasks 1 --nodes 1 --cpus-per-task 2 --mem 10g --time 00:05:00 
sge_option_fc = --ntasks 1 --nodes 1 --cpus-per-task 16 --mem 10g --time 00:20:00 
sge_option_cns = --ntasks 1 --nodes 1 --cpus-per-task 8 --mem 10g --time 00:20:00 

# concurrency settgin
pa_concurrent_jobs = 24
cns_concurrent_jobs = 24
ovlp_concurrent_jobs = 24

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

# error correction consensus optione
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

# overlap filtering options
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10
```

**Comment by pb-cdunn** [comment]
Could you tell us what slurm command *does* work? We don't have slurm here, so we rely on users. We need to be able to specify the job_queue somehow. That's possible with Slurm, right?

For testing, you do not need to run Falcon. Just run `sbatch` commands directly -- with a dummy script -- and please post verbatim what works.

**Comment by roblehmann** [comment]
Hey,

@pb-cdunn
I had the same problem with slurm version (16.05.6.) and the current FALCON version. The problem was the sbatch invocation of pypeFLOW/pwatcher/fs_based.py in line 407:

```
        sge_cmd = 'sbatch -J {job_name} -q {job_queue} {sge_option} -D {cwd} -o stdout -e stderr --wrap="{exe} {script_fn}"'.format(
                **locals())
```
 I simply removed the wrong parameter:

```
        sge_cmd = 'sbatch -J {job_name} {sge_option} -D {cwd} -o stdout -e stderr --wrap="{exe} {script_fn}"'.format(
                **locals())
```

The same should probably happen in pypeFLOW/pwatcher/network_based.py

cheers

**Comment by pb-cdunn** [comment]
@roblehmann, the solution submitted by a user has already been merged:
* https://github.com/PacificBiosciences/pypeFLOW/pull/42

Will that work for you? If so, simply update pypeFLOW.

(Your solution requires the queue name to be included in "sge_option".)
