### ISSUE TITLE
Error of running

### ISSUE THREAD

**Issue by Mr-Inamn** [PacificBiosciences/FALCON#484]
Hi, 
Thank you for supplying us a good example to test FALCON. 
But when I run fc_run.py fc_run.cfg. Something wrong happened. It appeared:
```
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[ERROR]Failed to parse config "fc_run.cfg".
Traceback (most recent call last):
  File "/share/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 422, in main1
    config = support.get_dict_from_old_falcon_cfg(support.parse_config(input_config_fn))
  File "/share/app/FALCON-integrate/FALCON/falcon_kit/run_support.py", line 237, in get_dict_from_old_falcon_cfg
    ' from "falcon_sense_option" in your cfg: %s' %repr(falcon_sense_option))
Exception: Please remove obsolete "--local_match_count_*" or "--output_dformat" from "falcon_sense_option" in your cfg: '--output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6'
Traceback (most recent call last):
  File "/share/app/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/share/app/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/share/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 668, in main
    main1(argv[0], args.config, args.logger)
  File "/share/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 422, in main1
    config = support.get_dict_from_old_falcon_cfg(support.parse_config(input_config_fn))
  File "/share/app/FALCON-integrate/FALCON/falcon_kit/run_support.py", line 237, in get_dict_from_old_falcon_cfg
    ' from "falcon_sense_option" in your cfg: %s' %repr(falcon_sense_option))
Exception: Please remove obsolete "--local_match_count_*" or "--output_dformat" from "falcon_sense_option" in your cfg: '--output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6'

```
Then I deleted --local_match_count_threshold 2 in file fc_run.cfg and run fc_run.py fc_run.cfg again. It appeared:
```
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
[INFO] No target specified, assuming "assembly" as target
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/share/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/share/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]job_type='SGE', job_queue='default'
[INFO]Num unsatisfied: 1
[INFO]About to submit: Node(0-rawreads/raw-fofn-abs)
[INFO]starting job Job(jobid='Pab56a8beac8601', cmd='/bin/bash run.sh', rundir='/public/home/lijing/faclon_test/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q jobqueue', 'job_type': 'SGE'})
[INFO]!qsub -N Pab56a8beac8601 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /public/home/lijing/faclon_test/mypwatcher/wrappers/run-Pab56a8beac8601.bash
Unable to run job: Job was rejected because job requests unknown queue "default".
Exiting.
[ERROR]In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSge(MetaJob(job=Job(jobid='Pab56a8beac8601', cmd='/bin/bash run.sh', rundir='/public/home/lijing/faclon_test/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q jobqueue', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/share/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 520, in cmd_run
    state.submit_background(job)

  File "/share/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/share/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 296, in submit
    system(sge_cmd, checked=True) # TODO: Capture q-jobid
  File "/share/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 539, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 256 <- 'qsub -N Pab56a8beac8601 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /public/home/lijing/faclon_test/mypwatcher/wrappers/run-Pab56a8beac8601.bash'
[ERROR]Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])
[WARNING]Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
[INFO]sleep 0.1
[INFO]Num unsatisfied: 2
[INFO]About to submit: Node(0-rawreads/raw-fofn-abs)
[INFO]starting job Job(jobid='Pab56a8beac8601', cmd='/bin/bash run.sh', rundir='/public/home/lijing/faclon_test/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q jobqueue', 'job_type': 'SGE'})
[INFO]!qsub -N Pab56a8beac8601 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /public/home/lijing/faclon_test/mypwatcher/wrappers/run-Pab56a8beac8601.bash
Unable to run job: Job was rejected because job requests unknown queue "default".
```
I have no idea about this mistake information. Could anyone give me some help? Thanks a lot.

**Comment by lijingjing1** [comment]
jobqueue should set you own type not default.

**Comment by pb-cdunn** [comment]
Also, I don't know where this `fc_run.cfg` came from. It's better to use **FALCON-examples**, which is supplied by **FALCON_integrate**. The `run/synth0` example should be fine, since that is run in TravisCI regularly.

**Comment by jasonsydes** [comment]
I could be mistaken, but I'm pretty sure that @Mr-Inamn's built his fc_run.cfg according to this page:

https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Running

... because I just did the same, and got the same errors.  

Good to know about the FALCON-examples!

**Comment by pb-cdunn** [comment]
Updated wiki. Thanks.
