### ISSUE TITLE
Running FALCON-integrate with virtualenv

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON#494]
**To whom it may concern,**

**I have decided to re-install and re-run the human de novo assembly as discussed in #491 to be able to run FALCON_UNZIP. I have highlighted the questions and comments in bold.**

**I have been able to successfully install and test the FALCON-integrate using the following cmd line**s.
```sh
export GIT_SYM_CACHE_DIR=~/.git-sym-cache # to speed things up
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master  # or whatever version you want
make init
mkdir -p fc_env
virtualenv fc_env 
source env.sh
make config-edit-user
make -j all
make test  # to run a simple one
```
**I was able to check that make test was successful. In addition, I was able to assemble the Arabidopis lyrata using the data provided in  http://datasets.pacb.com.s3.amazonaws.com/2014/Arabidopsis-lyrata/A_lyrata_ssp_lyrata using `job_type=local`

**I wanted to thereafter check whether I can run the FALCON with the sun grid engine.** 

**I activated the virtual environment**

    . /ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env/bin/activate

**and here is the fc_run.cfg**
```ini
[General]
#job_type = local

#list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 8000

job_queue = pac.q
sge_option_da = -V -pe peXMAS 8 -q %(job_queue)s
sge_option_la = -V -pe peXMAS 2 -q %(job_queue)s
sge_option_pda = -V -pe peXMAS 8 -q %(job_queue)s
sge_option_pla = -V -pe peXMAS 2 -q %(job_queue)s
sge_option_fc = -V -pe peXMAS 24 -q %(job_queue)s
sge_option_cns = -V -pe peXMAS 8 -q %(job_queue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```
`fc_run.py fc_run.cfg` returned:
```
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]job_type='SGE', job_queue='pac.q', sge_option='-pe peXMAS 8 -q pac.q'
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(0-rawreads/raw-fofn-abs)
[INFO]starting job Job(jobid='P9760aa915460e7', cmd='/bin/bash run.sh', rundir='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/0-rawreads/raw-fofn-abs', options={'job_queue': 'pac.q', 'sge_option': '-pe peXMAS 8 -q pac.q', 'job_type': 'SGE'})
[INFO]!qsub -N P9760aa915460e7 -q pac.q -pe peXMAS 8 -V -cwd -o stdout -e stderr -S /bin/bash /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/mypwatcher/wrappers/run-P9760aa915460e7.bash
Your job 3556916 ("P9760aa915460e7") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P9760aa915460e7', cmd='/bin/bash run.sh', rundir='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/0-rawreads/raw-fofn-abs', options={'job_queue': 'pac.q', 'sge_option': '-pe peXMAS 8 -q pac.q', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
[INFO]sleep 0.1s
[INFO]sleep 0.2s
[INFO]sleep 0.3s
[INFO]sleep 0.4s
[INFO]sleep 0.5s
[INFO]sleep 0.6s
[INFO]sleep 0.7s
[INFO]sleep 0.8s
[INFO]sleep 0.9s
[INFO]sleep 1.0s
[INFO]sleep 1.1s
[INFO]sleep 1.2s
[INFO]sleep 1.3s
[INFO]sleep 1.4s
[INFO]sleep 1.5s
[ERROR]Task Node(0-rawreads/raw-fofn-abs) failed with exit-code=99
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/raw-fofn-abs)])
[ERROR]ready: set([])
submitted: set([])
[INFO]!qdel -k P9760aa915460e7
The job -k of user(s) sjinlee does not exist
job 3556916 is already in deletion
```
```py
Traceback (most recent call last):
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 482, in main
    main1(argv[0], args.config, args.logger)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 143, in main1
    input_fofn_plf=input_fofn_plf,
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 177, in run
    wf.refreshTargets([fofn_abs_task])
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 209, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 276, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/raw-fofn-abs)])
```
**when I checked the mypwatcher/jobs/P9760aa915460e7/stderr** 

/mnt/ruby/Tools/python/Python-2.7.6/bin/python2.7: No module named pwatcher.mains

**the mypwatcher/jobs/P9760aa915460e7/stdout indicates that virtual envrionement has been activated. I have highlighted the PATH and VIRTUAL_ENV in bold**
```
JRE=/ruby/Tools/jdk1.7.0_45
MANPATH=/mnt/ruby/ge2011.11/man:/mnt/ruby/ge2011.11/man:/usr/man:/ruby/Tools/jdk1.7.0_45/man:/ruby/Tools/jdk1.7.0_45/man:/ruby/Tools/jdk1.7.0_45/man:/ruby/Tools/jdk1.7.0_45/man
HOSTNAME=cm147
SGE_TASK_STEPSIZE=undefined
JDK=/ruby/Tools/jdk1.7.0_45
TERM=xterm
SHELL=/bin/bash
NHOSTS=1
HISTSIZE=1000
SGE_O_WORKDIR=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/mypwatcher/jobs/P9760aa915460e7
TMPDIR=/tmp/3556916.1.pac.q
SSH_CLIENT=172.16.100.20 39403 22
SGE_O_HOME=/home/sjinlee
SGE_ARCH=linux-x64
SGE_CELL=m3
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
RESTARTED=0
SSH_TTY=/dev/pts/8
ARC=linux-x64
USER=sjinlee
LD_LIBRARY_PATH=/mnt/ruby/ge2011.11/lib/linux-x64:/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/python/Anaconda2/lib:/mnt/ruby/ge2011.11/lib/linux-x64
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01
SGE_TASK_LAST=undefined
QUEUE=pac.q
**VIRTUAL_ENV=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env**
SGE_TASK_ID=undefined
SGE_BINARY_PATH=/mnt/ruby/ge2011.11/bin/linux-x64
MAIL=/var/spool/mail/sjinlee
**PATH=/ruby/Tools/jdk1.7.0_45/bin:/ruby/Tools/jdk1.7.0_45/bin:/mnt/ruby/Tools/python/Python-2.7.6/bin:/ruby/Tools/blast/blast-2.2.12/bin:/ruby/Tools/00.bin/:/ruby/Tools/jdk1.7.0_45/bin:/ruby/Tools/R/R-3.2.1/bin::/mnt/ruby/ge2011.11/bin/l**
SGE_STDERR_PATH=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/mypwatcher/jobs/P9760aa915460e7/stderr
PWD=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/mypwatcher/jobs/P9760aa915460e7
XMODIFIERS=@im=none
SGE_STDOUT_PATH=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/mypwatcher/jobs/P9760aa915460e7/stdout
SGE_ACCOUNT=sge
SGE_EXECD_PORT=6445
KDE_IS_PRELINKED=1
LANG=en_US.UTF-8
JOB_SCRIPT=/mnt/ruby/ge2011.11/m3/spool/cm147/job_scripts/3556916
JOB_NAME=P9760aa915460e7
SGE_QMASTER_PORT=6444
MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
KDEDIRS=/usr
SGE_ROOT=/mnt/ruby/ge2011.11
LOADEDMODULES=
REQNAME=P9760aa915460e7
SGE_JOB_SPOOL_DIR=/mnt/ruby/ge2011.11/m3/spool/cm147/active_jobs/3556916.1
ENVIRONMENT=BATCH
HISTCONTROL=ignoredups
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
PE_HOSTFILE=/mnt/ruby/ge2011.11/m3/spool/cm147/active_jobs/3556916.1/pe_hostfile
SHLVL=3
HOME=/home/sjinlee
SGE_CWD_PATH=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/09.arabidopsis/falcon2/mypwatcher/jobs/P9760aa915460e7
NQUEUES=1
SGE_O_LOGNAME=sjinlee
SGE_O_MAIL=/var/spool/mail/sjinlee
DRMAA_LIBRARY_PATH=/mnt/ruby/ge2011.11/lib/linux-x64/libdrmaa.so
TMP=/tmp/3556916.1.pac.q
JOB_ID=3556916
LOGNAME=sjinlee
QTLIB=/usr/lib64/qt-3.3/lib
CVS_RSH=ssh
PE=peXMAS
CLASSPATH=:.:/ruby/Users/miraroh/classes/:/ruby/Tools/jdk1.7.0_45/lib/*::.:/ruby/Users/miraroh/classes/:/ruby/Tools/jdk1.7.0_45/lib/*:
SSH_CONNECTION=172.16.100.20 39403 172.16.140.31 22
SGE_TASK_FIRST=undefined
MODULESHOME=/usr/share/Modules
LESSOPEN=|/usr/bin/lesspipe.sh %s
SGE_O_PATH=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env/bin:ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/python/Anaconda2/bin:/ruby/Tools/jdk1.7.0_45/bin:/ruby/Tools/jdk1.7.0_45/bi
SGE_O_HOST=cm121
SGE_O_SHELL=/bin/bash
SGE_CLUSTER_NAME=p6444
REQUEST=P9760aa915460e7
NSLOTS=8
SGE_STDIN_PATH=/dev/null
G_BROKEN_FILENAMES=1
module=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/usr/bin/printenv
```
**I have previously looked at the issue in https://github.com/PacificBiosciences/FALCON-integrate/issues/60 which had a similar problem, but I didn't have the "funny lines" that caused the problems in .bashrc. I was wondering if you could provide any assistance solving this problem. I have been trying various methods and they have all been failing.**

Best,
Jin

**Comment by pb-cdunn** [comment]
This is an installation problem. It is difficult to solve that remotely, but I will try to help.

    which python

I think you will see `/mnt/ruby/Tools/python/Python-2.7.6/bin/python`, as your environment does not including `PYTHONPATH` and your `PATH` does not include the path of your virtual-env.

    virtualenv fc_env 

Where did you find directions for virtualenv? That is wrong, given the lines which follow.

    source env.sh
    make config-edit-user

That will perform a python "user" install, which relies on `PYTHONUSERBASE`. (You can google that.) You need to run `source env.sh` in the shell in which you start your jobs. You should see `PYTHONUSERBASE` in your environment.

* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation

I don't recommend virtualenv, but you can use it if you want. Just create your virtualenv and do a "system install" into it.

**Comment by sjin09** [comment]
**In the FALCON 0.4.0 there was make virtualenv. I looked at what make virtualenv. and I thought what it does would be sufficient after make init. Therefore, I did virtualenv fc_env to try to do the same.**

mkdir -p /ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env
python2.7 virtualenv/virtualenv.py --no-site-packages  --always-copy /ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env

**Comment by sjin09** [comment]
Dear @pb-cdunn 

**I have managed to correctly install using the installation guide (https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation).**

**I have created env.sh with the following lines**

#!/bin/bash
FALCON_WORKSPACE=/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate
PYTHONUSERBASE=/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH

The problem was /mnt/ruby/Tools/env/sjinlee_profile where PYTHON=/mnt/ruby/Tools/python/Anaconda/bin was specified, and therefore queue was constantly trying to use this python for the jobs. I changed this PYTHON PATH to PYTHON with which I used to install FALCON.

Thank you so much!
Jin

**Comment by pb-cdunn** [comment]
Btw, if you prefer to use a virtualenv, then you need `make config-edit` instead of `make config-edit-user`. A non-user install goes directly into your Python site-packages. `make config-standard` would also work, but then you would need a force-install to upgrade any Python packages which have not bumped their version numbers, and you would need to remember to reinstall whenever the Python code changes. `pip install --edit` uses something like a symlink.

Anyway, I'm glad you got it working.
