### ISSUE TITLE
 Task Node(0-rawreads) failed with exit-code=256

### ISSUE THREAD

**Issue by zhanghaoipp** [PacificBiosciences/FALCON#496]
Dear Falcon team,

I am new on falcon and want to denovo a fungal genme, but it failed, could you help me about it? the ctg file is as below:
```ini
[General]
job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn
input_type = raw
#input_type = preads
genome_size = 40000000
seed_coverage = 70

# The length cutoff used for seed reads used for initial mapping
length_cutoff = -1

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 2000
jobqueue = production
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s
pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
pa_HPCdaligner_option =  -v -B24 -t8 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B24 -t16 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s100
ovlp_DBsplit_option = -x500 -s100
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 1000 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 4 --bestn 10 --n_core 24 
```
It showed error as:
```
fc_run fc_run.cfg logging.ini
2016-11-27 16:30:48,350 - fc_run - INFO - Setup logging from file "logging.ini".
2016-11-27 16:30:48,350 - fc_run - INFO - fc_run started with configuration fc_run.cfg
2016-11-27 16:30:48,351 - fc_run - INFO -  No target specified, assuming "assembly" as target 
/home/bac/software/FALCON-integrate/FALCON/falcon_kit/run_support.py:349: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
2016-11-27 16:30:48,351 - pypeflow.simple_pwatcher_bridge - WARNING - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/bac/software/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2016-11-27 16:30:48,351 - pypeflow.simple_pwatcher_bridge - INFO - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/bac/software/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2016-11-27 16:30:48,352 - pypeflow.simple_pwatcher_bridge - INFO - job_type='local', job_queue='default'
2016-11-27 16:30:48,353 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 1
2016-11-27 16:30:48,353 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2016-11-27 16:30:48,354 - pwatcher.fs_based - INFO - starting job Job(jobid='Pf8747d65204d75', cmd='/bin/bash run.sh', rundir='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2016-11-27 16:30:48,356 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pf8747d65204d75', cmd='/bin/bash run.sh', rundir='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2016-11-27 16:30:48,357 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1
2016-11-27 16:30:48,457 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.2
2016-11-27 16:30:48,658 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2016-11-27 16:30:48,658 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 1
2016-11-27 16:30:48,658 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 0
2016-11-27 16:30:48,660 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 2
2016-11-27 16:30:48,660 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads)
2016-11-27 16:30:48,661 - pwatcher.fs_based - INFO - starting job Job(jobid='Pe1cb08cea30388', cmd='/bin/bash run.sh', rundir='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2016-11-27 16:30:48,664 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pe1cb08cea30388', cmd='/bin/bash run.sh', rundir='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2016-11-27 16:30:48,664 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1
2016-11-27 16:30:48,764 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.2
2016-11-27 16:30:48,965 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.3
2016-11-27 16:30:49,266 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.4
2016-11-27 16:30:49,667 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.5
2016-11-27 16:30:50,168 - pypeflow.simple_pwatcher_bridge - ERROR - Task Node(0-rawreads) failed with exit-code=256
2016-11-27 16:30:50,169 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([])
2016-11-27 16:30:50,169 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 0
2016-11-27 16:30:50,169 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 1
2016-11-27 16:30:50,169 - pypeflow.simple_pwatcher_bridge - ERROR - Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
2016-11-27 16:30:50,169 - pypeflow.simple_pwatcher_bridge - ERROR - ready: set([])
submitted: set([])
```
```py
Traceback (most recent call last):
  File "/home/bac/software/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 484, in main
    main1(argv[0], args.config, args.logger)
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 145, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 204, in run
    wf.refreshTargets([rdb_build_done])
  File "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 206, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 273, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
make: *** [run] Error 1
```

**Comment by pb-cdunn** [comment]
Look for stderr for that task, maybe in `0-rawreads/pwatcher.dir/stderr`.

**Comment by zhanghaoipp** [comment]
Dear pb-cdunn,

Thank you for your reply!

the stderr file is below:

+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads --heartbeat-file=/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/mypwatcher/heartbeats/heartbeat-Pe1cb08cea30388 --exit-file=/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/mypwatcher/exits/exit-Pe1cb08cea30388 --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads', exit_file='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/mypwatcher/exits/exit-Pe1cb08cea30388', heartbeat_file='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/mypwatcher/heartbeats/heartbeat-Pe1cb08cea30388', rate=10.0)

cwd:'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads'
hostname=bac-IPP
heartbeat_fn='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/mypwatcher/heartbeats/heartbeat-Pe1cb08cea30388'
exit_fn='/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/mypwatcher/exits/exit-Pe1cb08cea30388'
sleep_s=10.0
before setpgid: pid=9171 pgid=9150
 after setpgid: pid=9171 pgid=9171
In cwd: /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads, Blocking call: '/bin/bash run.sh'
cd /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads
+ cd /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads
bash task.sh
+ bash task.sh
2016-11-28 03:19:59,934 - root - DEBUG - Running "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/task.json"
2016-11-28 03:19:59,936 - root - DEBUG - Checking existence of '/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/task.json' with timeout=60
2016-11-28 03:19:59,936 - root - DEBUG - Loading JSON from '/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/task.json'
2016-11-28 03:19:59,937 - root - DEBUG - {u'inputs': {u'input_fofn': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw-fofn-abs/input.fofn'},
 u'outputs': {u'length_cutoff': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/length_cutoff',
              u'raw_reads_db': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw_reads.db',
              u'rdb_build_done': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/rdb_build_done',
              u'run_jobs': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/run_jobs.sh'},
 u'parameters': {u'config': {u'avoid_text_file_busy': True,
                             u'cns_concurrent_jobs': 8,
                             u'dazcon': False,
                             u'dust': False,
                             u'falcon_sense_greedy': False,
                             u'falcon_sense_option': u'--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 1000 --n_core 6',
                             u'falcon_sense_skip_contained': False,
                             u'fc_ovlp_to_graph_option': u' --min_len 2000',
                             u'genome_size': 40000000,
                             u'input_fofn': u'input.fofn',
                             u'input_type': u'raw',
                             u'install_prefix': u'/usr',
                             u'job_queue': u'default',
                             u'job_type': u'local',
                             u'length_cutoff': -1,
                             u'length_cutoff_pr': 2000,
                             u'overlap_filtering_setting': u'--max_diff 100 --max_cov 100 --min_cov 4 --bestn 10 --n_core 24',
                             u'ovlp_DBsplit_option': u'-x500 -s100',
                             u'ovlp_HPCdaligner_option': u'-v -B24 -t16 -h60 -e.96 -l500 -s1000',
                             u'ovlp_concurrent_jobs': 32,
                             u'pa_DBdust_option': u'-w128 -t2.5 -m20',
                             u'pa_DBsplit_option': u'-x500 -s100',
                             u'pa_HPCdaligner_option': u'-v -B24 -t8 -e.70 -l1000 -s1000',
                             u'pa_concurrent_jobs': 32,
                             u'pa_dazcon_option': u'-j 4 -x -l 500',
                             u'pwatcher_directory': u'mypwatcher',
                             u'pwatcher_type': u'fs_based',
                             u'seed_coverage': 70.0,
                             u'sge_option': u'-pe smp 8 -q production',
                             u'sge_option_cns': u'-pe smp 8 -q production',
                             u'sge_option_da': u'-pe smp 8 -q production',
                             u'sge_option_fc': u'-pe smp 24 -q production',
                             u'sge_option_la': u'-pe smp 2 -q production',
                             u'sge_option_pda': u'-pe smp 8 -q production',
                             u'sge_option_pla': u'-pe smp 2 -q production',
                             u'skip_checks': False,
                             u'stop_all_jobs_on_failure': False,
                             u'target': u'assembly',
                             u'use_tmpdir': False},
                 u'config_fn': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/fc_run.cfg',
                 u'sge_option': u'-pe smp 8 -q production',
                 u'work_dir': u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads'},
 u'python_function': u'falcon_kit.pype_tasks.task_build_rdb'}
2016-11-28 03:19:59,937 - root - DEBUG - Checking existence of u'/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw-fofn-abs/input.fofn' with timeout=60
2016-11-28 03:19:59,958 - pypeflow.do_support - INFO - !/bin/bash -vex /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/prepare_rdb.sh
#!/bin/bash
set -vex
+ set -vex
set -o pipefail
+ set -o pipefail
#fc_fasta2fasta < /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw-fofn-abs/input.fofn >| fc.fofn
while read fn; do  cat  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/raw-fofn-abs/input.fofn
+ read fn
+ cat /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/data/1_subreads.fasta
+ fasta2DB -v raw_reads -i1_subreads.fasta
Adding '1_subreads.fasta.fasta' ...
+ read fn
+ cat /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/data/2_subreads.fasta
+ fasta2DB -v raw_reads -i2_subreads.fasta
Adding '2_subreads.fasta.fasta' ...
+ read fn
+ cat /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/data/3_subreads.fasta
+ fasta2DB -v raw_reads -i3_subreads.fasta
Adding '3_subreads.fasta.fasta' ...
+ read fn
#cat fc.fofn | xargs rm -f
DBsplit -x500 -s100 raw_reads
+ DBsplit -x500 -s100 raw_reads
#DBdust -w128 -t2.5 -m20 raw_reads
LB=$(cat raw_reads.db | LD_LIBRARY_PATH= awk '$1 == "blocks" {print $3}')
cat raw_reads.db | LD_LIBRARY_PATH= awk '$1 == "blocks" {print $3}'
++ cat raw_reads.db
++ LD_LIBRARY_PATH=
++ awk '$1 == "blocks" {print $3}'
+ LB=23
rm -f run_jobs.sh
+ rm -f run_jobs.sh
CUTOFF=$(python2.7 -m falcon_kit.mains.calc_cutoff --coverage 70.0 40000000 <(DBstats -b1 raw_reads))
python2.7 -m falcon_kit.mains.calc_cutoff --coverage 70.0 40000000 <(DBstats -b1 raw_reads)
++ python2.7 -m falcon_kit.mains.calc_cutoff --coverage 70.0 40000000 /dev/fd/63
DBstats -b1 raw_reads
+++ DBstats -b1 raw_reads
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/mains/calc_cutoff.py", line 36, in <module>
    main(sys.argv)
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/mains/calc_cutoff.py", line 32, in main
    cutoff = f.calc_cutoff(target, stats)
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/functional.py", line 273, in calc_cutoff
    return calc_cutoff_from_reverse_sorted_readlength_counts(rl_counts, target)
  File "/home/bac/software/FALCON-integrate/FALCON/falcon_kit/functional.py", line 230, in calc_cutoff_from_reverse_sorted_readlength_counts
    assert target <= total, 'Not enough genome coverage (target={} < actual={})'.format(target, total)
AssertionError: Not enough genome coverage (target=2800000000 < actual=2236605456)
+ CUTOFF=
2016-11-28 03:20:26,387 - root - CRITICAL - Error in /home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 149, in <module>
    main()
  File "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 141, in main
    run(**vars(parsed_args))
  File "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 129, in run
    do_support.run_bash(script_fn)
  File "/home/bac/software/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /home/bac/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads/prepare_rdb.sh'

real	0m26.564s
user	0m22.864s
sys	0m4.548s
 returned: 256

**Comment by pb-cdunn** [comment]
> AssertionError: Not enough genome coverage (target=2800000000 < actual=2236605456)

You need to alter genome_size and/or coverage.

**Comment by zhanghaoipp** [comment]
Dear pb-cdunn,

Thank you! I have another question:

I checked raw reads with DBstats, but I do not understand clearly, it said "Statistics for all reads of length 500 bases or more, 2,236,605,456 base pairs   out of   3,144,334,921  ( 71.1%)" My input are the subreads filtered by smrt pipline, now all reads are longer than 500 bp. Why they are filtered again in falcon???

bac@bac-IPP:~/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads$ ../../../../DAZZ_DB/DBstats raw_reads.db 

Statistics for all reads of length 500 bases or more

        198,736 reads        out of         330,720  ( 60.1%)
  2,236,605,456 base pairs   out of   3,144,334,921  ( 71.1%)

         11,254 average read length
          6,661 standard deviation

  Base composition: 0.268(A) 0.210(C) 0.239(G) 0.283(T)

  Distribution of Read Lengths (Bin size = 1,000)

        Bin:      Count  % Reads  % Bases     Average
     70,000:          1      0.0      0.0       70753
     69,000:          2      0.0      0.0       70070
     68,000:          0      0.0      0.0       70070
     67,000:          1      0.0      0.0       69529
     66,000:          0      0.0      0.0       69529
     65,000:          2      0.0      0.0       68265
     64,000:          0      0.0      0.0       68265
     63,000:          1      0.0      0.0       67600
     62,000:          0      0.0      0.0       67600
     61,000:          0      0.0      0.0       67600
     60,000:          0      0.0      0.0       67600
     59,000:          2      0.0      0.0       65736
     58,000:          2      0.0      0.0       64383
     57,000:          5      0.0      0.0       62236
     56,000:          4      0.0      0.1       61091
     55,000:          2      0.0      0.1       60588
     54,000:         11      0.0      0.1       58564
     53,000:          9      0.0      0.1       57507
     52,000:         10      0.0      0.1       56551
     51,000:         10      0.0      0.2       55742
     50,000:         10      0.0      0.2       55014
     49,000:         19      0.0      0.2       53861
     48,000:         21      0.1      0.3       52844
     47,000:         35      0.1      0.3       51566
     46,000:         22      0.1      0.4       50917
     45,000:         31      0.1      0.4       50067
     44,000:         31      0.1      0.5       49323
     43,000:         42      0.1      0.6       48428
     42,000:         46      0.2      0.7       47566
     41,000:         51      0.2      0.8       46732
     40,000:         62      0.2      0.9       45844
     39,000:         83      0.3      1.0       44818
     38,000:        112      0.3      1.2       43686
     37,000:        112      0.4      1.4       42749
     36,000:        139      0.4      1.6       41760
     35,000:        169      0.5      1.9       40748
     34,000:        211      0.6      2.2       39702
     33,000:        249      0.8      2.6       38670
     32,000:        290      0.9      3.0       37668
     31,000:        374      1.1      3.6       36604
     30,000:        447      1.3      4.2       35559
     29,000:        505      1.6      4.8       34576
     28,000:        624      1.9      5.6       33561
     27,000:        748      2.3      6.5       32550
     26,000:        946      2.7      7.7       31496
     25,000:      1,205      3.3      9.0       30407
     24,000:      1,412      4.1     10.6       29370
     23,000:      1,864      5.0     12.5       28262
     22,000:      2,172      6.1     14.7       27224
     21,000:      2,822      7.5     17.4       26137
     20,000:      3,412      9.2     20.6       25084
     19,000:      4,261     11.4     24.3       24028
     18,000:      5,391     14.1     28.7       22959
     17,000:      6,494     17.3     33.8       21927
     16,000:      7,887     21.3     39.6       20914
     15,000:      9,090     25.9     45.9       19955
     14,000:     10,216     31.0     52.5       19050
     13,000:     11,033     36.6     59.2       18207
     12,000:     11,017     42.1     65.3       17455
     11,000:     10,706     47.5     70.8       16780
     10,000:     10,310     52.7     75.7       16162
      9,000:     10,819     58.1     80.3       15538
      8,000:     11,369     63.9     84.6       14907
      7,000:     11,719     69.8     88.5       14280
      6,000:     12,059     75.8     92.0       13658
      5,000:     11,637     81.7     94.9       13074
      4,000:     10,892     87.2     97.1       12535
      3,000:      9,528     92.0     98.6       12065
      2,000:      8,506     96.2     99.5       11640
      1,000:      5,823     99.2     99.9       11341
          0:      1,651    100.0    100.0       11254

**Comment by pb-jchin** [comment]
It is a good idea to pick only the longest subread of each ZMW for assembly.  Shorter subreads are not used for assembly in this case.

**Comment by zhanghaoipp** [comment]
Dear Jason,

Thank you! I set the genome size=40000000, seed_coverage=50 and length_cutoff=-1, let it auto-caculate the cutoff. However, it seems this time all subreads of each ZMW were selected in raw_reads.db. I do not know why?

bac@bac-IPP:~/software/FALCON-integrate/FALCON-examples/run/Ft_JL22/0-rawreads$ ../../../../DAZZ_DB/DBstats raw_reads.db 

Statistics for all wells of length 500 bases or more

        330,720 reads        out of         330,720  (100.0%)
  3,144,334,921 base pairs   out of   3,144,334,921  (100.0%)

          9,507 average read length
          6,458 standard deviation

  Base composition: 0.268(A) 0.210(C) 0.239(G) 0.283(T)

  Distribution of Read Lengths (Bin size = 1,000)

        Bin:      Count  % Reads  % Bases     Average
     70,000:          1      0.0      0.0       70753
     69,000:          2      0.0      0.0       70070
     68,000:          0      0.0      0.0       70070
     67,000:          1      0.0      0.0       69529
     66,000:          0      0.0      0.0       69529
     65,000:          2      0.0      0.0       68265
     64,000:          0      0.0      0.0       68265
     63,000:          1      0.0      0.0       67600
     62,000:          0      0.0      0.0       67600
     61,000:          0      0.0      0.0       67600
     60,000:          0      0.0      0.0       67600
     59,000:          2      0.0      0.0       65736
     58,000:          2      0.0      0.0       64383
     57,000:          5      0.0      0.0       62236
     56,000:          4      0.0      0.0       61091
     55,000:          2      0.0      0.0       60588
     54,000:         11      0.0      0.1       58564
     53,000:          9      0.0      0.1       57507
     52,000:         10      0.0      0.1       56551
     51,000:         10      0.0      0.1       55742
     50,000:         10      0.0      0.1       55014
     49,000:         19      0.0      0.2       53861
     48,000:         21      0.0      0.2       52844
     47,000:         35      0.0      0.2       51566
     46,000:         22      0.1      0.3       50917
     45,000:         31      0.1      0.3       50067
     44,000:         31      0.1      0.4       49323
     43,000:         42      0.1      0.4       48428
     42,000:         46      0.1      0.5       47566
     41,000:         51      0.1      0.5       46732
     40,000:         62      0.1      0.6       45844
     39,000:         83      0.2      0.7       44818
     38,000:        112      0.2      0.9       43686
     37,000:        112      0.2      1.0       42749
     36,000:        139      0.3      1.2       41760
     35,000:        169      0.3      1.4       40748
     34,000:        212      0.4      1.6       39698
     33,000:        249      0.5      1.9       38667
     32,000:        290      0.5      2.2       37666
     31,000:        376      0.7      2.5       36598
     30,000:        448      0.8      3.0       35553
     29,000:        506      0.9      3.4       34571
     28,000:        632      1.1      4.0       33547
     27,000:        765      1.4      4.7       32522
     26,000:        967      1.7      5.5       31460
     25,000:      1,248      2.0      6.5       30354
     24,000:      1,481      2.5      7.7       29298
     23,000:      1,975      3.1      9.1       28170
     22,000:      2,360      3.8     10.8       27100
     21,000:      3,096      4.7     12.9       25989
     20,000:      3,824      5.9     15.4       24907
     19,000:      4,846      7.4     18.4       23826
     18,000:      6,385      9.3     22.2       22713
     17,000:      7,987     11.7     26.6       21633
     16,000:     10,306     14.8     32.0       20549
     15,000:     12,434     18.6     38.1       19524
     14,000:     14,493     23.0     44.8       18563
     13,000:     16,605     28.0     51.9       17652
     12,000:     17,273     33.2     58.8       16841
     11,000:     17,085     38.4     65.1       16122
     10,000:     16,359     43.3     70.5       15481
      9,000:     16,754     48.4     75.6       14854
      8,000:     17,587     53.7     80.3       14224
      7,000:     18,190     59.2     84.7       13599
      6,000:     18,769     64.9     88.6       12978
      5,000:     18,711     70.5     91.8       12378
      4,000:     18,668     76.2     94.5       11794
      3,000:     18,428     81.7     96.6       11229
      2,000:     24,325     89.1     98.4       10501
      1,000:     28,024     97.6     99.8        9724
          0:      8,015    100.0    100.0        9507

**Comment by zhanghaoipp** [comment]
Sorry, I think it is because I add -a in pa_DBsplit_option.

**Comment by pb-cdunn** [comment]
Exactly.

It's interesting that your Cytosine base composition is so low. Anyway, it seems that you've got it working now. Good luck.

**Comment by ParadoxYm** [comment]
您好 我遇到了和您一样的问题Task Node(0-rawreads) failed with exit-code=256
请问您是怎么解决的

**Comment by ParadoxYm** [comment]
hey I have the same problem just like you
Task Node(0-rawreads) failed with exit-code=256
Can I ask you how did you solve it?
what did you do?
thank you

**Comment by kaikaixinxi** [comment]
i have the same problem ，what did you do?
