### ISSUE TITLE
FALCON stability issues

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON#499]
**To whom it may concern,**

**I am writing to inquire about an issue that I have been observing while running fc_get_read_ctg_map to extract the reads, preads and contigs that are associated with each other. I have been able to successfully install as previously described in issue #494.** 

**running fc_get_read_ctg_map sometimes gives me this error**
```py
WARNING:pypeflow.simple_pwatcher_bridge:In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
ERROR:pypeflow.simple_pwatcher_bridge:Task Node(2-asm-falcon/read_maps/get_ctg_read_map) failed with exit-code=256
ERROR:pypeflow.simple_pwatcher_bridge:Some tasks are recently_done but not satisfied: set([Node(2-asm-falcon/read_maps/get_ctg_read_map)])
ERROR:pypeflow.simple_pwatcher_bridge:ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/fc_env/bin/fc_get_read_ctg_map", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_get_read_ctg_map')()
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/get_read_ctg_map.py", line 134, in main
    get_read_ctg_map(rawread_dir=rawread_dir, pread_dir=pread_dir, asm_dir=asm_dir)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/FALCON/falcon_kit/mains/get_read_ctg_map.py", line 116, in get_read_ctg_map
    wf.refreshTargets() # block
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 210, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 277, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(2-asm-falcon/read_maps/get_ctg_read_map)])
```
**Upon repeated running of the same command, I am provided with this different warning.**
```
WARNING:pypeflow.simple_pwatcher_bridge:In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
```
but I see successful completion and creation of the directories `2-asm-falcon/read_maps/dump_pread_ids` `2-asm-falcon/read_masps/dump_rawread_ids and 2-asm-falcon/read_maps/get_ctg_read_map` with the associated outputs.

I was wondering if there is a method to make the run go smoothly as possible or is it more of trial and error?

**Best,**
**Jin**

**Comment by pb-cdunn** [comment]
To see the actual error, view `2-asm-falcon/read_maps/get_ctg_read_map/pwatcher.dir/stderr`

**Comment by sjin09** [comment]
**When I observe the above errors and check the**

**2-asm-falcon/read_maps/dump_pread_ids/pwatcher.dir/stderr**

+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids --heartbeat-file=/mnt/ruby/PacBio/Project/AK1/ASIAN_GEN
Namespace(command=['/bin/bash', 'run.sh'], directory='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids', exit_file='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/S

cwd:'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids'
hostname=denovo05
heartbeat_fn='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/mypwatcher/heartbeats/heartbeat-P59e02e48e095c2'
exit_fn='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/mypwatcher/exits/exit-P59e02e48e095c2'
sleep_s=10.0
before setpgid: pid=31952 pgid=31944
 after setpgid: pid=31952 pgid=31952
In cwd: /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids, Blocking call: '/bin/bash run.sh'
cd /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids
+ cd /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids
bash task.sh
+ bash task.sh
2016-12-02 09:07:27,831 - root - DEBUG - Running "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.ana
2016-12-02 09:07:27,835 - root - DEBUG - Checking existence of '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids/task.json' with timeout=60
2016-12-02 09:07:27,835 - root - DEBUG - Loading JSON from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids/task.json'
2016-12-02 09:07:27,837 - root - DEBUG - {u'inputs': {u'pread_db': u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/1-preads_ovl/preads.db'},
 u'outputs': {u'pread_id_file': u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids/pread_ids'},
 u'parameters': {},
 u'python_function': u'falcon_kit.mains.get_read_ctg_map.dump_pread_ids'}
2016-12-02 09:07:27,837 - root - DEBUG - Checking existence of u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/1-preads_ovl/preads.db' with timeout=60
2016-12-02 09:07:30,606 - root - DEBUG - Checking existence of u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids/pread_ids' with timeout=60

real    0m3.417s
user    0m1.307s
sys     0m1.386s
touch /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids/run.sh.done
+ touch /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_pread_ids/run.sh.done
 returned: 0

**and 2-asm-falcon/read_maps/dump_rawread_ids/pwatcher.dir/stderr**

+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids --heartbeat-file=/mnt/ruby/PacBio/Project/AK1/ASIAN_G
Namespace(command=['/bin/bash', 'run.sh'], directory='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids', exit_file='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME

cwd:'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids'
hostname=denovo05
heartbeat_fn='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/mypwatcher/heartbeats/heartbeat-P6bbda7757b892e'
exit_fn='/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/mypwatcher/exits/exit-P6bbda7757b892e'
sleep_s=10.0
before setpgid: pid=31949 pgid=31944
 after setpgid: pid=31949 pgid=31949
In cwd: /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids, Blocking call: '/bin/bash run.sh'
cd /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids
+ cd /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids
bash task.sh
+ bash task.sh
2016-12-02 09:07:27,779 - root - DEBUG - Running "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/19.tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.ana
2016-12-02 09:07:27,783 - root - DEBUG - Checking existence of '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids/task.json' with timeout=60
2016-12-02 09:07:27,783 - root - DEBUG - Loading JSON from '/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids/task.json'
2016-12-02 09:07:27,785 - root - DEBUG - {u'inputs': {u'rawread_db': u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/0-rawreads/raw_reads.db'},
 u'outputs': {u'rawread_id_file': u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids/rawread_ids'},
 u'parameters': {},
 u'python_function': u'falcon_kit.mains.get_read_ctg_map.dump_rawread_ids'}
2016-12-02 09:07:27,785 - root - DEBUG - Checking existence of u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/0-rawreads/raw_reads.db' with timeout=60
2016-12-02 09:07:30,456 - root - DEBUG - Checking existence of u'/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids/rawread_ids' with timeout=60

real    0m3.234s
user    0m1.575s
sys     0m1.250s
touch /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids/run.sh.done
+ touch /mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/08.chrXY/18.analysis/14.falcon/2-asm-falcon/read_maps/dump_rawread_ids/run.sh.done
 returned: 0

**I didn't see any noticeable errors, so I didn't initially post it.**

**Comment by pb-cdunn** [comment]
> Exception: Some tasks are recently_done but not satisfied: set([Node(2-asm-falcon/read_maps/get_ctg_read_map)])

To see the actual error, view `2-asm-falcon/read_maps/get_ctg_read_map/pwatcher.dir/stderr`
