### ISSUE TITLE
EXIT 256 back again

### ISSUE THREAD

**Issue by hodgett** [PacificBiosciences/FALCON#503]
I am still trying to get FALCON to run on our cluster, and have hit the dreaded EXIT 256 again using our test data set AND having re-installed FALCON from scratch with the latest codebase. Is it possible to get more information on what it means, why it's occurring, what the attempted fix was last time? Perhaps someone could help interpret what is going in this snippet from stderr? This is not making it past the second step of the process (0-rawreads).
```py
2016-12-22 15:21:36,604 - root - CRITICAL - Error in /lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/work2/bob_lab/matt_FalconTst/0-rawreads/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/pkg/suse12/software/python/2.7.11-foss-2016a/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/pkg/suse12/software/python/2.7.11-foss-2016a/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/lustre/work-lustre/bob_team/All_Programs/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /work2/bob_lab/matt_FalconTst/0-rawreads/prepare_rdb.sh'
```

**Comment by hodgett** [comment]
Well, it looks like this is a 'file not found' in disguise. I have solved the immediate problem. On to the next!

**Comment by pb-cdunn** [comment]
What files was not found? And how did you learn that?
