### ISSUE TITLE
Problem on the 0-rawreads process：

### ISSUE THREAD

**Issue by gucascau** [PacificBiosciences/FALCON#504]
I ran FALCON to assemble a 700Mb genome using 60X raw pacbio reads. In order to avoid the duplicate error, I installed the latest DALIGNER in FALCON. However, my assembly always got stuck at the first rawreads process. There are 24 tasks failed, and 45 tasks unfinished. Then I checked the 
pwatcher.dir/stderr files with the following information:

raw_reads.56.raw_reads.24.N1: Duplicate overlap (1748840 vs 700961)
.....
 raw_reads.9.raw_reads.56.N2: 104,472 all OK
  raw_reads.9.raw_reads.56.N3: 110,434 all OK
2016-12-25 16:46:26,524 - root - DEBUG - CD: '/home/xinw/project/Brain_coral_new/Pacbio/denovo_assemble/assemble_22_Dec/0-rawreads/job_003c' -> '/home/xinw/project/Brain_coral_new/Pacbio/denovo_assemble/assemble_22_Dec/0-rawreads/job_003c'
2016-12-25 16:46:26,524 - root - DEBUG - CD: '/home/xinw/project/Brain_coral_new/Pacbio/denovo_assemble/assemble_22_Dec/0-rawreads/job_003c' -> '/home/xinw/project/Brain_coral_new/Pacbio/denovo_assemble/assemble_22_Dec/0-rawreads/job_003c'
2016-12-25 16:46:26,524 - root - CRITICAL - Error in /home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/home/xinw/project/Brain_coral_new/Pacbio/denovo_assemble/assemble_22_Dec/0-rawreads/job_003c/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/home/xinw/software/FALCON/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /home/xinw/project/Brain_coral_new/Pacbio/denovo_assemble/assemble_22_Dec/0-rawreads/job_003c/rj_003c.sh'

real   	183m14.040s
user   	650m58.448s
sys    	9m49.484s
 returned: 256

I am not sure it is the problem of "duplicate overlap". In the config file, i used the skip_checks = true, and update DALIGNER to the latest one, but it is still coming out these error.

SO anyone know what's the problem? how can i solve this? 
Thanks && Merry xmas

**Comment by pb-jchin** [comment]
first, check if your `rj_003c.sh` contains the `LACheck` command, if so, either you did not really run from the update environment or the script is not updated.

**Comment by gucascau** [comment]
Yes, I could still find LACheck. I downloaded and installed the FALCON-instegrate based on the easy way: 
export GIT_SYM_CACHE_DIR=~/.git-sym-cache # to speed things up
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate 
###
Here I downloaded the latest version of DALIGNER and executed the following commands
###
git checkout master  # or whatever version you want
make init
source env.sh
make config-edit-user
make -j all
make test  # to run a simple one

I don't think it would be the update environment. Do I also need to update the FALCON? Thanks for the quick respond.

**Comment by lamz138138** [comment]
Hi, I have the same problem, did you solve it? By the way, I didn't do "make config-edit-user" as it would output follow error and I am running with virtualenv.
```
mkdir myVirtualenv
python virtualenv/virtualenv.py -p python2.7 myVirtualenv
unset PYTHONPATH
source myVirtualenv/bin/activate
export GIT_SYM_CACHE_DIR=~/.git-sym-cache
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master
make init
source env.sh
#make config-edit-user
make -j all
make test
```

**Comment by lamz138138** [comment]
I had run the pipeline successfully by adding "skip_check = ture" in *cfg as stated in https://github.com/PacificBiosciences/FALCON/issues/501.
