### ISSUE TITLE
[ERROR]Task Fred{'URL': 'task://localhost/report_pre_assembly'} failed with exit-code=35072 

### ISSUE THREAD

**Issue by simona1** [PacificBiosciences/FALCON#508]
Could you please advise how to deal with this error?
Thanks very much in advance!
Here is the step where it occurs:
```
[INFO]Queued 'task://localhost/report_pre_assembly' ...
[INFO]tick: 4, #updatedTasks: 1, sleep_time=0.100000
[INFO]tick: 8, #updatedTasks: 1, sleep_time=0.500000
[INFO]tick: 16, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 32, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 64, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 128, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 256, #updatedTasks: 1, sleep_time=1.000000
[ERROR]Task Fred{'URL': 'task://localhost/report_pre_assembly'} failed with exit-code=35072
[INFO]Failure ('fail'). Joining 'task://localhost/report_pre_assembly'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/apps/gcc/5.2.0/falcon/20161027/pypeFLOW/pypeflow/controller.py:537: UserWarning:
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "/apps/gcc/5.2.0/falcon/20161027/fc_env/bin/fc_run.py", line 7, in <module>
    execfile(__file__)
  File "/apps/gcc/5.2.0/falcon/20161027/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/apps/gcc/5.2.0/falcon/20161027/FALCON/falcon_kit/mains/run1.py", line 662, in main
    main1(argv[0], args.config, args.logger)
  File "/apps/gcc/5.2.0/falcon/20161027/FALCON/falcon_kit/mains/run1.py", line 423, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/apps/gcc/5.2.0/falcon/20161027/FALCON/falcon_kit/mains/run1.py", line 531, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/apps/gcc/5.2.0/falcon/20161027/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/apps/gcc/5.2.0/falcon/20161027/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/apps/gcc/5.2.0/falcon/20161027/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

**Comment by pb-cdunn** [comment]
[ERROR]Task Fred{'URL': 'task://localhost/report_pre_assembly'} failed with exit-code=35072

Look in the report_pre_assembly directory. Look for `pwatcher.dir/stderr` to see how that task failed. You can re-run that task from the command-line to debug it. You might have an integration problem, or bad inputs which produced no useful output.
