### ISSUE TITLE
merge-scatter fails: AssertionError

### ISSUE THREAD

**Issue by hodgett** [PacificBiosciences/FALCON#522]
Having got past the daligner-scatter step we have a new error. I have tried running run.sh but get the same error. Any clues?

```
[snip from output]
                             u'use_tmpdir': True},
                 u'db_prefix': u'raw_reads'},
 u'python_function': u'falcon_kit.pype_tasks.task_merge_scatter'}
2017-02-09 14:54:36,224 - root - DEBUG - CD: '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter' <- '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter'
2017-02-09 14:54:36,225 - root - DEBUG - Checking existence of u'/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/run_jobs.sh' with timeout=60
2017-02-09 14:54:36,225 - root - DEBUG - Checking existence of u'/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/raw-gather/gathered_las.txt' with timeout=60
2017-02-09 14:54:36,250 - root - DEBUG - CD: '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter' <- '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter'
2017-02-09 14:54:37,102 - root - DEBUG - CD: '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter' -> '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter'
2017-02-09 14:54:37,102 - root - DEBUG - CD: '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter' -> '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter'
2017-02-09 14:54:37,103 - root - CRITICAL - Error in /pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/lustre/work-lustre/b/Falcon_Test_20170202_A/0-rawreads/merge-scatter/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/pkg/suse12/software/python/2.7.11-foss-2016a/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/pkg/suse12/software/python/2.7.11-foss-2016a/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 122, in run_python_func
    func(self=self)
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/FALCON/falcon_kit/pype_tasks.py", line 293, in task_merge_scatter
    for p_id, merge_script, merged_las_fn in merge_scripts:
  File "/pkg/suse12/software2/ctcb/FALCON/1.8.6/FALCON-integrate/FALCON/falcon_kit/bash.py", line 310, in scripts_merge
    assert las_fn == os.path.basename(las_files[0])
AssertionError
```

**Comment by feixue1039** [comment]
Hello,

Have you already figure out how to solve this error? I have encountered the same error and don't know why.

**Comment by pb-jchin** [comment]
check https://github.com/PacificBiosciences/FALCON/pull/510

**Comment by feixue1039** [comment]
I checked #510 . Problem solved. Thank you very much.
BTW, I removed the ‘＃’ from the newly added line 310 and 311.
