### ISSUE TITLE
No such file or directory:0-rawreads/daligner-scatter/scattered.json

### ISSUE THREAD

**Issue by hanxue1994** [PacificBiosciences/FALCON#524]
I installed falcon following the manual , and then cd to the Falcon-example directory to test. I successfully tested the synth0 by typing "make" in the synth0 directory and get  `./check.py  shifted by 3269 (rc)` , but when I did the same thing at the directoty "ecoli", it returned error messages `IOError: [Errno 2] No such file or directory: '/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/daligner-scatter/scattered.json'`
The same thing happened when I use my own data to run fc_run.py, and I don't know how to solve this problem. By the way ,I do feel the manual is rather difficult to read and understand for a new user,is there any other information for a new user?

And the error messages in detail :
```
pwatcher.fs_based - ERROR - In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSge(MetaJob(job=Job(jobid='P1a59307fb51dd9', cmd='/bin/bash run.sh', rundir='/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 530, in cmd_run
    state.submit_background(bjob)
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 298, in submit
    system(sge_cmd, checked=True) # TODO: Capture q-jobid
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 549, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 32512 <- 'qsub -N P1a59307fb51dd9 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /data4/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P1a59307fb51dd9.bash'
2017-02-10 10:39:24,770 - pypeflow.simple_pwatcher_bridge - ERROR - Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])
2017-02-10 10:39:24,770 - pypeflow.simple_pwatcher_bridge - WARNING - Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
2017-02-10 10:39:24,770 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
2017-02-10 10:39:24,875 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 2, graph: 2
2017-02-10 10:39:24,875 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2017-02-10 10:39:24,877 - pwatcher.fs_based - INFO - starting job Job(jobid='P1a59307fb51dd9', cmd='/bin/bash run.sh', rundir='/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'SGE'})
2017-02-10 10:39:24,878 - pwatcher.fs_based - INFO - !qsub -N P1a59307fb51dd9 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /data4/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P1a59307fb51dd9.bash
sh: qsub: command not found
2017-02-10 10:39:24,884 - pwatcher.fs_based - ERROR - In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSge(MetaJob(job=Job(jobid='P1a59307fb51dd9', cmd='/bin/bash run.sh', rundir='/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 530, in cmd_run
    state.submit_background(bjob)
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 298, in submit
    system(sge_cmd, checked=True) # TODO: Capture q-jobid
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 549, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 32512 <- 'qsub -N P1a59307fb51dd9 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /data4/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P1a59307fb51dd9.bash'
2017-02-10 10:39:24,884 - pypeflow.simple_pwatcher_bridge - ERROR - Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])
2017-02-10 10:39:24,885 - pypeflow.simple_pwatcher_bridge - WARNING - Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
2017-02-10 10:39:24,885 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
2017-02-10 10:39:24,989 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 3, graph: 3
2017-02-10 10:39:24,989 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2017-02-10 10:39:24,991 - pwatcher.fs_based - INFO - starting job Job(jobid='P1a59307fb51dd9', cmd='/bin/bash run.sh', rundir='/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'SGE'})
2017-02-10 10:39:24,992 - pwatcher.fs_based - INFO - !qsub -N P1a59307fb51dd9 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /data4/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P1a59307fb51dd9.bash
sh: qsub: command not found
2017-02-10 10:39:24,998 - pwatcher.fs_based - ERROR - In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSge(MetaJob(job=Job(jobid='P1a59307fb51dd9', cmd='/bin/bash run.sh', rundir='/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 530, in cmd_run
    state.submit_background(bjob)
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 298, in submit
    system(sge_cmd, checked=True) # TODO: Capture q-jobid
  File "/data4/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 549, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 32512 <- 'qsub -N P1a59307fb51dd9 -q default -pe smp 8 -V -cwd -o stdout -e stderr -S /bin/bash /data4/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P1a59307fb51dd9.bash'
2017-02-10 10:39:24,999 - pypeflow.simple_pwatcher_bridge - ERROR - Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])
2017-02-10 10:39:24,999 - pypeflow.simple_pwatcher_bridge - WARNING - Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
2017-02-10 10:39:24,999 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
Traceback (most recent call last):
  File "/data4/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/data4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/data4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/data4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 219, in run
    daligner_tasks, daligner_out = create_daligner_tasks(rawread_dir, scattered_plf)
  File "/data4/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 22, in create_daligner_tasks
    content = json.loads(open(scatter_fn).read()) # array of descriptions
IOError: [Errno 2] No such file or directory: '/data4/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/daligner-scatter/scattered.json'
make: *** [run] Error 1
```

**Comment by pb-cdunn** [comment]
> sh: qsub: command not found

You need to submit jobs in a different way. The synth5k directory is configured to run on your local machine, which is why it works fine. You can copy/paste from there to set up a local run, or you can ask a sysadmin what is available for job-submission, and configure "pwatcher" to use that.
