### ISSUE TITLE
LAmerge: Did not write all records to preads.13 (85717)

### ISSUE THREAD

**Issue by hanxue1994** [PacificBiosciences/FALCON#531]
There came the error reports of some m_* tasks in 1-preads_ovl directory. What should I do to restart the job?

**Comment by ParadoxYm** [comment]
hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json
请问 你是怎么解决的

**Comment by hanxue1994** [comment]
我不太记得了，你可以把你的cfg文件内容给我看一下，说不定就想起来了
发自网易邮箱大师
在2017年04月12日 20:38，ParadoxYm 写道： hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json
请问 你是怎么解决的

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PacificBiosciences/FALCON","title":"PacificBiosciences/FALCON","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PacificBiosciences/FALCON"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ParadoxYm in #531: hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json\r\n请问 你是怎么解决的"}],"action":{"name":"View Issue","url":"https://github.com/PacificBiosciences/FALCON/issues/531#issuecomment-293560839"}}}

**Comment by ParadoxYm** [comment]
谢谢 这是
fc_run.cfg
[General]
#job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000


jobqueue = production
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24



这是部分的运行结果
2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - ERROR - Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])
2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - WARNING - Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
Traceback (most recent call last):
  File "/Users/paradox/Documents/asc/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 462, in main
    main1(argv[0], args.config, args.logger)
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 219, in run
    daligner_tasks, daligner_out = create_daligner_tasks(rawread_dir, scattered_plf)
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 22, in create_daligner_tasks
    content = json.loads(open(scatter_fn).read()) # array of descriptions
IOError: [Errno 2] No such file or directory: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/daligner-scatter/scattered.json'
make: *** [run-ecoli] Error 1





------------------ 原始邮件 ------------------
发件人: "coldsnow";<notifications@github.com>;
发送时间: 2017年4月12日(星期三) 晚上8:43
收件人: "PacificBiosciences/FALCON"<FALCON@noreply.github.com>;
抄送: "563271877"<563271877@qq.com>; "Comment"<comment@noreply.github.com>;
主题: Re: [PacificBiosciences/FALCON] LAmerge: Did not write all records topreads.13 (85717) (#531)


我不太记得了，你可以把你的cfg文件内容给我看一下，说不定就想起来了
发自网易邮箱大师
在2017年04月12日 20:38，ParadoxYm 写道： hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json
请问 你是怎么解决的

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.








{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PacificBiosciences/FALCON","title":"PacificBiosciences/FALCON","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PacificBiosciences/FALCON"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ParadoxYm in #531: hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json\r\n请问 你是怎么解决的"}],"action":{"name":"View Issue","url":"https://github.com/PacificBiosciences/FALCON/issues/531#issuecomment-293560839"}}}

**Comment by hanxue1994** [comment]
你选择了local之后，应该把sge那些作业选项设置为空
发自网易邮箱大师
在2017年04月13日 12:01，ParadoxYm 写道： 谢谢 这是
fc_run.cfg
[General]
#job_type = local
list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn
input_type = raw
#input_type = preads
The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000
The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000
jobqueue = production
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s
pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
这是部分的运行结果
2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - ERROR - Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])
2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - WARNING - Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
Traceback (most recent call last):
File "/Users/paradox/Documents/asc/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in 
exec(compile(open(file).read(), file, 'exec'))
File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in 
main(sys.argv)
File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 462, in main
main1(argv[0], args.config, args.logger)
File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
input_fofn_plf=input_fofn_plf,
File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 219, in run
daligner_tasks, daligner_out = create_daligner_tasks(rawread_dir, scattered_plf)
File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 22, in create_daligner_tasks
content = json.loads(open(scatter_fn).read()) # array of descriptions
IOError: [Errno 2] No such file or directory: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/daligner-scatter/scattered.json'
make: *** [run-ecoli] Error 1
------------------ 原始邮件 ------------------
发件人: "coldsnow";notifications@github.com;
发送时间: 2017年4月12日(星期三) 晚上8:43
收件人: "PacificBiosciences/FALCON"FALCON@noreply.github.com;
抄送: "563271877"563271877@qq.com; "Comment"comment@noreply.github.com;
主题: Re: [PacificBiosciences/FALCON] LAmerge: Did not write all records topreads.13 (85717) (#531)
我不太记得了，你可以把你的cfg文件内容给我看一下，说不定就想起来了
发自网易邮箱大师
在2017年04月12日 20:38，ParadoxYm 写道： hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json
请问 你是怎么解决的
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PacificBiosciences/FALCON","title":"PacificBiosciences/FALCON","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PacificBiosciences/FALCON"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ParadoxYm in #531: hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json\r\n请问 你是怎么解决的"}],"action":{"name":"View Issue","url":"https://github.com/PacificBiosciences/FALCON/issues/531#issuecomment-293560839"}}}
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PacificBiosciences/FALCON","title":"PacificBiosciences/FALCON","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PacificBiosciences/FALCON"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ParadoxYm in #531: 谢谢 这是\r\nfc_run.cfg\r\n[General]\r\n#job_type = local\r\n\r\n# list of files of the initial bas.h5 files\r\ninput_fofn = input.fofn\r\n#input_fofn = preads.fofn\r\n\r\ninput_type = raw\r\n#input_type = preads\r\n\r\n# The length cutoff used for seed reads used for initial mapping\r\nlength_cutoff = 12000\r\n\r\n# The length cutoff used for seed reads usef for pre-assembly\r\nlength_cutoff_pr = 12000\r\n\r\n\r\njobqueue = production\r\nsge_option_da = -pe smp 8 -q %(jobqueue)s\r\nsge_option_la = -pe smp 2 -q %(jobqueue)s\r\nsge_option_pda = -pe smp 8 -q %(jobqueue)s\r\nsge_option_pla = -pe smp 2 -q %(jobqueue)s\r\nsge_option_fc = -pe smp 24 -q %(jobqueue)s\r\nsge_option_cns = -pe smp 8 -q %(jobqueue)s\r\n\r\npa_concurrent_jobs = 32\r\novlp_concurrent_jobs = 32\r\n\r\npa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000\r\novlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000\r\n\r\npa_DBsplit_option = -x500 -s50\r\novlp_DBsplit_option = -x500 -s50\r\n\r\nfalcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6\r\n\r\noverlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24\r\n\r\n\r\n\r\n这是部分的运行结果\r\n2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - ERROR - Failed to enqueue 1 of 1 jobs: set([Node(0-rawreads/raw-fofn-abs)])\r\n2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - WARNING - Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.\r\n2017-04-13 03:20:34,478 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s\r\nTraceback (most recent call last):\r\n  File \"/Users/paradox/Documents/asc/FALCON-integrate/fc_env/bin/fc_run.py\", line 6, in \u003cmodule\u003e\r\n    exec(compile(open(__file__).read(), __file__, 'exec'))\r\n  File \"/Users/paradox/Documents/asc/FALCON-integrate/FALCON/src/py_scripts/fc_run.py\", line 5, in \u003cmodule\u003e\r\n    main(sys.argv)\r\n  File \"/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py\", line 462, in main\r\n    main1(argv[0], args.config, args.logger)\r\n  File \"/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py\", line 136, in main1\r\n    input_fofn_plf=input_fofn_plf,\r\n  File \"/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py\", line 219, in run\r\n    daligner_tasks, daligner_out = create_daligner_tasks(rawread_dir, scattered_plf)\r\n  File \"/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py\", line 22, in create_daligner_tasks\r\n    content = json.loads(open(scatter_fn).read()) # array of descriptions\r\nIOError: [Errno 2] No such file or directory: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/daligner-scatter/scattered.json'\r\nmake: *** [run-ecoli] Error 1\r\n\r\n\r\n\r\n\r\n\r\n------------------ 原始邮件 ------------------\r\n发件人: \"coldsnow\";\u003cnotifications@github.com\u003e;\r\n发送时间: 2017年4月12日(星期三) 晚上8:43\r\n收件人: \"PacificBiosciences/FALCON\"\u003cFALCON@noreply.github.com\u003e;\r\n抄送: \"563271877\"\u003c563271877@qq.com\u003e; \"Comment\"\u003ccomment@noreply.github.com\u003e;\r\n主题: Re: [PacificBiosciences/FALCON] LAmerge: Did not write all records topreads.13 (85717) (#531)\r\n\r\n\r\n我不太记得了，你可以把你的cfg文件内容给我看一下，说不定就想起来了\r\n发自网易邮箱大师\r\n在2017年04月12日 20:38，ParadoxYm 写道： hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json\r\n请问 你是怎么解决的\r\n\r\n—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/PacificBiosciences/FALCON\",\"title\":\"PacificBiosciences/FALCON\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/PacificBiosciences/FALCON\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@ParadoxYm in #531: hello. 我遇到了和你一样的问题。No such file or directory:0-rawreads/daligner-scatter/scattered.json\\r\\n请问 你是怎么解决的\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/PacificBiosciences/FALCON/issues/531#issuecomment-293560839\"}}}\r\n—\r\nYou are receiving this because you commented.\r\nReply to this email directly, view it on GitHub, or mute the thread.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/PacificBiosciences/FALCON/issues/531#issuecomment-293773711"}}}

**Comment by ParadoxYm** [comment]
谢谢 但是我还是没法运行ecoli 请问可以给我一个fc_run.cfg参考一下吗
麻烦了 谢谢你

**Comment by hanxue1994** [comment]
我就是使用的example里面的cfg，为什么运行不了啊，报错是什么
发自网易邮箱大师
在2017年04月13日 18:53，ParadoxYm 写道： 谢谢 但是我还是没法运行ecoli 请问可以给我一个fc_run.cfg参考一下吗
麻烦了 谢谢你

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PacificBiosciences/FALCON","title":"PacificBiosciences/FALCON","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PacificBiosciences/FALCON"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ParadoxYm in #531: 谢谢 但是我还是没法运行ecoli 请问可以给我一个fc_run.cfg参考一下吗\r\n麻烦了 谢谢你"}],"action":{"name":"View Issue","url":"https://github.com/PacificBiosciences/FALCON/issues/531#issuecomment-293857516"}}}

**Comment by ParadoxYm** [comment]
这是我的错误
fc_run fc_run.cfg logging.ini
2017-04-13 12:02:42,685 - fc_run - INFO - Setup logging from file "logging.ini".
2017-04-13 12:02:42,714 - fc_run - INFO - fc_run started with configuration fc_run.cfg
/public/home/asc0006/ym/FALCON-integrate/FALCON/falcon_kit/run_support.py:172: UserWarning: Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately
  warnings.warn("Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately")
/public/home/asc0006/ym/FALCON-integrate/FALCON/falcon_kit/run_support.py:176: UserWarning: Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately
  warnings.warn("Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately")
2017-04-13 12:02:42,720 - fc_run - INFO -  No target specified, assuming "assembly" as target 
/public/home/asc0006/ym/FALCON-integrate/FALCON/falcon_kit/run_support.py:371: UserWarning: Unexpected keys in input config: set(['pa_concurrent_jobs', 'ovlp_concurrent_jobs', 'jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
2017-04-13 12:02:42,720 - pypeflow.simple_pwatcher_bridge - WARNING - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/public/home/asc0006/ym/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-04-13 12:02:42,721 - pypeflow.simple_pwatcher_bridge - INFO - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/public/home/asc0006/ym/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-04-13 12:02:42,723 - pypeflow.simple_pwatcher_bridge - INFO - job_type='local', job_queue='default', sge_option='-pe smp 8 -q production', use_tmpdir=False, squash=False
2017-04-13 12:02:42,725 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 1
2017-04-13 12:02:42,726 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2017-04-13 12:02:42,731 - pwatcher.fs_based - INFO - starting job Job(jobid='P8c777fa25ba818', cmd='/bin/bash run.sh', rundir='/public/home/asc0006/ym/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-04-13 12:02:42,741 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P8c777fa25ba818', cmd='/bin/bash run.sh', rundir='/public/home/asc0006/ym/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-04-13 12:02:42,742 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
2017-04-13 12:02:42,843 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.2s
2017-04-13 12:02:43,044 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.3s
2017-04-13 12:02:43,354 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2017-04-13 12:02:43,354 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 1
2017-04-13 12:02:43,354 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 0
2017-04-13 12:02:43,359 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 2
2017-04-13 12:02:43,359 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads)
2017-04-13 12:02:43,367 - pwatcher.fs_based - INFO - starting job Job(jobid='P9f5fca28943285', cmd='/bin/bash run.sh', rundir='/public/home/asc0006/ym/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-04-13 12:02:43,378 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P9f5fca28943285', cmd='/bin/bash run.sh', rundir='/public/home/asc0006/ym/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-04-13 12:02:43,379 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
2017-04-13 12:02:43,480 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.2s
2017-04-13 12:02:43,681 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.3s
2017-04-13 12:02:43,986 - pypeflow.simple_pwatcher_bridge - ERROR - Task Node(0-rawreads) failed with exit-code=256
2017-04-13 12:02:43,986 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([])
2017-04-13 12:02:43,986 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 0
2017-04-13 12:02:43,986 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 1
2017-04-13 12:02:43,987 - pypeflow.simple_pwatcher_bridge - ERROR - Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
2017-04-13 12:02:43,987 - pypeflow.simple_pwatcher_bridge - ERROR - ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/home/asc0006/ym/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/public/home/asc0006/ym/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 462, in main
    main1(argv[0], args.config, args.logger)
  File "/public/home/asc0006/ym/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/public/home/asc0006/ym/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 194, in run
    wf.refreshTargets([rdb_build_done])
  File "/public/home/asc0006/ym/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/public/home/asc0006/ym/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 292, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
make: *** [run] 错误 1
