### ISSUE TITLE
Falcon crashes in several LAmerge jobs.  

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#542]
Hi, Chris,

How shall I investigate this:

the stderr for these LAmerge jobs end with this (below).  If I restart Falcon, it dies again with the same error.

Any thoughts of what I should look for?

Thanks!
David

2017-04-05 09:48:27,102 - root - DEBUG - Checking existence of u'/net/eichler/vol26/7200/dgordon/clint6/0-rawreads/raw-gather/gathered_las.txt' with timeout=60
2017-04-05 09:48:27,106 - root - DEBUG - Checking existence of u'/net/eichler/vol26/7200/dgordon/clint6/0-rawreads/merge-scatter/scattered.json' with timeout=60
2017-04-05 09:48:28,694 - falcon_kit.pype_tasks - DEBUG - symlink '../job_10b34/L1.168.585.las' -> '/net/eichler/vol26/7200/dgordon/clint6/0-rawreads/m_00168/L1.168.585.las'
2017-04-05 09:48:28,695 - root - CRITICAL - Error in /net/eichler/vol2/home/dgordon/falcon/161115/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/net/eichler/vol26/7200/dgordon/clint6/0-rawreads/m_00168/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/net/eichler/vol2/home/dgordon/falcon/161115/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 149, in <module>
    main()
  File "/net/eichler/vol2/home/dgordon/falcon/161115/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 141, in main
    run(**vars(parsed_args))
  File "/net/eichler/vol2/home/dgordon/falcon/161115/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 126, in run
    func(self=self)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON/falcon_kit/pype_tasks.py", line 207, in task_run_las_merge
    os.symlink(src, tgt)
OSError: [Errno 17] File exists

real    0m1.986s
user    0m1.234s
sys     0m0.407s
 returned: 256

**Comment by dgordon562** [comment]
I am finding there is no problem with running rp_xxx.sh directly.  So I set up a script that runs like this:

cd 0-rawreads/m_00568; bash rp_00568.sh; cd ../..
cd 0-rawreads/m_00679; bash rp_00679.sh; cd ../..
cd 0-rawreads/m_00081; bash rp_00081.sh; cd ../..
.
.
.

However, will fc_run.py recognize that these have completed?  Will it notice the done flags?  Or must I edit some status file?  If so, which/where/how?

**Comment by BioWu** [comment]
You should ```touch``` one new ```run.sh.done``` file as other finished jobs. Then the ```fc_run``` will treat it as ```done``` job.
I suggest you always run the ```run.sh``` script in all broken steps.
:)
