### ISSUE TITLE
Task Node(0-rawreads) failed with exit-code=256

### ISSUE THREAD

**Issue by ParadoxYm** [PacificBiosciences/FALCON#549]
Who can help me TAT

This is my fc_run.cfg
```ini
[General]
use_tmpdir= true
job_type = local


input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

genome_size = 4000
seed_coverage = 20


#length_cutoff = 12000


length_cutoff_pr = 1


jobqueue = production
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```

---------------------------------------------

this is 
```py
git-sym update run/ecoli
-> in dir 'run/ecoli'
<- back to dir '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples'
symlink: 'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads'
-> in dir '/Users/paradox/Documents/asc/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
<- back to dir '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples'
git-sym show run/ecoli
-> in dir 'run/ecoli'
<- back to dir '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples'
symlink: 'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads'
symlink: 'run/ecoli/logging.ini'
/ run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads	.git-sym/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0
O run/ecoli/logging.ini	logging.ini
git-sym check run/ecoli
-> in dir 'run/ecoli'
<- back to dir '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples'
symlink: 'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads'
cd run/ecoli; rm -rf 0-rawreads/ 1-preads_ovl/ 2-asm-falcon/; ls -l; fc_run.py fc_run.cfg logging.ini
total 64
drwxr-xr-x  3 paradox  staff    102  4 13 19:53 data
-rw-r--r--@ 1 paradox  staff   1093  4 13 20:18 fc_run.cfg
-rw-r--r--  1 paradox  staff   1578  4 13 20:10 fc_run.log
-rw-r--r--  1 paradox  staff    297  4 13 19:53 input.fofn
lrwxr-xr-x  1 paradox  staff     17  4 13 19:53 logging.ini -> ../../logging.ini
-rw-r--r--  1 paradox  staff    128  4 13 19:53 makefile
drwxr-xr-x  6 paradox  staff    204  4 13 19:55 mypwatcher
-rw-r--r--  1 paradox  staff  11722  4 13 20:10 pypeflow.log
drwxr-xr-x  2 paradox  staff     68  4 13 19:55 scripts
drwxr-xr-x  2 paradox  staff     68  4 13 19:55 sge_log
2017-04-13 12:25:00,564 - fc_run - INFO - Setup logging from file "logging.ini".
2017-04-13 12:25:00,565 - fc_run - INFO - fc_run started with configuration fc_run.cfg
/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/run_support.py:172: UserWarning: Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately
  warnings.warn("Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately")
/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/run_support.py:176: UserWarning: Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately
  warnings.warn("Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately")
2017-04-13 12:25:00,566 - fc_run - INFO -  No target specified, assuming "assembly" as target 
/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/run_support.py:371: UserWarning: Unexpected keys in input config: set(['ovlp_concurrent_jobs', 'pa_concurrent_jobs', 'jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
2017-04-13 12:25:00,566 - pypeflow.simple_pwatcher_bridge - WARNING - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-04-13 12:25:00,566 - pypeflow.simple_pwatcher_bridge - INFO - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-04-13 12:25:00,569 - pypeflow.simple_pwatcher_bridge - INFO - job_type='local', job_queue='default', sge_option='-pe smp 8 -q production', use_tmpdir='/var/folders/t3/xgh7tl410f9c_4xb0blyd7zh0000gn/T', squash=True
2017-04-13 12:25:00,570 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 1
2017-04-13 12:25:00,570 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2017-04-13 12:25:00,571 - pwatcher.fs_based - INFO - starting job Job(jobid='P621376a83654ea', cmd='/bin/bash run.sh', rundir='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-04-13 12:25:00,576 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P621376a83654ea', cmd='/bin/bash run.sh', rundir='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-04-13 12:25:00,577 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2017-04-13 12:25:00,577 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 1
2017-04-13 12:25:00,577 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 0
2017-04-13 12:25:00,580 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 2
2017-04-13 12:25:00,580 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads)
2017-04-13 12:25:00,582 - pwatcher.fs_based - INFO - starting job Job(jobid='Pfb3d2b446d8d80', cmd='/bin/bash run.sh', rundir='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-04-13 12:25:00,587 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pfb3d2b446d8d80', cmd='/bin/bash run.sh', rundir='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-04-13 12:25:00,588 - pypeflow.simple_pwatcher_bridge - ERROR - Task Node(0-rawreads) failed with exit-code=99
2017-04-13 12:25:00,588 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([])
2017-04-13 12:25:00,588 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 0
2017-04-13 12:25:00,588 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 1
2017-04-13 12:25:00,588 - pypeflow.simple_pwatcher_bridge - ERROR - Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
2017-04-13 12:25:00,589 - pypeflow.simple_pwatcher_bridge - ERROR - ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/Users/paradox/Documents/asc/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 462, in main
    main1(argv[0], args.config, args.logger)
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/Users/paradox/Documents/asc/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 194, in run
    wf.refreshTargets([rdb_build_done])
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 292, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
make: *** [run-ecoli] Error 1
```
----------------------------------------
And this is stderr
```py
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads --heartbeat-file=/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/heartbeats/heartbeat-Pfb3d2b446d8d80 --exit-file=/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/exits/exit-Pfb3d2b446d8d80 --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', exit_file='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/exits/exit-Pfb3d2b446d8d80', heartbeat_file='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/heartbeats/heartbeat-Pfb3d2b446d8d80', rate=10.0)

cwd:'/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads'
hostname=ParadoxdeMacBook-Pro.local
heartbeat_fn='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/heartbeats/heartbeat-Pfb3d2b446d8d80'
exit_fn='/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/exits/exit-Pfb3d2b446d8d80'
sleep_s=10.0
before setpgid: pid=2531 pgid=2516
 after setpgid: pid=2531 pgid=2531
In cwd: /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads, Blocking call: '/bin/bash run.sh'
cd /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads
+ cd /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads
bash task.sh
+ bash task.sh
2017-04-13 19:55:48,346 - root - DEBUG - Running "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/task.json"
2017-04-13 19:55:48,347 - root - DEBUG - Checking existence of '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/task.json' with timeout=60
2017-04-13 19:55:48,347 - root - DEBUG - Loading JSON from '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/task.json'
2017-04-13 19:55:48,348 - root - DEBUG - {u'inputs': {u'input_fofn': u'/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs/input.fofn'},
 u'outputs': {u'length_cutoff': u'length_cutoff',
              u'raw_reads_db': u'raw_reads.db',
              u'rdb_build_done': u'rdb_build_done',
              u'run_jobs': u'run_jobs.sh'},
 u'parameters': {u'config': {u'avoid_text_file_busy': True,
                             u'cns_concurrent_jobs': 8,
                             u'da_concurrent_jobs': 32,
                             u'dazcon': False,
                             u'default_concurrent_jobs': 8,
                             u'dust': False,
                             u'falcon_sense_greedy': False,
                             u'falcon_sense_option': u'--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6',
                             u'falcon_sense_skip_contained': False,
                             u'fc_concurrent_jobs': 8,
                             u'fc_ovlp_to_graph_option': u' --min_len 12000',
                             u'genome_size': 0,
                             u'input_fofn': u'input.fofn',
                             u'input_type': u'raw',
                             u'install_prefix': u'/Users/paradox/anaconda2',
                             u'job_queue': u'default',
                             u'job_type': u'local',
                             u'la_concurrent_jobs': 32,
                             u'length_cutoff': 12000,
                             u'length_cutoff_pr': 12000,
                             u'overlap_filtering_setting': u'--max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24',
                             u'ovlp_DBsplit_option': u'-x500 -s50',
                             u'ovlp_HPCdaligner_option': u'-v -B4 -t32 -h60 -e.96 -l500 -s1000',
                             u'pa_DBdust_option': u'-w128 -t2.5 -m20',
                             u'pa_DBsplit_option': u'-x500 -s50',
                             u'pa_HPCdaligner_option': u'-v -B4 -t16 -e.70 -l1000 -s1000',
                             u'pa_dazcon_option': u'-j 4 -x -l 500',
                             u'pda_concurrent_jobs': 32,
                             u'pla_concurrent_jobs': 32,
                             u'pwatcher_directory': u'mypwatcher',
                             u'pwatcher_type': u'fs_based',
                             u'seed_coverage': 20,
                             u'sge_option': u'-pe smp 8 -q production',
                             u'sge_option_cns': u'-pe smp 8 -q production',
                             u'sge_option_da': u'-pe smp 8 -q production',
                             u'sge_option_fc': u'-pe smp 24 -q production',
                             u'sge_option_la': u'-pe smp 2 -q production',
                             u'sge_option_pda': u'-pe smp 8 -q production',
                             u'sge_option_pla': u'-pe smp 2 -q production',
                             u'skip_checks': False,
                             u'stop_all_jobs_on_failure': False,
                             u'target': u'assembly',
                             u'use_tmpdir': False},
                 u'config_fn': u'/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/fc_run.cfg',
                 u'sge_option': u'-pe smp 8 -q production',
                 u'work_dir': u'/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads'},
 u'python_function': u'falcon_kit.pype_tasks.task_build_rdb'}
2017-04-13 19:55:48,349 - root - DEBUG - CD: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads' <- '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads'
2017-04-13 19:55:48,349 - root - DEBUG - Checking existence of u'/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs/input.fofn' with timeout=60
2017-04-13 19:55:48,366 - root - DEBUG - CD: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads' <- '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads'
2017-04-13 19:55:48,367 - pypeflow.do_support - INFO - !/bin/bash -vex /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/prepare_rdb.sh
#!/bin/bash
set -vex
+ set -vex
set -o pipefail
+ set -o pipefail
#fc_fasta2fasta < /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs/input.fofn >| fc.fofn
while read fn; do  undexta -vkU -w60 -i <  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs/input.fofn
+ read fn
+ undexta -vkU -w60 -i
/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/prepare_rdb.sh: line 5: /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads/subreads.1.dexta: No such file or directory
+ fasta2DB -v raw_reads -isubreads.1.dexta
Skipping 'subreads.1.dexta', file is empty!
2017-04-13 19:55:48,377 - root - DEBUG - CD: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads' -> '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads'
2017-04-13 19:55:48,378 - root - DEBUG - CD: '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads' -> '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads'
2017-04-13 19:55:48,378 - root - CRITICAL - Error in /Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/Users/paradox/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/paradox/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/Users/paradox/Documents/asc/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/prepare_rdb.sh'

real	0m0.098s
user	0m0.062s
sys	0m0.030s
 returned: 256
```

**Comment by Res2677** [comment]
Hi,ParadoxYm.I get the same error,I dont't know how to slove this problem. Have you solved it?help me.....please/(ㄒoㄒ)/~~

**Comment by pb-cdunn** [comment]
```
while read fn; do  undexta -vkU -w60 -i <  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs/input.fofn
+ read fn
+ undexta -vkU -w60 -i
/Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/prepare_rdb.sh: line 5: /Users/paradox/Documents/asc/FALCON-integrate/FALCON-examples/run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads/subreads.1.dexta: No such file or directory
+ fasta2DB -v raw_reads -isubreads.1.dexta
Skipping 'subreads.1.dexta', file is empty!
```
That indicates a problem obtaining the data. Possibly you need to update `input.fofn`, maybe to something like
```
data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads
```
