### ISSUE TITLE
falcon crash

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#55]
Hi, Jason,

I've had fc_run.py crash on me a number of times with the python key error below.  It isn't a show-stopper because I just restart fc_run.py and it then completes successfully, but it is a minor problem because I might not notice it is dead for a few days.

I believe the conditions under which it occurs are the following:  some jobs are running and they die (for one reason or another).  So I restart fc_run.py which restarts those jobs.  This time they complete.  fc_run.py sees their done files and then crashes with this key error.  

I should mention that the crash doesn't always say:

'task://localhost/build_p_rdb'

Sometimes it says:

'task://localhost/m_00054_preads'
or
'task://localhost/ct_00102'

Is there is a simple change I could make to controller.py so that it would handle this problem?

Thanks!
David

> fc_run.py fc_run_human.cfg
 No target specified, assuming "assembly" as target 
Your job 4419007 ("ct_00353-06239db8") has been submitted
Your job 4419008 ("ct_00050-083f149c") has been submitted
Your job 4419009 ("ct_00333-0a7520bc") has been submitted
Traceback (most recent call last):
  File "/net/gs/vol1/home/dgordon/falcon3/FALCON-master/install/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/net/gs/vol1/home/dgordon/falcon3/FALCON-master/install/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 801, in <module>
    wf.refreshTargets(updateFreq = wait_time) #all            
  File "/net/gs/vol1/home/dgordon/falcon3/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/net/gs/vol1/home/dgordon/falcon3/FALCON-master/install/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/build_p_rdb'
(fc_env){dgordon}e183:/net/eichler/vol20/projects/pacbio/nobackups/users/dgordon/falcon_chm13

**Comment by pb-jchin** [comment]
@dgordon562  I think this is a duplicated of https://github.com/PacificBiosciences/FALCON/issues/12 
I have fixed it in a recent commit for pypeFlow.
