### ISSUE TITLE
Exit with return error code 256

### ISSUE THREAD

**Issue by Rokami** [PacificBiosciences/FALCON#554]
Dear Falcon team,
I have installed FALCON-integrate in my service, and when I assembly a PacBio dataset, the program always exit at the end of running `0-rawreads`, I check error jobs' stderr and they have same problem:
  ```
raw_reads.14.raw_reads.58.C0: 8,794 all OK
  raw_reads.14.raw_reads.58.C1: Duplicate overlap (70177 vs 299317)
```

```
  raw_reads.58.raw_reads.14.C0: 8,634 all OK
  raw_reads.58.raw_reads.14.C1: Duplicate overlap (299317 vs 70177)
  raw_reads.58.raw_reads.14.C2: 8,415 all OK
  raw_reads.58.raw_reads.14.C3: 8,029 all OK
```

 
the error code is:
```
2017-05-06 06:58:40,911 - root - CRITICAL - Error in /usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py with args="{'json_fn': '/data4/zx/fcrun/0-rawreads/job_0708/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/local/python2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/python2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/usr/local/python2.7.9/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /data4/zx/fcrun/0-rawreads/job_0708/rj_0708.sh'

real    5m33.183s
user    9m5.084s
sys     0m27.842s
 returned: 256

```
my `cfg` options are:
```
[General]
job_type=local
input_fofn = TK212.fofn
input_type = raw
length_cutoff = 8000
length_cutoff_pr = 8000
jobqueue = TK212_assembly
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 8 -q %(jobqueue)s
pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32
cns_concurrent_jobs = 32
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
pa_HPCdaligner_option = -v -B10 -t16 -e.70 -l1000 -s1000 -dal4
ovlp_HPCdaligner_option = -v -B10 -t32 -h60 -e.96 -l500 -s1000 -dal4
falcon_sense_option = --output_muti --min_idt 0.70 --min_cov 2 --max_n_read 200 --n_core 12
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 10 --bestn 8 --n_core 24

```
What should I do to fix it or avoid duplicate overlap?

**Comment by BioWu** [comment]
Adding the ```skip_ckeck=true``` to your configure ```fc_run.cfg``` file, then re-submit it.
