### ISSUE TITLE
falcon large genome,failed at the second step!

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/FALCON#59]
It ended in the "1-preads_ovl" directory,and the log shows:
```
Your job 49978 ("d_05e8bcf4_preads-34459630") has been submitted
 No target specified, assuming "assembly" as target
Traceback (most recent call last):
  File "/home/nfs_UserData_220/falcon/falcon_bk/FALCON-master/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/home/nfs_UserData_220/falcon/falcon_bk/FALCON-master/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/nfs_UserData_220/falcon/falcon_bk/FALCON-master/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/home/nfs_UserData_220/falcon/falcon_bk/FALCON-master/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 738, in <module>
    wf.refreshTargets(updateFreq = wait_time) #all
  File "/home/nfs_UserData_220/falcon/falcon_bk/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/nfs_UserData_220/falcon/falcon_bk/FALCON-master/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/d_8a60cdc5_preads'
```
because it has produced very large rawreads data,I need to restart it from where it break down.
I have read the similar issue #12, but still don't know how to restart it with falcon or sge. Could you help me,please?
ps:Now I am running the `run_jobs.sh` script in the `1-preads_ovl` directory with commad `./run_jobs.sh" or "qsub -cwd  -l h=nodesuper -q all.q -pe openmp 90 run_jobs.sh`. But it seems that it is not running in parallel mode.

**Comment by pb-cdunn** [comment]
Try with latest *master* branch. Maybe this is not happening anymore.
