### ISSUE TITLE
Fail to run ecoli test

### ISSUE THREAD

**Issue by Fyphia** [PacificBiosciences/FALCON#595]
Hi everyone,
I run ecoli test in the FALCON-examples, and I got an error like this:
The output is :
```
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target
/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/run_support.py:339: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO] Skipping already done task: task:///opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py/task_make_fofn_abs_raw
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_build_rdb()
[INFO]script_fn:'/bigdata/baolab/fxie/new2/FALCON03/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/prepare_rdb.sh'
[INFO]jobid=Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30
StringJobSubmitter('bash -C ${CMD} > ${STDOUT_FILE} 2> ${STDERR_FILE}')
[INFO]starting job Job(jobid='Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30', cmd='/bin/bash prepare_rdb.sh', rundir='/bigdata/baolab/fxie/new2/FALCON03/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={})
[INFO]!chmod +x /bigdata/baolab/fxie/new2/FALCON03/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/run-Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30.bash
mapping, submission_string: {'NPROC': '4', 'STDERR_FILE': '/bigdata/baolab/fxie/new2/FALCON03/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/run-Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30.bash.stderr', 'CMD': '/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/pwatcher/mains/job_start.sh', 'JOB_ID': 'Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30', 'STDOUT_FILE': '/bigdata/baolab/fxie/new2/FALCON03/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/run-Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30.bash.stdout'}, bash -C ${CMD} > ${STDOUT_FILE} 2> ${STDERR_FILE}
[INFO]Queued 'task:///opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py/task_build_rdb' ...
[INFO]tick: 4, #updatedTasks: 1, sleep_time=0.100000
[INFO]tick: 8, #updatedTasks: 1, sleep_time=0.500000
[ERROR]Task Fred{'URL': 'task:///opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py/task_build_rdb'} failed with exit-code=127
[INFO]Failure ('fail'). Joining 'task:///opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py/task_build_rdb'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/pypeflow/controller.py:537: UserWarning:
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 578, in main
    main1(argv[0], args.config, args.logger)
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 355, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 412, in run
    wf.refreshTargets([rdb_build_done])
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/opt/linux/centos/7.x/x86_64/pkgs/python/2.7.12/falcon-env/lib/python2.7/site-packages/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```
Can anyone help me with this? Thanks a lot!
Fyphia

**Comment by skingan** [comment]
Hi Fyphia,

Your run is failing on the first step: building the raw read database. Try inspecting the stderr file:

`/bigdata/baolab/fxie/new2/FALCON03/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/run-Jecdfa1de7e0513617f96f46044239770aabcab7dc77fbdfa02d9a11ba3697f30.bash.std*`

This should give a clue as to why your ENV is failing.

Sarah
