### ISSUE TITLE
fail to "make run-synth0" in  FALCON-examples

### ISSUE THREAD

**Issue by VanceEver** [PacificBiosciences/FALCON#618]
I have run synth0 test in the FALCON-examples several times, but always failed.
and  error[output] like this:
```
(fc_env) root@iZwz9gfo7g3450iygsp5zpZ:~/FALCON-integrate/FALCON-examples# make run-synth0
git-sym update run/synth0
-> in dir 'run/synth0'
<- back to dir '/root/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
-> in dir '/root/FALCON-integrate/FALCON-examples/.git/git-sym-local/links'
<- back to dir '/root/FALCON-integrate/FALCON-examples'
git-sym show run/synth0
-> in dir 'run/synth0'
<- back to dir '/root/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
/ run/synth0/data/synth5k	.git-sym/synth5k.2016-11-02
git-sym check run/synth0
-> in dir 'run/synth0'
<- back to dir '/root/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
cd run/synth0; rm -rf 0-rawreads/ 1-preads_ovl/ 2-asm-falcon/; ls -l; fc_run.py fc_run.cfg logging.ini
total 76
-rw-r--r-- 1 root root 11599 Mar 12 13:07 all.log
-rwxr-xr-x 1 root root  1067 Mar 12 12:41 check.py
drwxr-xr-x 2 root root  4096 Mar 12 12:41 data
-rw-r--r-- 1 root root 18790 Mar 12 12:46 fc.log
-rw-r--r-- 1 root root   251 Mar 12 12:41 fc_many.cfg
-rw-r--r-- 1 root root  1611 Mar 12 12:41 fc_preads.cfg
-rw-r--r-- 1 root root  1698 Mar 12 12:41 fc_run.cfg
-rw-r--r-- 1 root root    28 Mar 12 12:41 input.fofn
-rw-r--r-- 1 root root   461 Mar 12 12:41 logging.ini
-rw-r--r-- 1 root root   770 Mar 12 12:41 logging.json
-rw-r--r-- 1 root root  1026 Mar 12 12:41 logging.many.ini
-rw-r--r-- 1 root root   332 Mar 12 12:41 makefile
-rw-r--r-- 1 root root    56 Mar 12 12:41 preads.fofn
[6265]$('lfs setstripe -c 12 /root/FALCON-integrate/FALCON-examples/run/synth0')
sh: 1: lfs: not found
[6265]WARNING: Call 'lfs setstripe -c 12 /root/FALCON-integrate/FALCON-examples/run/synth0' returned 32512.
2018-03-12 05:12:29,111[INFO] Setup logging from file "logging.ini".
2018-03-12 05:12:29,114[INFO] fc_run started with configuration fc_run.cfg
2018-03-12 05:12:29,115[INFO]  No target specified, assuming "assembly" as target 
2018-03-12 05:12:29,116[WARNING] In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/root/FALCON-integrate/pypeFLOW/pwatcher/blocking.pyc'>
2018-03-12 05:12:29,116[INFO] In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/root/FALCON-integrate/pypeFLOW/pwatcher/blocking.pyc'>
2018-03-12 05:12:29,116[INFO] job_type='string', job_queue='bash -C ${CMD}', sge_option='-pe smp 8 -q bash -C ${CMD}', use_tmpdir=False, squash=True, job_name_style='1'
2018-03-12 05:12:29,118[INFO] Num unsatisfied: 1, graph: 1
2018-03-12 05:12:29,118[INFO] About to submit: Node(0-rawreads/raw-fofn-abs)
2018-03-12 05:12:29,119[INFO] !chmod +x /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run-P0_raw_fofn_abs_bee22a18a7f7fa07ae7e28ff890cf5d9.bash
2018-03-12 05:12:29,122[INFO] sleep 0.1s
2018-03-12 05:12:29,125[INFO] Popen: 'bash -C /root/FALCON-integrate/pypeFLOW/pwatcher/mains/job_start.sh'
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run-P0_raw_fofn_abs_bee22a18a7f7fa07ae7e28ff890cf5d9.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run-P0_raw_fofn_abs_bee22a18a7f7fa07ae7e28ff890cf5d9.bash ]]

bash ${executable}
+ bash /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run-P0_raw_fofn_abs_bee22a18a7f7fa07ae7e28ff890cf5d9.bash

+ '[' '!' -d /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs ']'
+ cd /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
cd /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs
+ cd /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs
bash task.sh
+ bash task.sh
iZwz9gfo7g3450iygsp5zpZ
HOME=/root
LANG=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
MAKEFLAGS=
MAKELEVEL=1
MAKE_TERMERR=/dev/pts/0
MAKE_TERMOUT=/dev/pts/0
MFLAGS=
PATH=/root/FALCON-integrate/fc_env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs
PYPEFLOW_JOB_START_SCRIPT=/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run-P0_raw_fofn_abs_bee22a18a7f7fa07ae7e28ff890cf5d9.bash
PYPEFLOW_JOB_START_TIMEOUT=60
SHELL=/bin/bash
SHLVL=5
SSH_CLIENT=36.149.1.125 62927 22
SSH_CONNECTION=36.149.1.125 62927 172.16.252.178 22
SSH_TTY=/dev/pts/0
TERM=xterm
USER=root
_=/usr/bin/env
VIRTUAL_ENV=/root/FALCON-integrate/fc_env
XDG_RUNTIME_DIR=/run/user/0
XDG_SESSION_ID=117
/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs
2018-03-12 13:12:29,177 - root - DEBUG - Running "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/task.json"
2018-03-12 13:12:29,179 - root - DEBUG - Checking existence of '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/task.json' with timeout=30
2018-03-12 13:12:29,179 - root - DEBUG - Loading JSON from '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/task.json'
2018-03-12 13:12:29,179 - root - DEBUG - {u'inputs': {u'i_fofn': u'/root/FALCON-integrate/FALCON-examples/run/synth0/input.fofn'},
 u'outputs': {u'o_fofn': u'input.fofn'},
 u'parameters': {},
 u'python_function': u'falcon_kit.pype_tasks.task_make_fofn_abs_raw'}
2018-03-12 13:12:29,179 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs' <- '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs'
2018-03-12 13:12:29,179 - root - DEBUG - Checking existence of u'/root/FALCON-integrate/FALCON-examples/run/synth0/input.fofn' with timeout=30
2018-03-12 13:12:29,179 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs' <- '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs'
2018-03-12 13:12:29,190 - falcon_kit.util.system - INFO - Absolutizing FOFN in dir=u'/root/FALCON-integrate/FALCON-examples/run/synth0'
2018-03-12 13:12:29,191 - pypeflow.do_support - INFO - !/bin/bash -vex noop.sh
echo NOOP raw
+ echo NOOP raw
NOOP raw
2018-03-12 13:12:29,193 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs' -> '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs'
2018-03-12 13:12:29,193 - root - DEBUG - Checking existence of u'input.fofn' with timeout=30
2018-03-12 13:12:29,193 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs' -> '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs'

real	0m0.065s
user	0m0.060s
sys	0m0.000s
touch /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run.sh.done
+ touch /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/run.sh.done
+ finish
+ echo 'finish code: 0'
finish code: 0
2018-03-12 05:12:29,222[INFO] recently_satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2018-03-12 05:12:29,223[INFO] Num satisfied in this iteration: 1
2018-03-12 05:12:29,223[INFO] Num still unsatisfied: 0
2018-03-12 05:12:29,225[INFO] Num unsatisfied: 1, graph: 2
2018-03-12 05:12:29,225[INFO] About to submit: Node(0-rawreads)
2018-03-12 05:12:29,227[INFO] !chmod +x /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/run-P0_0_rawreads_d47002dd853df6a63f1964a12d25d8c2.bash
2018-03-12 05:12:29,229[INFO] sleep 0.1s
2018-03-12 05:12:29,233[INFO] Popen: 'bash -C /root/FALCON-integrate/pypeFLOW/pwatcher/mains/job_start.sh'
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/run-P0_0_rawreads_d47002dd853df6a63f1964a12d25d8c2.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/run-P0_0_rawreads_d47002dd853df6a63f1964a12d25d8c2.bash ]]

bash ${executable}
+ bash /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/run-P0_0_rawreads_d47002dd853df6a63f1964a12d25d8c2.bash

+ '[' '!' -d /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads ']'
+ cd /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
cd /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
+ cd /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
bash task.sh
+ bash task.sh
iZwz9gfo7g3450iygsp5zpZ
HOME=/root
LANG=en_US.UTF-8
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LOGNAME=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
MAKEFLAGS=
MAKELEVEL=1
MAKE_TERMERR=/dev/pts/0
MAKE_TERMOUT=/dev/pts/0
MFLAGS=
PATH=/root/FALCON-integrate/fc_env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
PYPEFLOW_JOB_START_SCRIPT=/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/run-P0_0_rawreads_d47002dd853df6a63f1964a12d25d8c2.bash
PYPEFLOW_JOB_START_TIMEOUT=60
SHELL=/bin/bash
SHLVL=5
SSH_CLIENT=36.149.1.125 62927 22
SSH_CONNECTION=36.149.1.125 62927 172.16.252.178 22
SSH_TTY=/dev/pts/0
TERM=xterm
USER=root
_=/usr/bin/env
VIRTUAL_ENV=/root/FALCON-integrate/fc_env
XDG_RUNTIME_DIR=/run/user/0
XDG_SESSION_ID=117
/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
2018-03-12 13:12:29,296 - root - DEBUG - Running "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/task.json"
2018-03-12 13:12:29,299 - root - DEBUG - Checking existence of '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/task.json' with timeout=30
2018-03-12 13:12:29,302 - root - DEBUG - Loading JSON from '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/task.json'
2018-03-12 13:12:29,304 - root - DEBUG - {u'inputs': {u'input_fofn': u'/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/input.fofn'},
 u'outputs': {u'length_cutoff': u'length_cutoff',
              u'raw_reads_db': u'raw_reads.db',
              u'rdb_build_done': u'rdb_build_done',
              u'run_jobs': u'run_jobs.sh'},
 u'parameters': {u'config': {u'LA4Falcon_preload': True,
                             u'avoid_text_file_busy': True,
                             u'cns_concurrent_jobs': 32,
                             u'da_concurrent_jobs': 32,
                             u'dazcon': False,
                             u'default_concurrent_jobs': 8,
                             u'falcon_sense_greedy': False,
                             u'falcon_sense_option': u'--output_multi --min_idt 0.70 --min_cov 1 --max_n_read 20000 --n_core 0',
                             u'falcon_sense_skip_contained': False,
                             u'fc_concurrent_jobs': 8,
                             u'fc_ovlp_to_graph_option': u' --min_len 1',
                             u'genome_size': 5000,
                             u'input_fofn': u'input.fofn',
                             u'input_type': u'raw',
                             u'install_prefix': u'/root/FALCON-integrate/fc_env',
                             u'job_name_style': u'1',
                             u'job_queue': u'bash -C ${CMD}',
                             u'job_type': u'string',
                             u'la_concurrent_jobs': 32,
                             u'length_cutoff': -1,
                             u'length_cutoff_pr': 1,
                             u'overlap_filtering_setting': u'--max_diff 10000 --max_cov 100000 --min_cov 1 --min_len 1 --bestn 1000 --n_core 0',
                             u'ovlp_DBsplit_option': u'-a -x5 -s50',
                             u'ovlp_HPCdaligner_option': u'-v -B4 -t50 -h1 -e.99 -l1 -s1000',
                             u'pa_DBdust_option': u'',
                             u'pa_DBsplit_option': u'-a -x5 -s.065536',
                             u'pa_HPCdaligner_option': u'-v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000',
                             u'pa_HPCrepmask_1_option': u' -g1 -c20 -mtan',
                             u'pa_HPCrepmask_2_option': u' -g10 -c15 -mtan -mrep1',
                             u'pa_HPCtanmask_option': u'',
                             u'pa_damasker_HPCdaligner_option': u' -mtan -mrep1 -mrep10',
                             u'pa_dazcon_option': u'-j 4 -x -l 500',
                             u'pa_repmask_levels': 0,
                             u'pa_use_repmask': False,
                             u'pa_use_tanmask': False,
                             u'pda_concurrent_jobs': 32,
                             u'pla_concurrent_jobs': 32,
                             u'pwatcher_directory': u'mypwatcher',
                             u'pwatcher_type': u'blocking',
                             u'seed_coverage': 20.0,
                             u'sge_option': u'-pe smp 8 -q bash -C ${CMD}',
                             u'sge_option_cns': u'-pe smp 8 -q bash -C ${CMD}',
                             u'sge_option_da': u'-pe smp 8 -q bash -C ${CMD}',
                             u'sge_option_fc': u'-pe smp 24 -q bash -C ${CMD}',
                             u'sge_option_la': u'-pe smp 2 -q bash -C ${CMD}',
                             u'sge_option_pda': u'-pe smp 8 -q bash -C ${CMD}',
                             u'sge_option_pla': u'-pe smp 2 -q bash -C ${CMD}',
                             u'skip_checks': False,
                             u'stop_all_jobs_on_failure': True,
                             u'target': u'assembly',
                             u'use_tmpdir': False},
                 u'config_fn': u'/root/FALCON-integrate/FALCON-examples/run/synth0/fc_run.cfg',
                 u'sge_option': u'-pe smp 8 -q bash -C ${CMD}',
                 u'work_dir': u'/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads'},
 u'python_function': u'falcon_kit.pype_tasks.task_build_rdb'}
2018-03-12 13:12:29,308 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads' <- '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads'
2018-03-12 13:12:29,308 - root - DEBUG - Checking existence of u'/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/input.fofn' with timeout=30
2018-03-12 13:12:29,308 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads' <- '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads'
2018-03-12 05:12:29,330[INFO] sleep 0.2s
2018-03-12 13:12:29,335 - pypeflow.do_support - INFO - !/bin/bash -vex /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/prepare_rdb.sh
#!/bin/bash
set -vex
+ set -vex
echo "PBFALCON_ERRFILE=$PBFALCON_ERRFILE"
+ echo PBFALCON_ERRFILE=
PBFALCON_ERRFILE=
set -o pipefail
+ set -o pipefail
#fc_fasta2fasta < /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/input.fofn >| fc.fofn
while read fn; do  undexta -vkU -w60 -i <  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs/input.fofn
+ read fn
+ fasta2DB -v raw_reads -isubreads.dexta
+ undexta -vkU -w60 -i
Processing 'Standard Input' ...
Adding 'subreads.dexta.fasta' ...
Done
+ read fn
#cat fc.fofn | xargs rm -f
DBsplit -a -x5 -s.065536 raw_reads
+ DBsplit -a -x5 -s.065536 raw_reads
DBdust  raw_reads
+ DBdust raw_reads
LB=$(cat raw_reads.db | LD_LIBRARY_PATH= awk '$1 == "blocks" {print $3}')
cat raw_reads.db | LD_LIBRARY_PATH= awk '$1 == "blocks" {print $3}'
++ LD_LIBRARY_PATH=
++ awk '$1 == "blocks" {print $3}'
++ cat raw_reads.db
+ LB=2
rm -f run_jobs.sh
+ rm -f run_jobs.sh
CUTOFF=$(python2.7 -m falcon_kit.mains.calc_cutoff --coverage 20.0 5000 <(DBstats -b1 raw_reads))
python2.7 -m falcon_kit.mains.calc_cutoff --coverage 20.0 5000 <(DBstats -b1 raw_reads)
++ python2.7 -m falcon_kit.mains.calc_cutoff --coverage 20.0 5000 /dev/fd/63
DBstats -b1 raw_reads
+++ DBstats -b1 raw_reads
+ CUTOFF=2000
echo -n $CUTOFF >| length_cutoff
+ echo -n 2000
HPC.daligner -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000 -mdust -H$CUTOFF raw_reads 1-$LB >| run_jobs.sh
+ HPC.daligner -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000 -mdust -H2000 raw_reads 1-2
/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/prepare_rdb.sh: line 14: HPC.daligner: command not found
2018-03-12 13:12:29,373 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads' -> '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads'
2018-03-12 13:12:29,373 - root - DEBUG - CD: '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads' -> '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads'
2018-03-12 13:12:29,374 - root - CRITICAL - Error in /root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 236, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 209, in run_cfg_in_tmpdir
    run_python(python_function_name, myinputs, myoutputs, parameters)
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 111, in run_python
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 106, in run_python_func
    do_support.run_bash(script_fn)
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 32512 <- '/bin/bash -vex /root/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/prepare_rdb.sh'

real	0m0.140s
user	0m0.076s
sys	0m0.008s
+ finish
+ echo 'finish code: 1'
finish code: 1
2018-03-12 05:12:29,531[ERROR] Task Node(0-rawreads) failed with exit-code=1
2018-03-12 05:12:29,531[INFO] recently_satisfied: set([])
2018-03-12 05:12:29,531[INFO] Num satisfied in this iteration: 0
2018-03-12 05:12:29,532[INFO] Num still unsatisfied: 1
2018-03-12 05:12:29,532[ERROR] Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
2018-03-12 05:12:29,532[ERROR] ready: set([])
	submitted: set([])
2018-03-12 05:12:29,532[ERROR] Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/root/FALCON-integrate/fc_env/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit==0.7+git.560fc92e4b645b32e4c094e9ec64907c3e150458', 'console_scripts', 'fc_run.py')()
  File "/root/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.560fc92e4b645b32e4c094e9ec64907c3e150458-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 504, in main
    main1(argv[0], args.config, args.logger)
  File "/root/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.560fc92e4b645b32e4c094e9ec64907c3e150458-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 150, in main1
    input_fofn_plf=input_fofn_plf,
  File "/root/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.7+git.560fc92e4b645b32e4c094e9ec64907c3e150458-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 216, in run
    wf.refreshTargets([rdb_build_done])
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/root/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
makefile:4: recipe for target 'run-synth0' failed
make: *** [run-synth0] Error 1
```
Can anyone help me?
Thanks a lot.

**Comment by pb-cdunn** [comment]
Look in the run-dir of the failed task, `FALCON-examples/run/synth0/0-rawreads`. You should find `stderr` somewhere. That will probably make the problem obvious. Best guess: the install bin is not in your `$PATH`.
