### ISSUE TITLE
[ERROR]Task Node(3-unzip/reads/get_read_ctg_map) failed with exit-code=256

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON#620]
I am trying the latest Falcon+Unzip release and get this:

```
2018-03-13 08:29:57,555 - root - CRITICAL - Error in /ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/ebio/abt6_projects7/arabidopsis_genomes/data/ahal/genome/assembly/falcon/3-unzip/reads/get_read_ctg_map/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/lib/python2.7/site-packages/pypeflow/do_task.py", line 246, in <module>
    main()
  File "/ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/lib/python2.7/site-packages/pypeflow/do_task.py", line 238, in main
    run(**vars(parsed_args))
  File "/ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/lib/python2.7/site-packages/pypeflow/do_task.py", line 232, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/lib/python2.7/site-packages/pypeflow/do_task.py", line 208, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/lib/python2.7/site-packages/pypeflow/do_task.py", line 169, in run_bash
    util.system(cmd)
  File "/ebio/abt6_projects9/abt6_software/bin/Falcon/fc_env_180311/local/lib/python2.7/site-packages/pypeflow/util.py", line 35, in system
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 35584 <- 'bash user_script.sh'
```
I can manually execute the user_script.sh (`bash user_script.sh`) and it returns a read_to_contig_map.

Input was: 

ctg_paths 1132
sg_edges_list 598344
pread_id_file 732979
rawread_id_file 2119228
utg_data 10716

**Comment by fbemm** [comment]
The crash seems to be related to the cluster nodes.  `bash user_script.sh` stops with a segfault there. Still does not explain the low amount of output when manually executed on the head node.

**Comment by fbemm** [comment]
Error relates to different virtualenv's as it looks.
