### ISSUE TITLE
Task Node(0-rawreads) failed with exit-code=256

### ISSUE THREAD

**Issue by AlexYang01** [PacificBiosciences/FALCON#630]
Hi,
I am new to genome assembly.
I try to assembly millet genome with FALCON-integrate, but I get a failure message.

[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P322b271c640542', cmd='/bin/bash run.sh', rundir='/project/millet/01.assembly/falcon/0-rawreads', options={'JOB_QUEUE': 's2pnh.q', 'job_queue': 's2pnh.q', 'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'sge', 'JOB_OPTS': '-P s2pnh -l vf=26G,num_proc=4 -q s2pnh.q', 'NPROC': 1, 'njobs': 8}), lang_exe='/bin/bash'))
[INFO](slept for another 0.0s -- another 1 loop iterations)
[INFO](slept for another 0.3s -- another 2 loop iterations)
[INFO](slept for another 1.2s -- another 3 loop iterations)
[INFO](slept for another 3.0s -- another 4 loop iterations)
[INFO](slept for another 6.0s -- another 5 loop iterations)
[INFO](slept for another 10.5s -- another 6 loop iterations)
[INFO](slept for another 16.8s -- another 7 loop iterations)
[ERROR]Task Node(0-rawreads) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
[ERROR]ready: set([])
        submitted: set([])
Traceback (most recent call last):
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/fc_env/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run.py')()
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 626, in main
    main1(argv[0], args.config, args.logger)
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 153, in main1
    input_fofn_plf=input_fofn_plf,
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 261, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/FALCON/falcon_kit/pype.py", line 96, in gen_parallel_tasks
    wf.refreshTargets()
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/software/Falcon/Falcon_20180420/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 358, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])

Thanks for helping me!

**Comment by pb-cdunn** [comment]
Always look for `*stderr` files in the run-dir for the failing task. The top-level stderr is only for the workflow engine.
