### ISSUE TITLE
ValueError: ("Expected ',' or end-of-list in", 'falcon-kit==1.0+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65', 'at', '+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65')

### ISSUE THREAD

**Issue by zingdle** [PacificBiosciences/FALCON#633]
I followed the quick start [here](http://pb-falcon.readthedocs.io/en/latest/quick_start.html) but failed at line 90 in `install_unzip.sh`:
```
cd run/greg200k-sv2 && fc_run fc_run.cfg
```
It says:
```
Traceback (most recent call last):
  File "/home/lxl/yangsheng/me/fc_env_180425/bin/fc_run", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/lxl/yangsheng/me/fc_env_180425/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/home/lxl/yangsheng/me/fc_env_180425/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/lxl/yangsheng/me/fc_env_180425/lib/python2.7/site-packages/pkg_resources.py", line 601, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/home/lxl/yangsheng/me/fc_env_180425/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/lxl/yangsheng/me/fc_env_180425/lib/python2.7/site-packages/pkg_resources.py", line 2817, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'falcon-kit==1.0+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65', 'at', '+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65')
```
Any suggestions about this?

**Comment by zingdle** [comment]
Upgrading setuptools to the latest version solve the problem.
