### ISSUE TITLE
Falcon Unzip [ERROR]Task Node(3-unzip/reads) failed with exit-code=256

### ISSUE THREAD

**Issue by sebastianevda** [PacificBiosciences/FALCON#643]
Have recently installed falcon-integrate and falcon_unzip.

Falcon assemblies working well.

tried to run falcon unzip in the same directory as assembly and get the following error:
```sh
se389@node13:~/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff$ python $HOME/FALCON_unzip/src/py_scripts/fc_unzip.py fc_un
[INFO]Setup logging from file "None".
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/bioinf/se389/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/bioinf/se389/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]job_type='local', (default)job_defaults={}, use_tmpdir=None, squash=False, job_name_style=0
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(3-unzip/reads)
[INFO]mkdir -p "/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads"
[INFO] starting job Job(jobid='P950cc2b83cb905', cmd='/bin/bash run.sh', rundir='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_ce
[INFO]dir: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/jobs/P950cc2b83cb905'
CALL:
 '/bin/bash /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/wrappers/run-P950cc2b83cb905.bas
[INFO]pid=108714 pgid=108714 sub-pid=108766
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P950cc2b83cb905', cmd='/bin/bash run.sh', rundir='/home/bioinf/se389/FALCON-integrate/FALCON-exampl'))
[INFO]sleep 0.1s
[INFO]sleep 0.2s
[INFO]sleep 0.3s
[INFO]sleep 0.4s
[INFO]sleep 0.5s
[INFO]sleep 0.6s
[ERROR]Task Node(3-unzip/reads) failed with exit-code=256
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])
[ERROR]ready: set([])
        submitted: set([])
Traceback (most recent call last):
  File "/home/bioinf/se389/FALCON_unzip/src/py_scripts/fc_unzip.py", line 4, in <module>
    main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_unzip-0.4.0-py2.7.egg/falcon_unzip/unzip.py", line 384, in main
    unzip_all(config)
  File "/usr/local/lib/python2.7/dist-packages/falcon_unzip-0.4.0-py2.7.egg/falcon_unzip/unzip.py", line 219, in unzip_all
    wf.refreshTargets() #force refresh now, will put proper dependence later
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 345, in _refreshTargets
    raise Exception(msg)
```
so thinking an issue with 3-unzip/reads

when I take a look at the:
3-unzip/reads/pwatcher.dir\stderr there is:

```sh
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads --heartbeat-file=/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/heartbeats/heartbeat-P950cc2b83cb905 --exit-file=/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/exits/exit-P950cc2b83cb905 --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads', exit_file='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/exits/exit-P950cc2b83cb905', heartbeat_file='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/heartbeats/heartbeat-P950cc2b83cb905', rate=10.0)

cwd:'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads'
hostname=node13.plantsci.internal.cam.ac.uk
heartbeat_fn='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/heartbeats/heartbeat-P950cc2b83cb905'
exit_fn='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/exits/exit-P950cc2b83cb905'
sleep_s=10.0
before setpgid: pid=108768 pgid=108714
 after setpgid: pid=108768 pgid=108768
In cwd: /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads, Blocking call: '/bin/bash run.sh'
export PATH=$PATH:/bin
+ export PATH=/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON_unzip/falcon_unzip:/home/bioinf/se389/FALCON_unzip/src/py_utils:/home/bioinf/se389/FALCON_unzip/src/py_scripts:/home/bioinf/se389/FALCON_unzip:HOME/FALCON-integrate/pypeFLOW/pypeflow:/applications/FALCON_unzip/src/py_scripts:/applications/GenomicConsensus/bin:/home/bioinf/se389/programs/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/usr/local/bin:/usr/bin:/bin:/usr/games::/opt/454/bin:/usr/local/condor/bin:/usr/local/condor/sbin:/bin
+ PATH=/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON_unzip/falcon_unzip:/home/bioinf/se389/FALCON_unzip/src/py_utils:/home/bioinf/se389/FALCON_unzip/src/py_scripts:/home/bioinf/se389/FALCON_unzip:HOME/FALCON-integrate/pypeFLOW/pypeflow:/applications/FALCON_unzip/src/py_scripts:/applications/GenomicConsensus/bin:/home/bioinf/se389/programs/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/usr/local/bin:/usr/bin:/bin:/usr/games::/opt/454/bin:/usr/local/condor/bin:/usr/local/condor/sbin:/bin
cd /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads
+ cd /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads
/bin/bash task.sh
+ /bin/bash task.sh
2018-06-05 14:00:34,592 - root - DEBUG - Running "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/task.json"
2018-06-05 14:00:34,593 - root - DEBUG - Checking existence of '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/task.json' with timeout=30
2018-06-05 14:00:34,594 - root - DEBUG - Loading JSON from '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/task.json'
2018-06-05 14:00:34,596 - root - DEBUG - {u'inputs': {u'falcon_asm_done': u'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/falcon_asm_done'},
 u'outputs': {u'ctg_list_file': u'ctg_list', u'job_done': u'track_reads_done'},
 u'parameters': {u'config': {u'job_queue': u'bash -C ${CMD}',
                             u'job_type': u'string',
                             u'pwatcher_type': u'blocking',
                             u'sge_blasr_aln': u'-pe smp 24',
                             u'sge_hasm': u'-pe smp 48',
                             u'sge_phasing': u'-pe smp 12',
                             u'sge_track_reads': u'-pe smp 12',
                             u'smrt_bin': u'/applications/smrtlink/smrtcmds/bin/',
                             u'unzip_blasr_concurrent_jobs': 40,
                             u'unzip_phasing_concurrent_jobs': 500},
                 u'sge_option': u'-pe smp 12',
                 u'wd': u'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads'},
 u'python_function': u'falcon_unzip.unzip.task_track_reads'}
2018-06-05 14:00:34,596 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads' <- '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads'
2018-06-05 14:00:34,596 - root - DEBUG - Checking existence of u'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/falcon_asm_done' with timeout=30
2018-06-05 14:00:34,596 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads' <- '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads'
2018-06-05 14:00:34,852 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2018-06-05 14:00:34,884 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2018-06-05 14:00:35,085 - pypeflow.do_support - INFO - !/bin/bash -vex /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/track_reads.sh
set -vex
+ set -vex
trap 'touch /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/track_reads_done.exit' EXIT
+ trap 'touch /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/track_reads_done.exit' EXIT
hostname
+ hostname
date
+ date
cd ../..
+ cd ../..
python -m falcon_kit.mains.get_read_ctg_map
+ python -m falcon_kit.mains.get_read_ctg_map
WARNING:pypeflow.simple_pwatcher_bridge:In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/bioinf/se389/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
ERROR:pypeflow.simple_pwatcher_bridge:Task Node(2-asm-falcon/read_maps/dump_pread_ids) failed with exit-code=256
ERROR:pypeflow.simple_pwatcher_bridge:Task Node(2-asm-falcon/read_maps/dump_rawread_ids) failed with exit-code=256
ERROR:pypeflow.simple_pwatcher_bridge:Some tasks are recently_done but not satisfied: set([Node(2-asm-falcon/read_maps/dump_pread_ids), Node(2-asm-falcon/read_maps/dump_rawread_ids)])
ERROR:pypeflow.simple_pwatcher_bridge:ready: set([])
	submitted: set([])
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bioinf/se389/FALCON-integrate/FALCON/falcon_kit/mains/get_read_ctg_map.py", line 107, in <module>
    main()
  File "/home/bioinf/se389/FALCON-integrate/FALCON/falcon_kit/mains/get_read_ctg_map.py", line 103, in main
    pread_dir=pread_dir, asm_dir=asm_dir)
  File "/home/bioinf/se389/FALCON-integrate/FALCON/falcon_kit/mains/get_read_ctg_map.py", line 60, in get_read_ctg_map
    wf.refreshTargets()  # block
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 345, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(2-asm-falcon/read_maps/dump_pread_ids), Node(2-asm-falcon/read_maps/dump_rawread_ids)])
touch /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/track_reads_done.exit
+ touch /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/track_reads_done.exit
2018-06-05 14:00:36,023 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads' -> '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads'
2018-06-05 14:00:36,023 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads' -> '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads'
2018-06-05 14:00:36,024 - root - CRITICAL - Error in /home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 236, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 209, in run_cfg_in_tmpdir
    run_python(python_function_name, myinputs, myoutputs, parameters)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 111, in run_python
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 106, in run_python_func
    do_support.run_bash(script_fn)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/3-unzip/reads/track_reads.sh'

real	0m1.534s
user	0m1.648s
sys	0m7.212s
 returned: 256


so thinking an issue with ERROR:pypeflow.simple_pwatcher_bridge:Task Node(2-asm-falcon/read_maps/dump_pread_ids) failed with exit-code=256

so take a look at:
2-asm-falcon\read_maps\dump_pread_ids\pwatcher.dir\stderr and get:

+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids --heartbeat-file=/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/heartbeats/heartbeat-P22aba84dbc549a --exit-file=/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/exits/exit-P22aba84dbc549a --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids', exit_file='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/exits/exit-P22aba84dbc549a', heartbeat_file='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/heartbeats/heartbeat-P22aba84dbc549a', rate=10.0)

cwd:'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids'
hostname=node13.plantsci.internal.cam.ac.uk
heartbeat_fn='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/heartbeats/heartbeat-P22aba84dbc549a'
exit_fn='/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/mypwatcher/exits/exit-P22aba84dbc549a'
sleep_s=10.0
before setpgid: pid=108885 pgid=108768
 after setpgid: pid=108885 pgid=108885
In cwd: /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids, Blocking call: '/bin/bash run.sh'
export PATH=$PATH:/bin
+ export PATH=/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON_unzip/falcon_unzip:/home/bioinf/se389/FALCON_unzip/src/py_utils:/home/bioinf/se389/FALCON_unzip/src/py_scripts:/home/bioinf/se389/FALCON_unzip:HOME/FALCON-integrate/pypeFLOW/pypeflow:/applications/FALCON_unzip/src/py_scripts:/applications/GenomicConsensus/bin:/home/bioinf/se389/programs/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/usr/local/bin:/usr/bin:/bin:/usr/games::/opt/454/bin:/usr/local/condor/bin:/usr/local/condor/sbin:/bin:/bin
+ PATH=/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/FALCON_unzip/falcon_unzip:/home/bioinf/se389/FALCON_unzip/src/py_utils:/home/bioinf/se389/FALCON_unzip/src/py_scripts:/home/bioinf/se389/FALCON_unzip:HOME/FALCON-integrate/pypeFLOW/pypeflow:/applications/FALCON_unzip/src/py_scripts:/applications/GenomicConsensus/bin:/home/bioinf/se389/programs/bin:/home/bioinf/se389/FALCON-integrate/fc_env/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/home/bioinf/se389/bin:/usr/local/bin:/usr/bin:/bin:/usr/games::/opt/454/bin:/usr/local/condor/bin:/usr/local/condor/sbin:/bin:/bin
cd /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids
+ cd /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids
/bin/bash task.sh
+ /bin/bash task.sh
2018-06-05 14:00:35,831 - root - DEBUG - Running "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids/task.json"
2018-06-05 14:00:35,832 - root - DEBUG - Checking existence of '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids/task.json' with timeout=30
2018-06-05 14:00:35,832 - root - DEBUG - Loading JSON from '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids/task.json'
2018-06-05 14:00:35,833 - root - DEBUG - {u'inputs': {u'pread_db': u'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/1-preads_ovl/preads.db'},
 u'outputs': {u'pread_id_file': u'pread_ids'},
 u'parameters': {},
 u'python_function': u'falcon_kit.pype_tasks.task_dump_pread_ids'}
2018-06-05 14:00:35,833 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids' <- '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids'
2018-06-05 14:00:35,833 - root - DEBUG - Checking existence of u'/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/1-preads_ovl/preads.db' with timeout=30
2018-06-05 14:00:35,834 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids' <- '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids'
2018-06-05 14:00:35,897 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids' -> '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids'
2018-06-05 14:00:35,898 - root - WARNING - CD: '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids' -> '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids'
2018-06-05 14:00:35,898 - root - CRITICAL - Error in /home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/home/bioinf/se389/FALCON-integrate/FALCON-examples/greg200k-sv2.2/test_sha_reads_cell_1_and_2_auto_20_cutoff/2-asm-falcon/read_maps/dump_pread_ids/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 236, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 209, in run_cfg_in_tmpdir
    run_python(python_function_name, myinputs, myoutputs, parameters)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 111, in run_python
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/bioinf/se389/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 103, in run_python_func
    func(self=self)
  File "/home/bioinf/se389/FALCON-integrate/FALCON/falcon_kit/pype_tasks.py", line 556, in task_dump_pread_ids
    input.pread_db = pread_db
AttributeError: 'object' object has no attribute 'pread_db'

real	0m0.166s
user	0m0.076s
sys	0m0.016s
 returned: 256
```

Cant work out why it isnt working - the 1-preads_ovl/preads.db is alive and kicking.

Any help appreciated.

All the best,

Sebastian.

**Comment by pb-cdunn** [comment]
Hmmm. You're looking in the right place, `stderr`. I'm not sure of the problem though....

You seem to be using a commit near this (based on the line number for `pype_tasks.py`):
```
commit 20d77d600b3962459f280d034cddf2a1a72238e7 (HEAD)
Author: Christopher Dunn <cdunn@pacificbiosciences.com>
Date:   Tue Mar 27 09:45:36 2018
```
That uses `falcon_kit/mains/get_read_ctg_map.py` to set up to the call into `pype_tasks.task_dump_pread_ids`. I don't know why that's not working, but I can tell you that we no longer use that executable at all. Try updating to the latest binaries:
* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Configuring-Unzip
