### ISSUE TITLE
[ERROR]Task Node(0-rawreads) failed with exit-code=256

### ISSUE THREAD

**Issue by yhsYhsYhs** [PacificBiosciences/FALCON#645]
**I had run "fc_run.py fc_run_ecoli_local.cfg"on the one dataset and some error occured.**
```
[ERROR]Task Node(0-rawreads) failed with exit-code=256
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
[ERROR]ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/falcon/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 504, in main
    main1(argv[0], args.config, args.logger)
  File "falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 150, in main1
    input_fofn_plf=input_fofn_plf,
  File "falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 216, in run
    wf.refreshTargets([rdb_build_done])
  File "falcon/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "falcon/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
```
> 1. fc_run_ecoli_local.cfg are as following:
```ini
> [General]
> job_type = local
> 
> # list of fasta files
> input_fofn = falcon/FALCON-integrate/FALCON-examples/e.coli/input.fofn
> 
> # input type, raw or pre-assembled reads (preads, error corrected reads)
> input_type = raw
> #input_type = preads
> 
> # The length cutoff used for seed reads used for error correction.
> # "-1" indicates FALCON should calculate the cutoff using
> # the user-defined genome length and coverage cut off
> # otherwise, user can specify length cut off in bp (e.g. 2000)
> length_cutoff = -1
> genome_size = 4641652
> seed_coverage = 20
> 
> # The length cutoff used for overalpping the preassembled reads 
> length_cutoff_pr = 12000
> 
> ## resource usage ##
> # need this line even if running local
> jobqueue = your_queue
> # grid settings for...
> # daligner step of raw reads
> sge_option_da = -pe smp 5 -q %(jobqueue)s
> # las-merging of raw reads
> sge_option_la = -pe smp 20 -q %(jobqueue)s
> # consensus calling for preads
> sge_option_cns = -pe smp 12 -q %(jobqueue)s
> # daligner on preads
> sge_option_pda = -pe smp 6 -q %(jobqueue)s
> # las-merging on preads
> sge_option_pla = -pe smp 16 -q %(jobqueue)s
> # final overlap/assembly 
> sge_option_fc = -pe smp 24 -q %(jobqueue)s
> 
> # job concurrency settings for...
> # all jobs
> default_concurrent_jobs = 30
> # preassembly
> pa_concurrent_jobs = 30
> # consensus calling of preads
> cns_concurrent_jobs = 30
> # overlap detection
> ovlp_concurrent_jobs = 30
> 
> # daligner parameter options for...
> # https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/
> # initial overlap of raw reads
> pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
> # overlap of preads
> ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000
> 
> # parameters for creation of dazzler database of...
> # https://dazzlerblog.wordpress.com/command-guides/dazz_db-command-guide/
> # raw reads
> pa_DBsplit_option = -x500 -s50
> # preads
> ovlp_DBsplit_option = -x500 -s50
> 
>  # settings for consensus calling for preads
> falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
> 
>  # setting for filtering of final overlap of preads
> overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
> 
```

**Comment by pb-cdunn** [comment]
Look in the `0-rawreads` directory for `*stderr`. That should help. And here are the latest config options:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Configuring-Unzip
