### ISSUE TITLE
[Exception: Call 'which samtools' returned 256] on install

### ISSUE THREAD

**Issue by conchoecia** [PacificBiosciences/FALCON#647]
I'm trying to install FALCON via the `install_unzip.sh` script [found via readthedocs](https://pb-falcon.readthedocs.io/en/latest/quick_start.html). I'm trying to install here `/usr/local/bin/falcon-201805` with the command `sudo bash -ex install_unzip_180504.sh /usr/local/bin/falcon-201805`.

However, I consistently get this error about `samtools`, found below. When I run `which samtools` from my user the path is pretty clear: `/usr/local/bin/samtools-1.7/samtools` and I verified that the permissions on samtools has execute for user, group, and other. Ubuntu 16.04.

Any ideas why I'm getting this install error?
```
[INFO]$('which samtools')
[WARNING]Call 'which samtools' returned 256.
Traceback (most recent call last):
  File "/usr/local/bin/falcon-201805/fc_env_180619/bin/fc_unzip.py", line 11, in <module>
    sys.exit(main())
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/mains/start_unzip.py", line 29, in main
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/unzip.py", line 105, in run
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/unzip.py", line 98, in parse_config
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/io.py", line 64, in validate_config
    SEEK_END = 2
  File "/usr/local/bin/falcon-201805/fc_env_180619/local/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'which samtools' returned 256.
```

**Comment by pb-cdunn** [comment]
```
$ samtools --version
samtools 1.6
Using htslib 1.6
Copyright (C) 2017 Genome Research Ltd.
```
* https://github.com/PacificBiosciences/pypeFLOW/blob/cb894bb12a19eba6cdda2a2485bf8a5cbeadda9d/pypeflow/io.py

Line 29 looks fine there. We're simply call `os.system("which samtools")`. Hmmm.
```
    SEEK_END = 2
```
That's weird. `SEEK_END==2` means "relative to the end of the file", which is fine. But why is that printed? I have no idea.

We've never seen this. Maybe you can debug this for us. Maybe run under `strace`?
