### ISSUE TITLE
falcon_unzip failed at 3-unzip/2-htigs/chunk_000***F

### ISSUE THREAD

**Issue by whc2** [PacificBiosciences/FALCON#650]
Hello everyone!

I assembly a genome with 1G genome size using falcon and falcon_unzip. However, falcon_unzip always fails at 7 chunk_000***F in 3-unzip/2-htigs. When I increase the memory and computing resources and run one of these tasks, they still can't finished. I tested many times on both local and SGE cluster, and the unzip task always fails at the same specific subtasks.

```
[Unzip]
input_fofn= input.fofn
input_bam_fofn= input_bams.fofn
input_type = raw

smrt_bin = /vol1/software/pool/smrtlink/my_install/smrtcmds/bin/

[job.defaults]
job_type = local
NPROC=4
njobs=10
pwatcher_type = blocking
submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"
```
Errors in the nohup file:
```
[ERROR]Task Node(3-unzip/2-htigs/chunk_000883F) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/2-htigs/chunk_000883F)])
[ERROR]ready: set([Node(3-unzip/2-htigs/chunk_008979F), Node(3-unzip/2-htigs/chunk_005661F), Node(3-unzip/2-htigs/chunk_004574F), Node(3-un
        submitted: set([Node(3-unzip/2-htigs/chunk_001482F), Node(3-unzip/2-htigs/chunk_000997F), Node(3-unzip/2-htigs/chunk_000007F), Node
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/vol1/software/pool/Python-2.7.9/my_install/bin/fc_unzip.py", line 11, in <module>
    sys.exit(main())
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/start_unzip.py", line 29, in main
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/unzip.py", line 107, in run
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/unzip.py", line 26, in unzip_all
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/tasks/unzip.py", line 445, in run_workflow
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bri
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bri
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/2-htigs/chunk_000883F)])
```
The subtasks' err, 3-unzip/2-htigs/chunk_000819F/run-P91938387a499cb.bash.stdout:
```
[ERROR 2018-06-26 12:44:59] Failure in generate_haplotigs_for_ctg((u'000819F', u'/data1/project/04.falcon/3-unzip/0-phasing/000819F/uow-00/proto', './uow-000819F', u'../../..'))
Traceback (most recent call last):
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 76, in run_generate_haplotigs_for_ctg
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 221, in generate_haplotigs_for_ctg
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 483, in fragment_haplotigs
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 535, in fragment_single_haplotig
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/proto/tiling_path.py", line 165, in convert_split_lines_to_tiling_path
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/proto/tiling_path.py", line 38, in __init__
AssertionError
Traceback (most recent call last):
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/runpy.py", line 162, in _run_module_as_mai
n
    "__main__", fname, loader, pkg_name)
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1454, in <module>
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1450, in main
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1217, in cmd_apply
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 76, in run_generate_haplotigs_for_ctg
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 221, in generate_haplotigs_for_ctg
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 483, in fragment_haplotigs
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 535, in fragment_single_haplotig
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/proto/tiling_path.py", line 165, in convert_split_lines_to_tiling_path
  File "/tmp/pip-install-fZQwcv/falcon-unzip/falcon_unzip/proto/tiling_path.py", line 38, in __init__
AssertionError
2018-06-26 12:45:06,110 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2018-06-26 12:45:06,110 - root - WARNING - CD: '/data1/project/04.falcon/z.new3/3-unzip/2-htigs/chunk_000819F' -> '/data1/project/04.falcon/z.new3/3-unzip/2-htigs/chunk_000819F'
2018-06-26 12:45:06,111 - root - CRITICAL - Error in /vol1/software/pool/Python-2.7.9/my_install/lib/python2
.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/data1/project/04.falcon/z.new3/3-unzip/2-htigs/chunk_000819F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/do_task.py", line 236, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/do_task.py", line 212, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/do_task.py", line 173, in run_bash
    util.system(cmd)
  File "/vol1/software/pool/Python-2.7.9/my_install/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /data1/project/04.falcon/z.new3/3-unzip/2-htigs/chunk_000819F (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real    1m20.682s
user    1m21.997s
sys     0m14.802s
+ finish
+ echo 'finish code: 1'
```

Whenever encounter the 7 error subtasks, the falcon_unzip job is terminated. When I restart the unzip job, the subtasks that can be finished will be finish, but the last 7 subtasks with errors still can't finish. I suppose that these subtasks deal with regions that have very high heterogousity. Please give me any help or suggestion.

The tools versions:
```
falcon-unzip 1.1.1+git.eae3d7539d007377dd996dcf06b8953cdf0f3fe3
falcon-kit 1.2.0+git.0fcc93dc4f743af0cd27e7881546b768631b9b5b
pypeflow 2.0.2+git.cb894bb12a19eba6cdda2a2485bf8a5cbeadda9d
```

Any suggestions are welcome. Thank you very much!

**Comment by pb-cdunn** [comment]
This is fixed in the latest binary release.

**Comment by gbdias** [comment]
I still see the same behavior with:
```
pb-assembly               0.0.1
falcon-unzip              1.1.3
falcon-kit                1.2.3
```

**Comment by pb-cdunn** [comment]
That's way out of date.... Oh, you need a python3 env. Then `conda update --all`.
