### ISSUE TITLE
Assertion error running Falcon unzip

### ISSUE THREAD

**Issue by ghannum** [PacificBiosciences/FALCON#652]
I installed the latest version of Falcon w. Funzip. The assembly went fine, but unzip throws a bunch of errors. I dug into a single folder and ran it manually to extract the following error.

falcon-unzip 1.1.1+git.eae3d7539d007377dd996dcf06b8953cdf0f3fe3
falcon-kit 1.2.0+git.0fcc93dc4f743af0cd27e7881546b768631b9b5b
pypeflow 2.0.2+git.cb894bb12a19eba6cdda2a2485bf8a5cbeadda9d
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/proto/main_augment_pb.py", line 634, in <module>
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/proto/main_augment_pb.py", line 631, in main
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/proto/main_augment_pb.py", line 496, in run
  File "/tmp/pip-install-aGjt1F/falcon-unzip/falcon_unzip/proto/main_augment_pb.py", line 340, in delineate_regions
AssertionError
WARNING:root:Call '/bin/bash user_script.sh' returned 256.

**Comment by ghannum** [comment]
My command is:
> python -m falcon_kit.mains.generic_run_units_of_work --nproc=24 --units-of-work-fn=/blah/falcon/3-unzip/0-phasing/phasing-chunks/000044F/some-units-of-work.json --bash-template-fn=/blah/falcon/3-unzip/0-phasing/phasing-split/bash-template.sh --results-fn=phasing-result-list.json

**Comment by pb-cdunn** [comment]
Not sure. But try with latest binary release. If it recurs, we may request more detail.
