### ISSUE TITLE
Error running Falcon unzip

### ISSUE THREAD

**Issue by ghannum** [PacificBiosciences/FALCON#657]
Some of the 2-htigs chunks fail:

> 3-unzip/2-htigs/chunk_000210F$ bash task.sh
...
...
...
[ERROR 2018-07-24 15:08:37] Failure in generate_haplotigs_for_ctg((u'000210F', u'/mypath/3-unzip/0-phasing/000210F/uow-00/proto', './uow-000210F', u'../../..'))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 76, in run_generate_haplotigs_for_ctg
    return generate_haplotigs_for_ctg(ctg_id, out_dir, unzip_dir, proto_dir, logger)
  File "/usr/local/lib/python2.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 221, in generate_haplotigs_for_ctg
    fragmented_snp_haplotigs = fragment_haplotigs(filtered_snp_haplotigs, aln_dict, clippoints, bubble_tree, fp_proto_log)
  File "/usr/local/lib/python2.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 483, in fragment_haplotigs
    new_haplotigs = fragment_single_haplotig(haplotig, aln, clippoints, bubble_tree, fp_proto_log)
  File "/usr/local/lib/python2.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 535, in fragment_single_haplotig
    tp = tiling_path.convert_split_lines_to_tiling_path(haplotig.path, len(haplotig.seq))
  File "/usr/local/lib/python2.7/site-packages/falcon_unzip/proto/tiling_path.py", line 165, in convert_split_lines_to_tiling_path
    return TilingPath(edges, contig_sequence_len)
  File "/usr/local/lib/python2.7/site-packages/falcon_unzip/proto/tiling_path.py", line 38, in __init__
    assert(contig_sequence_len >= tiling_len)
AssertionError

**Comment by pb-cdunn** [comment]
That should be fixed in the latest tarball.
