### ISSUE TITLE
Exception: Some tasks are recently_done but not satisfied Node0-rawreads/daligner-runs

### ISSUE THREAD

**Issue by aechchiki** [PacificBiosciences/FALCON#660]
Hi, I was trying to run Falcon for a diploid assembly to be fed into falcon-unzip

and the program stopped with:

```
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/daligner-runs/j_01a9)])
```

I looked at the stderr file in the given subfolder (`/scratch/local/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9`): 

```
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9 --heartbeat-file=/tmp/aechchik/falcon_dnr/mypwatcher/heartbeats/heartbeat-P7e83330576cd63 --exit-file=/tmp/aechchik/falcon_dnr/mypwatcher/exits/exit-P7e83330576cd63 --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9', exit_file='/tmp/aechchik/falcon_dnr/mypwatcher/exits/exit-P7e83330576cd63', heartbeat_file='/tmp/aechchik/falcon_dnr/mypwatcher/heartbeats/heartbeat-P7e83330576cd63', rate=10.0)

cwd:'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
hostname=dee-serv06.vital-it.ch
heartbeat_fn='/tmp/aechchik/falcon_dnr/mypwatcher/heartbeats/heartbeat-P7e83330576cd63'
exit_fn='/tmp/aechchik/falcon_dnr/mypwatcher/exits/exit-P7e83330576cd63'
sleep_s=10.0
before setpgid: pid=59087 pgid=36383
 after setpgid: pid=59087 pgid=59087
In cwd: /tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9, Blocking call: '/bin/bash run.sh'
export PATH=$PATH:/bin
+ export PATH=/Home/aechchik/fc_env_180723/bin:/Home/aechchik/fc_env_180723/bin:/mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/etc:/mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/bin:/software/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/aechchik/bin:/bin
+ PATH=/Home/aechchik/fc_env_180723/bin:/Home/aechchik/fc_env_180723/bin:/mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/etc:/mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/bin:/software/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/aechchik/bin:/bin
cd /tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9
+ cd /tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9
/bin/bash task.sh
+ /bin/bash task.sh
2018-07-28 02:53:15,073 - root - DEBUG - Running "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py /tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9/task.json"
2018-07-28 02:53:15,075 - root - DEBUG - Checking existence of '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9/task.json' with timeout=30
2018-07-28 02:53:15,075 - root - DEBUG - Loading JSON from '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9/task.json'
2018-07-28 02:53:15,076 - root - DEBUG - {u'bash_template_fn': u'template.sh',
 u'inputs': {u'bash_template': u'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner_bash_template.sh',
             u'units_of_work': u'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-chunks/j_01a9/some-units-of-work.json'},
 u'outputs': {u'results': u'some-done-files.json'},
 u'parameters': {}}
2018-07-28 02:53:15,076 - root - WARNING - CD: '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9' <- '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
2018-07-28 02:53:15,089 - root - DEBUG - Checking existence of u'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-chunks/j_01a9/some-units-of-work.json' with timeout=30
2018-07-28 02:53:15,089 - root - DEBUG - Checking existence of u'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner_bash_template.sh' with timeout=30
2018-07-28 02:53:15,089 - root - DEBUG - Checking existence of u'template.sh' with timeout=30
2018-07-28 02:53:15,089 - root - WARNING - CD: '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9' <- '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
2018-07-28 02:53:15,090 - root - INFO - $('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
# Substitution will be similar to snakemake "shell".
python -m falcon_kit.mains.generic_run_units_of_work --units-of-work-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-chunks/j_01a9/some-units-of-work.json --bash-template-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner_bash_template.sh --results-fn=some-done-files.json
+ python -m falcon_kit.mains.generic_run_units_of_work --units-of-work-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-chunks/j_01a9/some-units-of-work.json --bash-template-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner_bash_template.sh --results-fn=some-done-files.json
INFO:root:u"Deserializing from '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-chunks/j_01a9/some-units-of-work.json'"
INFO:root:u"  Opened for read: '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-chunks/j_01a9/some-units-of-work.json'"
INFO:root:u'  Read 0.0MB as json'
INFO:root:u'  Deserialized 1 records'
WARNING:root:INPUT:{u'daligner_settings': u'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/settings.json', u'daligner_script': u'/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/daligner-script.sh'}
WARNING:root:OUTPUT:{u'job_done': u'daligner.done'}
WARNING:root:PARAMS:{}
WARNING:root:CD: u'uow-00' <- '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
INFO:root:$('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
# Note: HPC.daligner chooses a merged filename in its generated script, so we will symlink to it.
python -m falcon_kit.mains.daligner --daligner-settings-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/settings.json --daligner-script-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/daligner-script.sh --job-done-fn=daligner.done
+ python -m falcon_kit.mains.daligner --daligner-settings-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/settings.json --daligner-script-fn=/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/daligner-script.sh --job-done-fn=daligner.done
INFO:root:Running daligner from '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/daligner-script.sh' (using '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-split/daligner-scripts/j_01a9/settings.json') to write 'daligner.done'
INFO:root:$(u'bash -vex run_daligner.sh')
module () {  eval `/software/bin/modulecmd bash $*`
}
#!/bin/bash
set -vex
+ set -vex

db_dir=/tmp/aechchik/falcon_dnr/0-rawreads
+ db_dir=/tmp/aechchik/falcon_dnr/0-rawreads
ln -sf ${db_dir}/.raw_reads.bps .
+ ln -sf /tmp/aechchik/falcon_dnr/0-rawreads/.raw_reads.bps .
ln -sf ${db_dir}/.raw_reads.idx .
+ ln -sf /tmp/aechchik/falcon_dnr/0-rawreads/.raw_reads.idx .
ln -sf ${db_dir}/raw_reads.db .
+ ln -sf /tmp/aechchik/falcon_dnr/0-rawreads/raw_reads.db .
ln -sf ${db_dir}/.raw_reads.dust.anno .
+ ln -sf /tmp/aechchik/falcon_dnr/0-rawreads/.raw_reads.dust.anno .
ln -sf ${db_dir}/.raw_reads.dust.data .
+ ln -sf /tmp/aechchik/falcon_dnr/0-rawreads/.raw_reads.dust.data .
rm -f *.las
+ rm -f raw_reads.193.raw_reads.632.C0.las raw_reads.193.raw_reads.632.C1.las raw_reads.193.raw_reads.632.C2.las raw_reads.193.raw_reads.632.C3.las raw_reads.193.raw_reads.632.N0.las raw_reads.193.raw_reads.632.N1.las raw_reads.193.raw_reads.632.N2.las raw_reads.193.raw_reads.632.N3.las raw_reads.194.raw_reads.632.C0.las raw_reads.194.raw_reads.632.C1.las raw_reads.194.raw_reads.632.C2.las raw_reads.194.raw_reads.632.C3.las raw_reads.194.raw_reads.632.N0.las raw_reads.194.raw_reads.632.N1.las raw_reads.194.raw_reads.632.N2.las raw_reads.194.raw_reads.632.N3.las raw_reads.195.raw_reads.632.C0.las raw_reads.195.raw_reads.632.C1.las raw_reads.195.raw_reads.632.C2.las raw_reads.195.raw_reads.632.C3.las raw_reads.195.raw_reads.632.N0.las raw_reads.195.raw_reads.632.N1.las raw_reads.195.raw_reads.632.N2.las raw_reads.195.raw_reads.632.N3.las raw_reads.196.raw_reads.632.C0.las raw_reads.196.raw_reads.632.C1.las raw_reads.196.raw_reads.632.C2.las raw_reads.196.raw_reads.632.C3.las raw_reads.196.raw_reads.632.N0.las raw_reads.196.raw_reads.632.N1.las raw_reads.196.raw_reads.632.N2.las raw_reads.196.raw_reads.632.N3.las raw_reads.632.raw_reads.193.C0.las raw_reads.632.raw_reads.193.C1.las raw_reads.632.raw_reads.193.C2.las raw_reads.632.raw_reads.193.C3.las raw_reads.632.raw_reads.193.N0.las raw_reads.632.raw_reads.193.N1.las raw_reads.632.raw_reads.193.N2.las raw_reads.632.raw_reads.193.N3.las raw_reads.632.raw_reads.194.C0.las raw_reads.632.raw_reads.194.C1.las raw_reads.632.raw_reads.194.C2.las raw_reads.632.raw_reads.194.C3.las raw_reads.632.raw_reads.194.N0.las raw_reads.632.raw_reads.194.N1.las raw_reads.632.raw_reads.194.N2.las raw_reads.632.raw_reads.194.N3.las raw_reads.632.raw_reads.195.C0.las raw_reads.632.raw_reads.195.C1.las raw_reads.632.raw_reads.195.C2.las raw_reads.632.raw_reads.195.C3.las raw_reads.632.raw_reads.195.N0.las raw_reads.632.raw_reads.195.N1.las raw_reads.632.raw_reads.195.N2.las raw_reads.632.raw_reads.195.N3.las raw_reads.632.raw_reads.196.C0.las raw_reads.632.raw_reads.196.C1.las raw_reads.632.raw_reads.196.C2.las raw_reads.632.raw_reads.196.C3.las raw_reads.632.raw_reads.196.N0.las raw_reads.632.raw_reads.196.N1.las raw_reads.632.raw_reads.196.N2.las raw_reads.632.raw_reads.196.N3.las
daligner -v -t16 -H14851 -e0.7 -s1000 -mdust raw_reads.632 raw_reads.193 raw_reads.194 raw_reads.195 raw_reads.196
+ daligner -v -t16 -H14851 -e0.7 -s1000 -mdust raw_reads.632 raw_reads.193 raw_reads.194 raw_reads.195 raw_reads.196
LAcheck -v raw_reads *.las
+ LAcheck -v raw_reads raw_reads.193.raw_reads.632.C0.las raw_reads.193.raw_reads.632.C1.las raw_reads.193.raw_reads.632.C2.las raw_reads.193.raw_reads.632.C3.las raw_reads.193.raw_reads.632.N0.las raw_reads.193.raw_reads.632.N1.las raw_reads.193.raw_reads.632.N2.las raw_reads.193.raw_reads.632.N3.las raw_reads.194.raw_reads.632.C0.las raw_reads.194.raw_reads.632.C1.las raw_reads.194.raw_reads.632.C2.las raw_reads.194.raw_reads.632.C3.las raw_reads.194.raw_reads.632.N0.las raw_reads.194.raw_reads.632.N1.las raw_reads.194.raw_reads.632.N2.las raw_reads.194.raw_reads.632.N3.las raw_reads.195.raw_reads.632.C0.las raw_reads.195.raw_reads.632.C1.las raw_reads.195.raw_reads.632.C2.las raw_reads.195.raw_reads.632.C3.las raw_reads.195.raw_reads.632.N0.las raw_reads.195.raw_reads.632.N1.las raw_reads.195.raw_reads.632.N2.las raw_reads.195.raw_reads.632.N3.las raw_reads.196.raw_reads.632.C0.las raw_reads.196.raw_reads.632.C1.las raw_reads.196.raw_reads.632.C2.las raw_reads.196.raw_reads.632.C3.las raw_reads.196.raw_reads.632.N0.las raw_reads.196.raw_reads.632.N1.las raw_reads.196.raw_reads.632.N2.las raw_reads.196.raw_reads.632.N3.las raw_reads.632.raw_reads.193.C0.las raw_reads.632.raw_reads.193.C1.las raw_reads.632.raw_reads.193.C2.las raw_reads.632.raw_reads.193.C3.las raw_reads.632.raw_reads.193.N0.las raw_reads.632.raw_reads.193.N1.las raw_reads.632.raw_reads.193.N2.las raw_reads.632.raw_reads.193.N3.las raw_reads.632.raw_reads.194.C0.las raw_reads.632.raw_reads.194.C1.las raw_reads.632.raw_reads.194.C2.las raw_reads.632.raw_reads.194.C3.las raw_reads.632.raw_reads.194.N0.las raw_reads.632.raw_reads.194.N1.las raw_reads.632.raw_reads.194.N2.las raw_reads.632.raw_reads.194.N3.las raw_reads.632.raw_reads.195.C0.las raw_reads.632.raw_reads.195.C1.las raw_reads.632.raw_reads.195.C2.las raw_reads.632.raw_reads.195.C3.las raw_reads.632.raw_reads.195.N0.las raw_reads.632.raw_reads.195.N1.las raw_reads.632.raw_reads.195.N2.las raw_reads.632.raw_reads.195.N3.las raw_reads.632.raw_reads.196.C0.las raw_reads.632.raw_reads.196.C1.las raw_reads.632.raw_reads.196.C2.las raw_reads.632.raw_reads.196.C3.las raw_reads.632.raw_reads.196.N0.las raw_reads.632.raw_reads.196.N1.las raw_reads.632.raw_reads.196.N2.las raw_reads.632.raw_reads.196.N3.las
  raw_reads.193.raw_reads.632.C0: 2,268 all OK
  raw_reads.193.raw_reads.632.C1: 820 all OK
  raw_reads.193.raw_reads.632.C2: 1,588 all OK
  raw_reads.193.raw_reads.632.C3: 1,094 all OK
  raw_reads.193.raw_reads.632.N0: 3,002 all OK
  raw_reads.193.raw_reads.632.N1: 764 all OK
  raw_reads.193.raw_reads.632.N2: 1,898 all OK
  raw_reads.193.raw_reads.632.N3: 1,516 all OK
  raw_reads.194.raw_reads.632.C0: 618 all OK
  raw_reads.194.raw_reads.632.C1: 2,640 all OK
  raw_reads.194.raw_reads.632.C2: 1,647 all OK
  raw_reads.194.raw_reads.632.C3: 2,287 all OK
  raw_reads.194.raw_reads.632.N0: 768 all OK
  raw_reads.194.raw_reads.632.N1: 3,375 all OK
  raw_reads.194.raw_reads.632.N2: 1,877 all OK
  raw_reads.194.raw_reads.632.N3: 2,822 all OK
  raw_reads.195.raw_reads.632.C0: 977 all OK
  raw_reads.195.raw_reads.632.C1: 423 all OK
  raw_reads.195.raw_reads.632.C2: 2,234 all OK
  raw_reads.195.raw_reads.632.C3: 2,096 all OK
  raw_reads.195.raw_reads.632.N0: 1,178 all OK
  raw_reads.195.raw_reads.632.N1: 408 all OK
  raw_reads.195.raw_reads.632.N2: 2,891 all OK
  raw_reads.195.raw_reads.632.N3: 2,222 all OK
  raw_reads.196.raw_reads.632.C0: 618 all OK
  raw_reads.196.raw_reads.632.C1: 2,898 all OK
  raw_reads.196.raw_reads.632.C2: 3,110 all OK
  raw_reads.196.raw_reads.632.C3: 601 all OK
  raw_reads.196.raw_reads.632.N0: 618 all OK
  raw_reads.196.raw_reads.632.N1: 3,407 all OK
  raw_reads.196.raw_reads.632.N2: 3,806 all OK
  raw_reads.196.raw_reads.632.N3: 561 all OK
  raw_reads.632.raw_reads.193.C0: 614 all OK
  raw_reads.632.raw_reads.193.C1: 1,405 all OK
  raw_reads.632.raw_reads.193.C2: 662 all OK
  raw_reads.632.raw_reads.193.C3: 912 all OK
  raw_reads.632.raw_reads.193.N0: 1,148 all OK
  raw_reads.632.raw_reads.193.N1: 1,228 all OK
  raw_reads.632.raw_reads.193.N2: 825 all OK
  raw_reads.632.raw_reads.193.N3: 810 all OK
  raw_reads.632.raw_reads.194.C0: 848 all OK
  raw_reads.632.raw_reads.194.C1: 981 all OK
  raw_reads.632.raw_reads.194.C2: 769 all OK
  raw_reads.632.raw_reads.194.C3: 975 all OK
  raw_reads.632.raw_reads.194.N0: 1,073 all OK
  raw_reads.632.raw_reads.194.N1: 1,038 all OK
  raw_reads.632.raw_reads.194.N2: 1,557 all OK
  raw_reads.632.raw_reads.194.N3: 1,212 all OK
  raw_reads.632.raw_reads.195.C0: 769 all OK
  raw_reads.632.raw_reads.195.C1: 842 all OK
  raw_reads.632.raw_reads.195.C2: 1,153 all OK
  raw_reads.632.raw_reads.195.C3: 974 all OK
  raw_reads.632.raw_reads.195.N0: 1,146 all OK
  raw_reads.632.raw_reads.195.N1: Duplicate overlap (3421964 vs 1056815)
  raw_reads.632.raw_reads.195.N2: 1,067 all OK
  raw_reads.632.raw_reads.195.N3: 1,109 all OK
  raw_reads.632.raw_reads.196.C0: 757 all OK
  raw_reads.632.raw_reads.196.C1: 1,089 all OK
  raw_reads.632.raw_reads.196.C2: 1,212 all OK
  raw_reads.632.raw_reads.196.C3: 569 all OK
  raw_reads.632.raw_reads.196.N0: 1,134 all OK
  raw_reads.632.raw_reads.196.N1: 1,004 all OK
  raw_reads.632.raw_reads.196.N2: 1,174 all OK
  raw_reads.632.raw_reads.196.N3: 807 all OK
WARNING:root:Call u'bash -vex run_daligner.sh' returned 256.
Traceback (most recent call last):
  File "/software/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/falcon_kit/mains/daligner.py", line 59, in <module>
    main()
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/falcon_kit/mains/daligner.py", line 55, in main
    run(**vars(args))
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/falcon_kit/mains/daligner.py", line 21, in run
    io.syscall('bash -vex {}'.format(script_fn))
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call u'bash -vex run_daligner.sh' returned 256.
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: u'uow-00' -> '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
Traceback (most recent call last):
  File "/software/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 95, in <module>
    main()
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 91, in main
    run(**vars(args))
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 49, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py", line 173, in run_bash
    util.system(cmd)
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2018-07-28 02:56:54,163 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2018-07-28 02:56:54,163 - root - WARNING - CD: '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9' -> '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
2018-07-28 02:56:54,164 - root - WARNING - CD: '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9' -> '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9'
2018-07-28 02:56:54,164 - root - CRITICAL - Error in /Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/tmp/aechchik/falcon_dnr/0-rawreads/daligner-runs/j_01a9/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/software/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py", line 236, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py", line 212, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/do_task.py", line 173, in run_bash
    util.system(cmd)
  File "/Home/aechchik/fc_env_180723/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.

real	3m39.328s
user	4m21.051s
sys	0m31.885s
 returned: 256
```

Any idea on how can I fix this?

Thanks
Amina

**Comment by pb-cdunn** [comment]
We have not seen any `.las` file errors with the versions of the tools in the latest tarball. Which tarball are you using?

**Comment by pb-cdunn** [comment]
(You cannot upgrade in the middle. You might need to re-run your whole assembly. You need the version in `daligner` in our tarball.)

**Comment by aechchiki** [comment]
thanks for the reply @pb-cdunn 
it's the tarball '3/12/2018', name: 'install_unzip.sh' (from: https://pb-falcon.readthedocs.io/en/latest/quick_start.html)

**Comment by pb-cdunn** [comment]
Well, the first thing to do is:
* Open a new shell.
* Install the latest tarball something.
* For a given bad `.las` file, go to the directory where it was created.
* Run `daligner` from latest tarball to reproduce that `.las` file. (If possible, run in a new directory.)
* Try `LAcheck` on that new `.las`.

If it's still a bad `.las` file, I would then request the input data so that we can reproduce the problem. If we are able to reproduce it using the standard `daligner` (rather than our fork of Gene Myers' code), then we would submit a bug report to thegenemyers.

**Comment by aechchiki** [comment]
thanks, sorry.
