### ISSUE TITLE
Unable to complete Falcon test run: fc_run fails to parse config file

### ISSUE THREAD

**Issue by ggstatgen** [PacificBiosciences/FALCON#661]
Hi,

Thanks for developing Falcon! I'm pretty new to it and have just managed to install it via binary zip. I've got a miniconda python 2.7.9 local installation, and followed the installation tutorial here

[https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries](url)

to unzip the tarball in my miniconda /bin and /lib files. I've added the paths to the environmental variables as required, and checked prerequisite software is present  (samtools, mummer, minimap2) which it is.

I'm now testing my installation with an example run. This unfortunately fails almost immediately, with the following error dump

command is:
`fc_run fc_run.cfg`

output is

```
falcon-kit 1.2.1+git.2d47201ed4926c8ee625ad251a49d00cad64efc0                                                                           
pypeflow 2.0.3+git.ba1caa2601daef1c8ee41508ba9c9f78a8879666
[INFO]Setup logging from file "None".                                                                                                              
[INFO]$ lfs setstripe -c 12 /project/assembly_FALCON >
[INFO]Apparently '/project/assembly_FALCON' is not in lustre filesystem, which is fine.                                      
[INFO]fc_run started with configuration fc_run_3.cfg
[ERROR]Failed to parse config "fc_run_3.cfg".                                                                                                            
Traceback (most recent call last):  
  File "/project//CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 52, in main1                     
    config = run_support.parse_cfg_file(input_config_fn)
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 154, in parse_cfg_file
    update_defaults(config['General'])
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 389, in update_defaults
    clean_falcon_options(cfg)
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 115, in clean_falcon_options
    check_HPCdaligner_option(fc[dk])
  File "/project/mouse_modifier_bkp/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 102, in check_HPCdaligner_option
    raise Exception(msg)
Exception: HPC.daligner option "-dal" has changed to "-B".

Traceback (most recent call last):
  File "/project/CODE/miniconda3/envs/Falcon/bin/fc_run", line 11, in <module>
    sys.exit(main())
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 730, in main
    main1(argv[0], args.config, args.logger)
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 52, in main1
    config = run_support.parse_cfg_file(input_config_fn)
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 154, in parse_cfg_file
    update_defaults(config['General'])
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 389, in update_defaults
    clean_falcon_options(cfg)
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 115, in clean_falcon_options
    check_HPCdaligner_option(fc[dk])
  File "/project/CODE/miniconda3/envs/Falcon/lib/python2.7/site-packages/falcon_kit/run_support.py", line 102, in check_HPCdaligner_option
    raise Exception(msg)
Exception: HPC.daligner option "-dal" has changed to "-B".
```

My `fc_run.cfg` file is the following
```
[General]
# list of files of the initial subread fasta files
input_fofn = input.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -dal4 -M32 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -M32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

# error correction consensus options
falcon_sense_option = --output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 6

# overlap filtering options
overlap_filtering_setting = --max-diff 100 --max-cov 100 --min-cov 20 --bestn 10
[job.defaults]
pwatcher_type = blocking
submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"
njobs = 32

[job.step.da]
NPROC = 8
# Daligner needs only 4 procs per job, but since we set `-M32`, we need 32GB per job. If
# your Grid has roughly 4GB per processor, then we want to reserve 8 processors, in order to
# reserve 8GB*4==32GB of RAM per job.

[job.step.la]
NPROC = 2

[job.step.pda]
NPROC = 8

[job.step.pla]
NPROC = 2

[job.step.cns]
NPROC = 6 # also to pass --n-core=6 to falcon_sense

[job.step.asm]
NPROC = 24 # also to pass --n-core=24 to ovlp_filter
'''

where `input.fofn` is a text file containing paths to three bacterial fasta files extracted from the FALCON/examples project.

What am I doing wrong? Thanks!

**Comment by pb-cdunn** [comment]
* https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/

pa_HPCdaligner_option =  -v ~-dal4~ -M32 -e.70 -l1000 -s1000

ovlp_HPCdaligner_option = -v ~~-dal4~~ -M32 -h60 -e.96 -l500 -s1000

```ini
pa_HPCdaligner_option =  -v -B4 -M32 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -M32 -h60 -e.96 -l500 -s1000
```

And if you're using the latest binary release, you are better off putting most of that into
```ini
pa_daligner_option =   -v -e.70 -l1000 -s1000 -M32
ovlp_daligner_option = -v -e.96  -l500 -s1000 -h60
pa_HPCdaligner_option =  -B4
ovlp_HPCdaligner_option = -B4
```
That way, TANmask and REPmask will get proper values also.

**Comment by amnag** [comment]
> * https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/
> 
> pa_HPCdaligner_option = -v -dal4 -M32 -e.70 -l1000 -s1000
> 
> ovlp_HPCdaligner_option = -v -dal4 -M32 -h60 -e.96 -l500 -s1000
> 
> ```ini
> pa_HPCdaligner_option =  -v -B4 -M32 -e.70 -l1000 -s1000
> ovlp_HPCdaligner_option = -v -B4 -M32 -h60 -e.96 -l500 -s1000
> ```
> 
> And if you're using the latest binary release, you are better off putting most of that into
> 
> ```ini
> pa_daligner_option =   -v -e.70 -l1000 -s1000 -M32
> ovlp_daligner_option = -v -e.96  -l500 -s1000 -h60
> pa_HPCdaligner_option =  -B4
> ovlp_HPCdaligner_option = -B4
> ```
> 
> That way, TANmask and REPmask will get proper values also.

Hi @pb-cdunn ,
which set of input parameters is more appropriate for assembling a genome comparable in size to the human genome ?

pa_daligner_option =  -e.70 -l1200 -s100 -k14 -h256 -w8
ovlp_daligner_option = -h600 -e.96 -l1800 -s100 -k24

pa_HPCdaligner_option =  -v -B128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B128 -t32 -h60 -e.96 -l500 -s1000

or

pa_daligner_option = -v  -e.70 -l1000 -s1000 -M32
ovlp_daligner_option = -v -e.96 -l500 -s1000 -h60

pa_HPCdaligner_option =  -B128
ovlp_HPCdaligner_option = -B128

Also are the -l and -s values for pa_daligner_option superseded by the corresponding values for pa_HPCdaligner_option ? What is the difference between these two parameters - pa_daligner_option and pa_HPCdaligner_option ?

Your help is much appreciated.
Thanks,
@amnag
