### ISSUE TITLE
MissingLas: 76728 is not a perfect square. We must be missing some .las files.

### ISSUE THREAD

**Issue by roylejw** [PacificBiosciences/FALCON#662]
Hi there,

I don't seem to be able to find a similar issue posted yet.

At the daligner-combine stage of my 1-preads_ovl FALCON run I am getting the following:

```
[INFO]Not enough .las found from '/lustre/home-lustre/n8401888/falcon_native/1-preads_ovl/daligner-gathered/gathered-done-files.json'. Sleeping 20 seconds before retrying.
Traceback (most recent call last):
  File "/home/n8401888/bin/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/n8401888/bin/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/lustre/home-lustre/n8401888/bin/falcon_assembler/fc_env_180726/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 980, in <module>
    main()
  File "/lustre/home-lustre/n8401888/bin/falcon_assembler/fc_env_180726/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 976, in main
    args.func(args)
  File "/lustre/home-lustre/n8401888/bin/falcon_assembler/fc_env_180726/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 676, in cmd_daligner_combine
    daligner_combine(args.db_fn, args.gathered_fn, args.las_paths_fn)
  File "/lustre/home-lustre/n8401888/bin/falcon_assembler/fc_env_180726/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 482, in daligner_combine
    las_paths = find_las_paths()
  File "/lustre/home-lustre/n8401888/bin/falcon_assembler/fc_env_180726/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 475, in find_las_paths
    raise MissingLas(msg)
__main__.MissingLas: 76728 is not a perfect square. We must be missing some .las files.
```

Trawling through the daligner runs of the preads every job has finished with .las files, and has a run.sh.done file associated. Is there any way to determine how or why this error is occuring? 

Cheers,
Jack

**Comment by pb-cdunn** [comment]
You have old code. We dropped that check in
```
commit c7d6b13fb8f39b107cb8652428396b9af7bc0612
Author: Christopher Dunn <cdunn@pacificbiosciences.com>
Date:   Mon May 21 17:12:20 2018
```
You can try a recent binary from https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries, or if you're intrepid, you can try `conda install pb-assembly`. (That works, but it's not a stable release yet, so we might over-write.)
