### ISSUE TITLE
help with SLURM config for fs_based, sbatch

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/FALCON#664]
Hello. We've been successfully running falcon/1.8.8 with SLURM in production, and I'm trying to convert our config to use the new config options so we can upgrade to falcon/2.1.4.  However, my test seems to die when it tries to submit the SLURM job and I can't decipher the stderr.  Since the job wasn't successfully submitted, the task itself does not have stderr, just the overall stderr for fc_run.

And here is what I'm trying to run with falcon/2.1.4:
```ini
[job.defaults]
njobs=8
job_type = SLURM
pwatcher_type = fs_based

submit = sbatch --exclusive --mem=100G -t 12:00:00 -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}`
```
tail of all.log:
```
2018-08-23 04:10:20,824 - pwatcher.fs_based:218 - DEBUG - Writing wrapper "/assembly/slurm20180822_4/mypwatcher/wrappers/run-Pf7876f438a5e73.bash"
2018-08-23 04:10:20,824 - pwatcher.fs_based:441 - INFO -  starting job Job(jobid='Pf7876f438a5e73', cmd='/bin/bash run.sh', rundir='/assembly/slurm20180822_4/0-rawreads', options={'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'SLURM', 'submit': 'sbatch --exclusive --mem=100G -t 12:00:00 -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}', 'NPROC': 1, 'njobs': '8'}) w/ job_type=SLURM
2018-08-23 04:10:20,824 - pwatcher.fs_based:655 - DEBUG - delete(which='known', jobids=<0>)
2018-08-23 04:10:20,824 - pwatcher.fs_based:617 - DEBUG - Deleting jobs for jobids from known ([])
2018-08-23 04:10:20,824 - pypeflow.simple_pwatcher_bridge:189 - DEBUG - In notifyTerminate(), result of delete:None
```

and stderr:
```
[INFO]About to submit: Node(0-rawreads)
[INFO] starting job Job(jobid='Pf7876f438a5e73', cmd='/bin/bash run.sh', rundir=
'/assembly/slurm20180822_4/0-rawreads', options={'pwatcher_type': 'fs_based', 'use_tm
pdir': False, 'MB': 4000, 'job_type': 'SLURM', 'submit': 'sbatch --exclusive --m
em=100G -t 12:00:00 -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}', 'NPROC': 1, 'njobs': '8'}) w/ job_type=SLURM
Traceback (most recent call last):
  File "/assemblers/falcon/2.1.4/fc_env/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run.py')()
  File "/assemblers/falcon/2.1.4/FALCON/falcon_kit/mains/run1.py", line 626, in main
    main1(argv[0], args.config, args.logger)
  File "/assemblers/falcon/2.1.4/FALCON/falcon_kit/mains/run1.py", line 153, in main1
    input_fofn_plf=input_fofn_plf,
  File "/assemblers/falcon/2.1.4/FALCON/falcon_kit/mains/run1.py", line 261, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
 File "/assemblers/falcon/2.1.4/FALCON/falcon_kit/pype.py", line 96, in gen_parallel_tasks
    wf.refreshTargets()
  File "/assemblers/falcon/2.1.4/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/assemblers/falcon/2.1.4/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 313, in _refreshTargets
    unsubmitted = set(self.tq.enque(to_submit)) # In theory, this traps exceptions.
  File "/assemblers/falcon/2.1.4/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 152, in enque
    result = self.watcher.run(**watcher_args)
  File "/assemblers/falcon/2.1.4/pypeFLOW/pwatcher/fs_based.py", line 648, in run
    return cmd_run(self.state, jobids, job_type, job_defaults_dict)
  File "/assemblers/falcon/2.1.4/pypeFLOW/pwatcher/fs_based.py", line 451, in cmd_run
    bjob = MetaJobSlurm(mjob)
  File "/assemblers/falcon/2.1.4/pypeFLOW/pwatcher/fs_based.py", line 396, in __init__
    super(MetaJobSlurm, self).__init__(mjob)
TypeError: object.__init__() takes no parameters
```

**Comment by pb-cdunn** [comment]
Try the `develop` branch of **pypeFLOW**.

It takes a lot of time to build a new tarball, but the problem is strictly in pypeFLOW.

If you are able to find a way to use Slurm with blocking calls, please try `pwatcher_type=blocking`. The filesystem-based process-watcher is very difficult to maintain, as we cannot most systems.

**Comment by jasmynp** [comment]
I wasn't sure if the 2.1.4 is out of date, so I downloaded the latest binaries (2018.08.08-21.41) and installed it.  Same error -- it fails to get past the function that should submit the SLURM job.  Any chance this is a bug?

**Comment by pb-cdunn** [comment]
Yes, you need the bug-fix on the pypeflow `develop` branch. That is not in a tarball yet, but you can use `PYTHONPATH` to override the version in the tarball. If it works for you, I'll try to update the tarball. That would hopefully be the last update, as we are switching to Bioconda for these unofficial (but useful) releases.

In general, I *strongly* suggest using `pwatcher_type=blocking`. We cannot test most job-submission systems, so `pwatcher_type=fs_base` is very difficult to support.

**Comment by jasmynp** [comment]
Thanks. I tried pwatcher=blocking first but had issues so tried fs_based next (what we currently use with the older falcon).  I'll try blocking again and test your other suggestions and get back to you.    We are preparing for your bioconda release but need to test the latest unzip in the meantime, so trying to get this working for now in production.  Keep you posted.

**Comment by pb-cdunn** [comment]
For Slurm blocking calls, I think you need `srun --wait=0 ...`

You need to experiment with the blocking srun call from your command-line *first*, before you try falcon at all. (Submit `echo hello world` as the job.) When you have it working, then you know what to use for the submission string.

**Comment by jasmynp** [comment]
Hi Chris,

I am waiting to hear from our compute consultants about srun on our systems.  In the meantime, I am testing the develop version of pypeFLOW and the error seems similar, only moved down one line in the code maybe...can you take a peek?

stderr:
`....  
File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 453, in cmd_run
    bjob = MetaJobSlurm(mjob)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 398, in __init__
    super(MetaJobSlurm, self).__init__(mjob)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 366, in __init__
    assert self.kill_template
AttributeError: 'MetaJobSlurm' object has no attribute 'kill_template'`

all.log:
`2018-08-27 20:43:08,214 - pwatcher.fs_based:218 - DEBUG - Writing wrapper "/20180827_pypeFLOW_dev/mypwatcher/wrappers/run-P793c6187be733f.bash"
2018-08-27 20:43:08,217 - pwatcher.fs_based:443 - INFO -  starting job Job(jobid='P793c6187be733f', cmd='/bin/bash run.sh', rundir='/20180827_pypeFLOW_dev/0-rawreads/build', options={'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'SLURM', 'submit': 'sbatch --exclusive --mem=100G -t 12:00:00 -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}', 'NPROC': 1, 'njobs': '8'}) w/ job_type=SLURM
2018-08-27 20:43:08,217 - pwatcher.fs_based:657 - DEBUG - delete(which='known', jobids=<0>)
2018-08-27 20:43:08,217 - pwatcher.fs_based:619 - DEBUG - Deleting jobs for jobids from known ([])
2018-08-27 20:43:08,217 - pypeflow.simple_pwatcher_bridge:189 - DEBUG - In notifyTerminate(), result of delete:None`

**Comment by pb-cdunn** [comment]
@jasmynp , [fixed](https://github.com/PacificBiosciences/pypeFLOW/commit/85c6d6e8b70145daa600bb29b3b4e3a32e1d3735). Try again with the tip of `develop` in **pypeFLOW**.

**Comment by jasmynp** [comment]
Hi @pb-cdunn ,  Almost there, there was still one more error, and I think I found the fix.

```
2018-08-28 19:44:16,276 - pwatcher.fs_based:464 - ERROR - In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSlurm(MetaJob(job=Job(jobid='Pe73b35c9c4ddb0', cmd='/bin/bash run.sh', rundir='/global/projectb/scratch/jasmynp/fungal_std/rqc_tests/falcon_2_1_4/20180828_pypeFLOW_dev/fs_based/0-rawreads/build', options={'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'SLURM', 'submit': 'sbatch --exclusive --mem=100G -t 12:00:00 -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}', 'NPROC': 1, 'njobs': '8'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 460, in cmd_run
    state.submit_background(bjob)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 120, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 322, in submit
    mapping['JOB_OPTS'] = self.sub(mapping['JOB_OPTS'], mapping)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/pwatcher/fs_based.py", line 340, in sub
    return string.Template(unsub).substitute(mapping)
  File "/miniconda/miniconda2/envs/qaqc2/lib/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
  File "/miniconda/miniconda2/envs/qaqc2/lib/python2.7/string.py", line 166, in convert
    val = mapping[named]
KeyError: 'JOB_QUEUE'
```

In the code, even though JOB_OPTS is commented out in the mapping dict on line 307, the code still seems to go to the "if 'JOB_OPTS' in mapping:" conditional on lines 320-322.  If I comment this out, then fs_based.py works.

Also, it looks like blocking mode with srun is working for me now, but I'm comparing the two methods for run times and stability.

I'm encountering an issue with tan-runs now but I'll put it in a separate ticket.

**Comment by pb-cdunn** [comment]
Thanks. I'll fix that bug right away.

Btw, we do accept pull-requests for pypeflow. I know the long delay in response can annoy a user, but you can test changes easier than we can.

> Also, it looks like blocking mode with srun is working for me now.

Great! That helps a ton.

> I'm encountering an issue with tan-runs now but I'll put it in a separate ticket.

I saw that. I'm afraid that could require more attention. It's working for us locally, but you might need the very latest code for both pypeflow *and* falcon, which management has decided not to push anymore. When we figure out the exact cause or error, we can maybe release another tarball.

**Comment by jasmynp** [comment]
@pb-cdunn thanks for the pypeflow fix.  Noted on the future pull requests for bug fixes I see.

Please keep me posted on a fix for the tan-runs issue.  I'm trying to get a stable version running here so we can run the later version of unzip in production. 

Thanks.

**Comment by pb-cdunn** [comment]
If you cannot submit a pull-request, could you post your diffs for the JOB_QUEUE bug?

**Comment by pb-cdunn** [comment]
I *think* it's sort of your bug. You have `JOB_QUEUE` interpolation in your job settings, but you have not defined it. Could you post your current `.cfg`?

```
JOB_OPTS = '-q ${JOB_QUEUE} -pe smp ${NPROC}'
```
That is the default. You can override that with `JOB_OPTS=''`, or you can provide `JOB_QUEUE` in your `.cfg`.

**Comment by jasmynp** [comment]
Yes, I was wondering if one way to fix was to define `JOB_QUEUE` but I hadn't defined it in the past with the falcon/1.8.8 release so didn't know if it was a mandatory parameter.  I think for unzip, I defined it as blank to get it to work `JOB_QUEUE=`  I don't usually define the queue when I submit my job, but I can if it is necessary. This is my config:

````
[job.defaults]
njobs=8
job_type = SLURM
pwatcher_type = fs_based

\#sbatch
submit =sbatch --exclusive --mem=100G -t 12:00:00 -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}

\# new 20180824
pa_daligner_option =  -e.70 -l1000 -s1000
ovlp_daligner_option = -e.96  -l500 -s1000 -h60
pa_HPCdaligner_option =  -v -B4 -M100
ovlp_HPCdaligner_option = -v -B4 -M100

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

\# error correction consensus option
falcon_sense_option = --output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 6

\# overlap filtering options
overlap_filtering_setting = --max-diff 100 --max-cov 100 --min-cov 5 --bestn 10

\# might not be needed anymore with latest binaries but doesn't complain
skip_checks = true
```
`


Arghs sorry for the formatting issues. You get the jist.

**Comment by pb-cdunn** [comment]
Well, instead of defining `JOB_QUEUE`, you could provide your own `JOB_OPTS`.

The fs_based stuff is just a lot more complicated, and much harder to maintain.
