### ISSUE TITLE
tan-runs cannot find build/raw_reads.db under tan-chunks

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/FALCON#666]
My latest binary runs fails in tan-runs.  Looking at the stderr under tan-00* subdir, it is looking for a build/raw_reads.db under tan-chunks that does not exist:

```py
INFO]ln -sf ../../tan-chunks/build/raw_reads.db raw_reads.db
Traceback (most recent call last):
  File "/miniconda/miniconda2/envs/qaqc2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/miniconda/miniconda2/envs/qaqc2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1357, 
in <module>
    main()
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1353, 
in main
    args.func(args)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 923, i
n cmd_tan_apply
    tan_apply(args.db_fn, args.script_fn, args.job_done_fn)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 323, in tan_apply
    db = symlink_db(db_fn)
  File "/falcon/falcon-2018.08.08-21.41/fc_env_180824/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 232, in symlink_db
    all_basenames = os.listdir(db_dirname)
OSError: [Errno 2] No such file or directory: '../../tan-chunks/build'
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
```

The build/raw_reads.db is located in the top-level 0-rawreads and the rawreads.db is symlinked under tan-split subdir.  I'm guessing it needs to symlink the build dir under tan-chunks or link directly from 0-rawreads?

Thanks.

**Comment by pb-cdunn** [comment]
What version of pypeflow/falcon_kit? (You should see falcon_kit and pypeflow version strings in stderr.)

**Comment by jasmynp** [comment]
I hope this is correct:
falcon-kit 1.2.2+git.00e8272b663d32a0962ae92ab92324a3b3eb4b46

I couldn't find the pypeflow version string in stderr.  Where is it printed in?  I'm using the develop version that you requested I try out.  Same issue whether I use fs_based or blocking.

**Comment by jasmynp** [comment]
I see someone else's stderr that reports the pypeflow version below it.  But mine doesn't.  Not sure why.

**Comment by pb-cdunn** [comment]
```
commit 00e8272b663d32a0962ae92ab92324a3b3eb4b46
Merge: b72db27 6b1ac0b
Author: Christopher Dunn <cdunn@pacificbiosciences.com>
Date:   Thu Aug 2 20:59:37 2018
```
I'm not sure if there was a bug there, but since there is already a new tarball, you might have better luck with that.
