### ISSUE TITLE
Job Failure Initial Steps

### ISSUE THREAD

**Issue by mbcouger** [PacificBiosciences/FALCON#692]
Hello I got the following errors when trying to run a falcon job. I have attached this error log and my cfg script, is it something with the setup or instalattion of Falcon. I am wanting to run a falcon unzip job locally I had a hard time finding a current cfg file for this. 

Many Thanks
Log:
[INFO]pid=155403 pgid=155392 sub-pid=155408
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pb6624bc67b4862', cmd='/bin/bash run.sh', rundir='/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/build', options={'pwatcher_type': 'fs_based', 'njobs': 30, 'job_type': 'local', 'use_tmpdir': False, 'NPROC': 1, 'MB': 4000}), lang_exe='/bin/bash'))
[INFO](slept for another 0.0s -- another 1 loop iterations)
[INFO](slept for another 0.30000000000000004s -- another 2 loop iterations)
[INFO](slept for another 1.2000000000000002s -- another 3 loop iterations)
[INFO](slept for another 2.9999999999999996s -- another 4 loop iterations)
[INFO](slept for another 6.0s -- another 5 loop iterations)
[INFO](slept for another 10.500000000000002s -- another 6 loop iterations)
[INFO](slept for another 16.800000000000004s -- another 7 loop iterations)
[INFO](slept for another 25.20000000000001s -- another 8 loop iterations)
[INFO](slept for another 36.000000000000014s -- another 9 loop iterations)
[INFO](slept for another 49.499999999999986s -- another 10 loop iterations)
[INFO](slept for another 65.99999999999994s -- another 11 loop iterations)
[INFO](slept for another 85.7999999999999s -- another 12 loop iterations)
[INFO](slept for another 109.19999999999983s -- another 13 loop iterations)
[INFO](slept for another 135.5999999999998s -- another 14 loop iterations)
[INFO](slept for another 150.0s -- another 15 loop iterations)
[INFO](slept for another 160.0s -- another 16 loop iterations)
[INFO](slept for another 170.0s -- another 17 loop iterations)
[INFO](slept for another 180.0s -- another 18 loop iterations)
[INFO](slept for another 190.0s -- another 19 loop iterations)
[INFO](slept for another 200.0s -- another 20 loop iterations)
[ERROR]Task Node(0-rawreads/build) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: {Node(0-rawreads/build)}
[ERROR]ready: set()
	submitted: set()
[ERROR]Failed to kill job for heartbeat 'heartbeat-Pb6624bc67b4862' (which might mean it was already gone): FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(0-rawreads/build)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/pwatcher/fs_based.py", line 611, in delete_heartbeat
    bjob.kill(state, heartbeat)
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/pwatcher/fs_based.py", line 273, in kill
    with open(heartbeat_fn) as ifs:
FileNotFoundError: [Errno 2] No such file or directory: '/pylon5/mc3v0jp/mbcouger/FalconMale/mypwatcher/heartbeats/heartbeat-Pb6624bc67b4862'
Traceback (most recent call last):
  File "/home/mbcouger/.conda/envs/denovo_asm1/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.5.2', 'console_scripts', 'fc_run')()
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 235, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/falcon_kit/pype.py", line 109, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/mbcouger/.conda/envs/denovo_asm1/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(0-rawreads/build)}

CFG
[fc_llocal.txt](https://github.com/PacificBiosciences/FALCON/files/3628468/fc_llocal.txt)

**Comment by mbcouger** [comment]
Hey I think I got it working. Will give an udpate if I encounter any more errors. Many Thanks

**Comment by mbcouger** [comment]
I am now getting the following errors with the configure file attached, any thoughts? Also it was unclear rather the reads could be Fastq. 
[FCLocal.cfg.txt](https://github.com/PacificBiosciences/FALCON/files/3628897/FCLocal.cfg.txt)

**Comment by mbcouger** [comment]
Here are the errors 
[INFO]<--""
   Level NOTSET so inherits level NOTSET
   Handler Stream <open file '<stderr>', mode 'w' at 0x7f6f3bcd41e0>
     Level INFO
     Formatter fmt='[%(levelname)s]%(message)s' datefmt=None
   |
   o<--"falcon_kit"
   |   Level NOTSET so inherits level NOTSET
   |   Handler File '/pylon5/mc3v0jp/mbcouger/FalconMale/fc.log'
   |     Level DEBUG
   |     Formatter fmt='%(asctime)s - %(name)s - %(levelname)s - %(message)s' datefmt=None
   |
   o<--"fc_run"
   |   Level NOTSET so inherits level NOTSET
   |
   o<--"pypeflow"
   |   Level DEBUG
   |   Handler File '/pylon5/mc3v0jp/mbcouger/FalconMale/pypeflow.log'
   |     Level DEBUG
   |     Formatter fmt='%(asctime)s - %(name)s - %(levelname)s - %(message)s' datefmt=None
   |   |
   |   o<--"pypeflow.controller"
   |   |   Level NOTSET so inherits level DEBUG
   |   |
   |   o<--"pypeflow.data"
   |   |   Level NOTSET so inherits level DEBUG
   |   |
   |   o<--"pypeflow.task"
   |       Level NOTSET so inherits level DEBUG
   |
   o<--"rdflib"
       Level NOTSET so inherits level NOTSET
       |
       o<--"rdflib.graph"
       |   Level NOTSET so inherits level NOTSET
       |
       o<--"rdflib.namespace"
       |   Level NOTSET so inherits level NOTSET
       |
       o<--"rdflib.term"
           Level NOTSET so inherits level NOTSET

[INFO]fc_run started with configuration FCArablocal.cfg
[INFO] No target specified, assuming "assembly" as target 
/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:287: UserWarning: Unexpected keys in input config: set(['pa_daligner_option', 'ovlp_daligner_option'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0
[INFO]Queued 'task:///opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_make_fofn_abs_raw' ...
[INFO]Running task from function task_make_fofn_abs_raw()
[INFO]tick: 2, #updatedTasks: 1
[INFO]tick: 4, #updatedTasks: 1
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0
[INFO]Running task from function task_build_rdb()
[INFO]Queued 'task:///opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb' ...
[INFO]tick: 2, #updatedTasks: 1
[INFO]tick: 4, #updatedTasks: 1
[INFO](local) '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh'
[WARNING]Call 'bash /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh 1> /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh.log 2>&1' returned 256.
[ERROR]Contents of '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh.log':
cd /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads
+ cd /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads
trap 'touch /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/rdb_build_done.exit' EXIT
+ trap 'touch /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/rdb_build_done.exit' EXIT
ls -il prepare_rdb.sub.sh
+ ls -il prepare_rdb.sub.sh
144121055705924219 -rwxr-xr-x 1 mbcouger mc3v0jp 465 Sep 18 20:53 prepare_rdb.sub.sh
hostname
+ hostname
l009.pvt.bridges.psc.edu
ls -il prepare_rdb.sub.sh
+ ls -il prepare_rdb.sub.sh
144121055705924219 -rwxr-xr-x 1 mbcouger mc3v0jp 465 Sep 18 20:53 prepare_rdb.sub.sh
time /bin/bash ./prepare_rdb.sub.sh
+ /bin/bash ./prepare_rdb.sub.sh
fasta2DB -pfakemoviename -v raw_reads -f/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/input.fofn
+ fasta2DB -pfakemoviename -v raw_reads -f/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/input.fofn
fasta2DB: Cannot open /pylon5/mc3v0jp/mbcouger/VoleNewPacbio/EGRESS/XPCUC.20190906.PACBIO_DATA-PART-2/769_2_MIOR_009_kidney/PACBIO_DATA/Male009KidneyAllReads.fastq.fasta for 'r'
touch /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/rdb_build_done.exit
+ touch /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/rdb_build_done.exit
Traceback (most recent call last):
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 72, in _run_script_local
    system(cmd, check=True)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 29, in system
    raise Exception(msg)
Exception: Call 'bash /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh 1> /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh.log 2>&1' returned 256.
[ERROR]PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',
 'inputDataObjs': {'input_fofn': PypeLocalFile('file://localhost/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/input.fofn', '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/input.fofn')},
 'mutableDataObjs': {},
 'outputDataObjs': {'raw_reads_db': PypeLocalFile('file://localhost/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/raw_reads.db', '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/raw_reads.db'),
                    'rdb_build_done': PypeLocalFile('file://localhost/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/rdb_build_done', '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/rdb_build_done'),
                    'run_jobs': PypeLocalFile('file://localhost/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/run_jobs.sh', '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/run_jobs.sh')},
 'parameters': {'config': {'avoid_text_file_busy': True,
                           'cns_concurrent_jobs': 8,
                           'dazcon': False,
                           'dust': False,
                           'falcon_sense_option': '--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6',
                           'falcon_sense_skip_contained': False,
                           'fc_ovlp_to_graph_option': ' --min_len 12000',
                           'genome_size': 0,
                           'input_fofn': 'input.fofn',
                           'input_type': 'raw',
                           'install_prefix': '/opt/packages/falcon/FALCON-integrate',
                           'job_type': 'local',
                           'length_cutoff': 12000,
                           'length_cutoff_pr': 12000,
                           'openending': False,
                           'overlap_filtering_setting': '--max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24',
                           'ovlp_DBsplit_option': ' -x500 -s200',
                           'ovlp_HPCdaligner_option': '-v -B4 -M64',
                           'ovlp_concurrent_jobs': 14,
                           'pa_DBdust_option': '-w128 -t2.5 -m20',
                           'pa_DBsplit_option': ' -x500 -s200',
                           'pa_HPCdaligner_option': '-v -B4 -M64',
                           'pa_concurrent_jobs': 14,
                           'pa_dazcon_option': '-j4 -x -l 500',
                           'seed_coverage': 20,
                           'sge_option_cns': '',
                           'sge_option_da': '',
                           'sge_option_fc': '',
                           'sge_option_la': '',
                           'sge_option_pda': '',
                           'sge_option_pla': '',
                           'stop_all_jobs_on_failure': False,
                           'target': 'assembly',
                           'use_tmpdir': False},
                'work_dir': '/pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads'}}
Traceback (most recent call last):
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 342, in __call__
    return self.runInThisThread(*argv, **kwargv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 363, in runInThisThread
    self.run(*argv, **kwargv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 276, in run
    rtn = self._runTask(self, *argv, **kwargv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 190, in _runTask
    return self._taskFun(self)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 192, in task_build_rdb
    job_type=config['job_type'], sge_option=sge_option_da)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 150, in run_script_and_wait_and_rm_exit
    job_type, sge_option)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 143, in run_script_and_wait
    run_script(job_data, job_type)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 102, in run_script
    rc = _run_script(job_data)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 72, in _run_script_local
    system(cmd, check=True)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 29, in system
    raise Exception(msg)
Exception: Call 'bash /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh 1> /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh.log 2>&1' returned 256.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/packages/python/2_7_11_gcc/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/packages/python/2_7_11_gcc/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 342, in __call__
    return self.runInThisThread(*argv, **kwargv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 363, in runInThisThread
    self.run(*argv, **kwargv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 276, in run
    rtn = self._runTask(self, *argv, **kwargv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 190, in _runTask
    return self._taskFun(self)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 192, in task_build_rdb
    job_type=config['job_type'], sge_option=sge_option_da)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 150, in run_script_and_wait_and_rm_exit
    job_type, sge_option)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 143, in run_script_and_wait
    run_script(job_data, job_type)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 102, in run_script
    rc = _run_script(job_data)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 72, in _run_script_local
    system(cmd, check=True)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 29, in system
    raise Exception(msg)
Exception: Call 'bash /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh 1> /pylon5/mc3v0jp/mbcouger/FalconMale/0-rawreads/prepare_rdb.sh.log 2>&1' returned 256.

[INFO]Failure ('fail'). Joining 'task:///opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb'...
[ERROR]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
falcon_kit.mains.run args: ['/opt/packages/falcon/FALCON-integrate/bin/fc_run', 'FCArablocal.cfg']

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Please wait for all threads / processes to terminate !
! Also, maybe use 'ps' or 'qstat' to check all threads,!
! processes and/or jobs are terminated cleanly.        !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "/opt/packages/falcon/FALCON-integrate/bin/fc_run", line 9, in <module>
    load_entry_point('falcon-kit==0.4.1', 'console_scripts', 'fc_run')()
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 624, in main
    main1(*argv)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/falcon_kit-0.4.1-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 468, in main1
    wf.refreshTargets([rdb_build_done])
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 522, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/opt/packages/falcon/FALCON-integrate/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 737, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'

**Comment by mbcouger** [comment]
My Apologies I was using an old template. I have attached a new template which I am getting an error on. It seems I have added these options but Falcon still request and says they are missing. In addition  for this job I have 110x coverage with an n50 of 24kb, we are really intrested in phasing the sex chromosmes which are repetive. Would it be possible for you to look over my options and make any suggestion in light of our goals for the assembly and data. 
Many Thanks 

Error "Exception: Missing options.
We now require both "pa_daligner_option" (stage 0) and "ovlp_daligner_option" (stage 1),
which are automatically passed along to
  HPC.daligner
  HPC.TANmask
  HPC.REPmas
[Assemblyconfig.txt](https://github.com/PacificBiosciences/FALCON/files/3630023/Assemblyconfig.txt)

**Comment by pb-cdunn** [comment]
> We now require both "pa_daligner_option" (stage 0) and "ovlp_daligner_option"

Yes, we now separate the daligner options specifically for HPC.daligner from the ones that work both there and in daligner itself.

[This wiki](https://github.com/PacificBiosciences/FALCON/wiki/Options-Available) is fairly up-to-date and might help. Or see the [pb-assembly README](https://github.com/pacificBiosciences/pb-assembly).
