### ISSUE TITLE
Unable to run my PacBio data

### ISSUE THREAD

**Issue by crkmary** [PacificBiosciences/FALCON#695]
Hi everyone,
Does anyone have success using falcon to assembly PacBio Sequel reads?
I do convert sequel bams to fasta (using bam2fasta)and use them as input for falcon.But I got an error like this:
```
> executable=${PYPEFLOW_JOB_START_SCRIPT}

> + executable=/public/home/FALCON/DBM/0-rawreads/build/run-P059fd763948cf4.bash
> timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
> + timeout=60
> 
>  Wait up to timeout seconds for the executable to become "executable",
>  then exec.
> timeleft = int(timeout)
> while [[ ! -x "${executable}" ]]; do
>     if [[ "${timeout}" == "0" ]]; then
>         echo "timed out waiting for (${executable})"
>         exit 77
>     fi
>     echo "not executable: '${executable}', waiting ${timeout}s"
>     sleep 1
>     timeout=$((timeout-1))
> done
> + [[ ! -x /public/home/FALCON/DBM/0-rawreads/build/run-P059fd763948cf4.bash ]]
> 
> /bin/bash ${executable}
> + /bin/bash /public/home/FALCON/DBM/0-rawreads/build/run-P059fd763948cf4.bash
> + '[' '!' -d /public/home/FALCON/DBM/0-rawreads/build ']'
> + cd /public/home/FALCON/DBM/0-rawreads/build
> + eval '/bin/bash run.sh'
> ++ /bin/bash run.sh
> export PATH=$PATH:/bin
> + export PATH=/root/miniconda3/envs/dna/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/miniconda3/bin:/root/bin:/bin
> + PATH=/root/miniconda3/envs/dna/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/miniconda3/bin:/root/bin:/bin
> cd /public/home/FALCON/DBM/0-rawreads/build
> + cd /public/home/FALCON/DBM/0-rawreads/build
> /bin/bash task.sh
> + /bin/bash task.sh
> pypeflow 2.3.0
> 2019-10-12 14:00:06,236 - root - DEBUG - Running "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py /public/home/FALCON/DBM/0-rawreads/build/task.json"
> 2019-10-12 14:00:06,237 - root - DEBUG - Checking existence of '/public/home/FALCON/DBM/0-rawreads/build/task.json' with timeout=30
> 2019-10-12 14:00:06,237 - root - DEBUG - Loading JSON from '/public/home/FALCON/DBM/0-rawreads/build/task.json'
> 2019-10-12 14:00:06,239 - root - DEBUG - {'bash_template_fn': 'template.sh',
>  'inputs': {'config': '../../General_config.json',
>             'input_fofn': '../../input.fofn'},
>  'outputs': {'db': 'raw_reads.db', 'length_cutoff': 'length_cutoff'},
>  'parameters': {'pypeflow_mb': 4000, 'pypeflow_nproc': 1, 'topdir': '../..'}}
> 2019-10-12 14:00:06,239 - root - INFO - CD: '/public/home/FALCON/DBM/0-rawreads/build' <- '/public/home/FALCON/DBM/0-rawreads/build'
> 2019-10-12 14:00:06,239 - root - DEBUG - Checking existence of '../../General_config.json' with timeout=30
> 2019-10-12 14:00:06,240 - root - DEBUG - Checking existence of '../../input.fofn' with timeout=30
> 2019-10-12 14:00:06,240 - root - DEBUG - Checking existence of 'template.sh' with timeout=30
> 2019-10-12 14:00:06,241 - root - INFO - CD: '/public/home/FALCON/DBM/0-rawreads/build' <- '/public/home/FALCON/DBM/0-rawreads/build'
> 2019-10-12 14:00:06,278 - root - INFO - $('/bin/bash user_script.sh')
> hostname
> + hostname
> pwd
> + pwd
> date
> + date
>  Substitution will be similar to snakemake "shell".
> python3 -m falcon_kit.mains.dazzler --config-fn=../../General_config.json --db-fn=raw_reads.db  build --input-fofn-fn=../../input.fofn --length-cutoff-fn=length_cutoff
> + python3 -m falcon_kit.mains.dazzler --config-fn=../../General_config.json --db-fn=raw_reads.db build --input-fofn-fn=../../input.fofn --length-cutoff-fn=length_cutoff
> falcon-kit 1.5.2 (pip thinks "falcon-kit 1.5.2")
> pypeflow 2.3.0
> [INFO]Log-level: INFO
> [INFO]config('../../General_config.json'):
> {'input_fofn': 'input.fofn', 'input_type': 'raw', 'length_cutoff': '-1', 'genome_size': '3430000', 'seed_coverage': '40', 'length_cutoff_pr': '1', 'pa_daligner_option': '-e.8', 'ovlp_daligner_option': '-e.9 -k24 -h60 -w6', 'pa_HPCdaligner_option': '-v -B128 -M24', 'ovlp_HPCdaligner_option': '-v -B128 -M24', 'pa_DBsplit_option': '-x500 -s50', 'ovlp_DBsplit_option': '-x500 -s50', 'falcon_sense_option': '--output-multi --min-cov-aln 4 --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 36', 'falcon_sense_skip_contained': False, 'overlap_filtering_setting': '--max-diff 100 --max-cov 100 --min-cov 2 --n-core 36', 'pa_HPCTANmask_option': '-l500', 'pa_REPmask_code': '0,300/0,300/0,300', 'skip_checks': False, 'pa_DBdust_option': '', 'pa_fasta_filter_option': 'streamed-internal-median', 'pa_subsample_coverage': 0, 'pa_subsample_strategy': 'random', 'pa_subsample_random_seed': 12345, 'dazcon': False, 'pa_dazcon_option': '-j 4 -x -l 500', 'ovlp_DBdust_option': '', 'falcon_sense_greedy': False, 'LA4Falcon_preload': False, 'fc_ovlp_to_graph_option': ' --min-len 1', 'bestn': 12, 'target': 'assembly', 'avoid_text_file_busy': True, 'ver': '100'}
> [INFO]our subset of config:
> {'genome_size': 3430000, 'seed_coverage': 40.0, 'DBdust_opt': '', 'DBsplit_opt': '-x500 -s50', 'daligner_opt': '-e.8 -v -B128 -M24', 'TANmask_opt': '-e.8 -l500', 'REPmask_opt': '-e.8 ', 'user_length_cutoff': -1, 'fasta_filter_option': 'streamed-internal-median', 'subsample_coverage': 0, 'subsample_random_seed': 12345, 'subsample_strategy': 'random'}
> [INFO]Building rdb from '../../input.fofn', to write 'raw_reads.db'
> [INFO]$('bash -vex build_db.sh')
> #!/bin/bash
> set -vex
> + set -vex
> echo "PBFALCON_ERRFILE=$PBFALCON_ERRFILE"
> + echo PBFALCON_ERRFILE=
> set -o pipefail
> + set -o pipefail
> rm -f raw_reads.db raw_reads.dam .raw_reads.* # in case of re-run
> + rm -f raw_reads.db raw_reads.dam '.raw_reads.*'
> fc_fasta2fasta < my.input.fofn >| fc.fofn
> zmw_whitelist_option=""
> + zmw_whitelist_option=
> use_subsampling=0
> + use_subsampling=0
> if [[ $use_subsampling -eq 1 ]]; then
>     while read fn; do  cat  ${fn} | python3 -m falcon_kit.mains.zmw_collect; done < my.input.fofn > zmw.all.tsv
>     cat zmw.all.tsv | python3 -m falcon_kit.mains.zmw_subsample --coverage "0" --random-seed "12345" --strategy "random" --genome-size "3430000" zmw.whitelist.json
>     zmw_whitelist_option="--zmw-whitelist-fn zmw.whitelist.json"
> fi
> + [[ 0 -eq 1 ]]
> while read fn; do  cat  ${fn} | python3 -m falcon_kit.mains.fasta_filter ${zmw_whitelist_option} streamed-internal-median - | fasta2DB -v raw_reads -i${fn##*/}; done < my.input.fofn
> + read fn
> + cat /public/home/FALCON/DBM/DBM19A2766.fasta
> + python3 -m falcon_kit.mains.fasta_filter streamed-internal-median -
> + fasta2DB -v raw_reads -iDBM19A2766.fasta
> falcon-kit 1.5.2 (pip thinks "falcon-kit 1.5.2")
> pypeflow 2.3.0
> INFO:root:Counting bytes from "None"
> INFO:root:        #1 count=          3,364 
> ERROR:root:Trapped exception. Raising new one.
```
```py
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 60, in tokenize_header
>     subread_start, subread_end = [int(val) for val in subread_pos.split('_')]
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 60, in <listcomp>
>     subread_start, subread_end = [int(val) for val in subread_pos.split('_')]
> ValueError: invalid literal for int() with base 10: 'ccs'
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 60, in tokenize_header
>     subread_start, subread_end = [int(val) for val in subread_pos.split('_')]
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 60, in <listcomp>
>     subread_start, subread_end = [int(val) for val in subread_pos.split('_')]
> ValueError: invalid literal for int() with base 10: 'ccs'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 383, in <module>
>     main(sys.argv)          # pragma: no cover
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 380, in main
>     args.func(args)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 309, in cmd_run_streamed_internal_median_filter
>     run_streamed_internal_median_filter(fp_in, sys.stdout, whitelist_set)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 250, in run_streamed_internal_median_filter
>     run_streamed_median_filter(fp_in, fp_out, whitelist_set=whitelist_set, zmw_filter_func=internal_median_zmw_subread)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 175, in run_streamed_median_filter
>     write_streamed(fp_out, yield_zmwtuple_func, zmw_filter_func)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 167, in write_streamed
>     for zmw_id, zmw_subreads in itertools.groupby(yield_zmwtuple_func(store_record=True), lambda x: x.zmw_id):
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 156, in yield_zmwtuple
>     for (record, tokens) in yield_record_and_tokenized_headers(whitelist_set, records):
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 77, in yield_record_and_tokenized_headers
>     tokens = tokenize_header(record.name)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/fasta_filter.py", line 67, in tokenize_header
>     raise ValueError(msg)
> ValueError: Error tokenizing FASTA header:
> 'm54148_190712_094109/58655303/ccs'
> Standard input is empty, terminating!
> cat: write error: Broken pipe
> [WARNING]Call 'bash -vex build_db.sh' returned 256.
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1532, in <module>
>     main()
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1528, in main
>     args.func(args)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1050, in cmd_build
>     build_db(ours, args.input_fofn_fn, args.db_fn, args.length_cutoff_fn)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 169, in build_db
>     io.syscall('bash -vex {}'.format(script_fn))
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
>     raise Exception(msg)
> Exception: Call 'bash -vex build_db.sh' returned 256.
> 2019-10-12 14:00:07,267 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
> 2019-10-12 14:00:07,267 - root - INFO - CD: '/public/home/FALCON/DBM/0-rawreads/build' -> '/public/home/FALCON/DBM/0-rawreads/build'
> 2019-10-12 14:00:07,268 - root - INFO - CD: '/public/home/FALCON/DBM/0-rawreads/build' -> '/public/home/FALCON/DBM/0-rawreads/build'
> 2019-10-12 14:00:07,268 - root - CRITICAL - Error in /root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/public/home/FALCON/DBM/0-rawreads/build/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
>     main()
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
>     run(**vars(parsed_args))
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
>     run_cfg_in_tmpdir(cfg, tmpdir, '.')
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
>     run_bash(bash_template, myinputs, myoutputs, parameters)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
>     util.system(cmd)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
>     raise Exception(msg)
> Exception: Call '/bin/bash user_script.sh' returned 256.
> +++ pwd
> ++ echo 'FAILURE. Running top in /public/home/FALCON/DBM/0-rawreads/build (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
> ++ rm -f top.txt
> ++ which python
> ++ which top
> ++ env -u LD_LIBRARY_PATH top -b -n 1
> ++ env -u LD_LIBRARY_PATH top -b -n 1
> ++ pstree -apl
> 
> real	0m2.063s
> user	0m0.773s
> sys	0m0.586s
> + finish
> + echo 'finish code: 1'
```

**Comment by pb-cdunn** [comment]
```
> ValueError: Error tokenizing FASTA header:
> 'm54148_190712_094109/58655303/ccs'
```
That workflow will not work with ccs reads. (And bam2fasta will not work for gcpp/arrow polishing later, but that's a separate problem.)

If you are intrepid, and if this is a small genome, you can try our experimental snakemake workflow for ccs, still under development:

* https://github.com/PacificBiosciences/pb-assembly/tree/snake/snake/clr

(Please do not post questions about that in pbbioconda, as it's not yet supported officially. Here in FALCON is fine.)

That uses tools available in `pb-assembly` in Bioconda. Note that one of those snakemakes actually runs the other one twice, recursively. Good luck!

As an alternative, you could run our officially supported "Microbial Assembly" workflow in smrtlink ( not using Bioconda at all). For that, please contact field support for your Sequel II machine, or search the web for the download. (It will use Cromwell as your distribution/workflow engine.)
