### ISSUE TITLE
fc_unzip.py run error

### ISSUE THREAD

**Issue by wuxiaopei0509** [PacificBiosciences/FALCON#696]
Hi ,PacBioBiosciences team
I install the pb-assembly0.0.3 through conda ,the first process fc_run can run successfully ,however when I continue to run the next fc_unzip process ,it occurs an error as follows:
```py
[INFO]$('which which')
/usr/bin/which
[INFO]$('which blasr')
/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/bin/blasr
[INFO]$('which samtools')
/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/bin/samtools
[INFO]$('which pbalign')
/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/bin/pbalign
[INFO]$('which gcpp')
which: no gcpp in (/usr/bin/python:/home/wuxiaopei/software/blasr:/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/bin:/home/wuxiaopei/miniconda2/condabin:/home/huyanting/clustalw-2.1-linux-x86_64-libcppstatic:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/jinguihua/biosoft/blast+/ncbi-blast-2.6.0+/bin:/home/huyanting/canu-1.6/Linux-amd64/bin:/home/huyanting/snap:/home/huyanting/perl5:/home/shiyong/biosoft/maker/bin:/home/huyanting/minimap2-2.9_x64-linux:/home/huyanting/LACHESIS-master/src/bin:/home/huyanting/RepeatMasker:/home/huyanting/wtdbg-1.2.8-master:/opt/soft/augustus-3.2.3/bin:/opt/soft/augustus-3.2.3/scripts:/home/huyanting/bwa-0.7.17:/home/jinguihua/biosoft/blast-2.2.26/bin:/opt/zhangcj/soft/cutadapt-master:/usr/local/git/bin:/home/huyanting/REPET_linux-x64-2.5/bin:/home/jinguihua/biosoft/cpanminus-devel/App-cpanminus/cpanm:/home/wuxiaopei/.local/bin:/home/wuxiaopei/bin:/home/wuxiaopei/software/blasr:/home/wuxiaopei/software/PBSuite_15.8.24/bin)
[WARNING]Call 'which gcpp' returned 256.
Traceback (most recent call last):
  File "/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.2.0', 'console_scripts', 'fc_unzip.py')()
  File "/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 33, in main
    unzip.run(**vars(args))
  File "/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 167, in run
    config = parse_config(config_fn)
  File "/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 128, in parse_config
    io.validate_config(config)
  File "/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/lib/python2.7/site-packages/falcon_unzip/io.py", line 76, in validate_config
    syscall('which ' + cmd)
  File "/home/wuxiaopei/miniconda2/envs/pb-assembly0.0.3/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'which gcpp' returned 256
```
Why did it happen? and how can I slove it?
Thanks very much!

**Comment by pb-cdunn** [comment]
Our Issue queue is actually https://github.com/PacificBiosciences/pbbioconda/issues/new/choose

We no longer support installing from GitHub. You must use either Bioconda or an official **smrtlink** download. (See your Sequel representative for more information on downloading, installing, and running our **smrtlink** software suite.)
