### ISSUE TITLE
Running Test cfg fails

### ISSUE THREAD

**Issue by KarlFetter** [PacificBiosciences/FALCON#700]
Hi All. I'm having a bit of trouble getting the cfg file provided in FALCON-examples/run/greg200k-sv2 to work. I'm running the job on my lab's server which does not have a submission handler. The default job type is local in the cfg file and the bash I/O commands appear correct.

Here's the cfg file supplied in the wget materials:
```
[General]
#sge_option_da =
#sge_option_la =
#sge_option_pda =
#sge_option_pla =
#sge_option_cns =
#sge_option_fc =
#pwatcher_type = blocking
#job_type = string
#job_queue = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

#openending = True

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 1000
genome_size = 200000
#seed_coverage = 60

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 1

#pa_REPmask_code = 1,300;0,300;0,300
pa_daligner_option   = -e.8 -l3200 -k18 -h480  -w8 -s100
ovlp_daligner_option = -e.9 -l2500 -k24 -h1024 -w6 -s100
pa_HPCdaligner_option   =  -v -B128 -M24
ovlp_HPCdaligner_option =  -v -B128 -M24
#pa_HPCTANmask_option = -k18 -h480 -w8 -e.8 -s100
#pa_HPCREPmask_option = -k18 -h480 -w8 -e.8 -s100

pa_DBsplit_option = -a -x500 -s4
ovlp_DBsplit_option = -s5

falcon_sense_option = --output-multi --min-cov-aln 4 --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 8
falcon_sense_skip_contained = False

overlap_filtering_setting = --max-diff 120 --max-cov 120 --min-cov 2 --n-core 8
#dazcon = 1

[job.defaults]
job_type = local

#use_tmpdir = /scratch
pwatcher_type = blocking
job_type = string
submit = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}
#job_queue = bash -C ${CMD}
# By dropping STD*_FILE, we see all output on the console.
# That helps debugging in TravisCI/Bamboo.

NPROC=4
#njobs=1
[job.step.da]
[job.step.pda]
[job.step.la]
#NPROC=1
[job.step.pla]
#NPROC=1
[job.step.cns]
#njobs=1
NPROC=8
[job.step.asm]
NPROC=32
```

And the error log is here:

```
falcon-kit 1.3.0
pypeflow 2.2.0
[INFO]Setup logging from file "None".
[INFO]$ lfs setstripe -c 12 /data/karl/periwinkle/methods/falcon/tutorial/FALCON-examples/run/greg200k-sv2 >
[INFO]Apparently '/data/karl/periwinkle/methods/falcon/tutorial/FALCON-examples/run/greg200k-sv2' is not in lustre filesystem, which is fine.
[INFO]fc_run started with configuration fc_run.cfg
[WARNING]Please supply a default for "njobs" (aka concurrency) in section [job.defaults]. For now, we will use 8
[INFO]cfg=
{
  "General": {
    "LA4Falcon_preload": false,
    "avoid_text_file_busy": true,
    "bestn": 12,
    "dazcon": false,
    "falcon_sense_greedy": false,
    "falcon_sense_option": "--output-multi --min-cov-aln 4 --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 8",
    "falcon_sense_skip_contained": false,
    "fc_ovlp_to_graph_option": " --min-len 1",
    "genome_size": "200000",
    "input_fofn": "input.fofn",
    "input_type": "raw",
    "length_cutoff": "1000",
    "length_cutoff_pr": "1",
    "overlap_filtering_setting": "--max-diff 120 --max-cov 120 --min-cov 2 --n-core 8",
    "ovlp_DBdust_option": "",
    "ovlp_DBsplit_option": "-s5",
    "ovlp_HPCdaligner_option": "-v -B128 -M24",
    "ovlp_daligner_option": "-e.9 -l2500 -k24 -h1024 -w6 -s100",
    "pa_DBdust_option": "",
    "pa_DBsplit_option": "-a -x500 -s4",
    "pa_HPCTANmask_option": "-l500",
    "pa_HPCdaligner_option": "-v -B128 -M24",
    "pa_REPmask_code": "0,300/0,300/0,300",
    "pa_daligner_option": "-e.8 -l3200 -k18 -h480  -w8 -s100",
    "pa_dazcon_option": "-j 4 -x -l 500",
    "pa_fasta_filter_option": "streamed-internal-median",
    "pa_subsample_coverage": 0,
    "pa_subsample_random_seed": 12345,
    "pa_subsample_strategy": "random",
    "seed_coverage": 20,
    "skip_checks": false,
    "target": "assembly"
  },
  "job.defaults": {
    "NPROC": "4",
    "job_type": "string",
    "njobs": 8,
    "pwatcher_type": "blocking",
    "submit": "bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}",
    "use_tmpdir": false
  },
  "job.step.asm": {
    "NPROC": "32"
  },
  "job.step.cns": {
    "NPROC": "8"
  },
  "job.step.da": {},
  "job.step.dust": {},
  "job.step.la": {},
  "job.step.pda": {},
  "job.step.pla": {}
}
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/data/programs/miniconda2/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
[INFO]job_type='string', (default)job_defaults={'pwatcher_type': 'blocking', 'use_tmpdir': False, 'job_type': 'string', 'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}', 'NPROC': '4', 'njobs': 8}, use_tmpdir=False, squash=True, job_name_style=0
[INFO]Setting max_jobs to 8; was None
[INFO]Num unsatisfied: 2, graph: 2
[INFO]About to submit: Node(0-rawreads/build)
[INFO]Popen: 'bash -C /data/programs/miniconda2/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /data/karl/periwinkle/methods/falcon/tutorial/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-Pf6a01b7522b15b.bash.stdout 2>| /data/karl/periwinkle/methods/falcon/tutorial/FALCON-examples/run/greg200k-sv2/0-rawreads/build/run-Pf6a01b7522b15b.bash.stderr'
[INFO](slept for another 0.0s -- another 1 loop iterations)
[ERROR]Task Node(0-rawreads/build) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/data/programs/miniconda2/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.3.0', 'console_scripts', 'fc_run')()
  File "/data/programs/miniconda2/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/data/programs/miniconda2/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "/data/programs/miniconda2/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 235, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/data/programs/miniconda2/lib/python2.7/site-packages/falcon_kit/pype.py", line 109, in gen_parallel_tasks
    wf.refreshTargets()
  File "/data/programs/miniconda2/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/data/programs/miniconda2/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
```

I tried running the same example scrips on Compute Canada's Cedar. I modified the submission to work with slurm using this cfg file & it also failed. Seems like it won't submit the job either locally or on Compute Canada.

```
[General]
job_type=slurm
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=
pa_fasta_filter_option=pass
target=assembly
skip_checks=False
LA4Falcon_preload=false
sge_option_da=False
sge_option_la=False
sge_option_pda=False
sge_option_pla=False
sge_option_fc=False
sge_option_cns=False

# falcon complained that these options weren't set.
# Although, pa_daligner_option & ovlp_dalinger_option were both set.
# set(['pa_hpctanmask_option', 'pa_daligner_option', 'ovlp_daligner_option', 'pa_repmask_code', 'pa_fasta_filter_option'])

#### Data Partitioning
pa_DBsplit_option=-x500 -s200
ovlp_DBsplit_option=-x500 -s200

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
genome_size=0
seed_coverage=20
length_cutoff=1000    
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option=-e.8 -l2000 -k18 -h480  -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 2 --max-n-read 1800
falcon_sense_greedy=False

####Pread overlapping
ovlp_daligner_option=-e.9 -l2500 -k24 -h1024 -w6 -s100
ovlp_HPCdaligner_option=-v -B128 -M24

####Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=
length_cutoff_pr=1000

[job.defaults]
job_type=slurm
pwatcher_type=fs_based
JOB_QUEUE = default
submit = srun --wait=0 -p myqueue  \
    -J ${JOB_NAME}             \
    -o ${JOB_STDOUT}        \
    -e ${JOB_STDERR}        \
    --mem-per-cpu=${MB}M     \
    --cpus-per-task=${NPROC} \
    ${JOB_SCRIPT}

[job.step.da]
NPROC=4
MB=32768
njobs=240
[job.step.la]
NPROC=4
MB=32768
njobs=240
[job.step.cns]
NPROC=8
MB=65536
njobs=240
[job.step.pda]
NPROC=4
MB=32768
njobs=240
[job.step.pla]
NPROC=4
MB=32768
njobs=240
[job.step.asm]
NPROC=24
MB=196608
njobs=1
```

Any help getting these tests to run would be great. I've read through a lot of pb-falcon text. But it's hard to know what's out of date and what's in date. There are many example config files that don't seem to match what the current version of falcon wants. The quantity of outdated files, examples, and text for different versions of falcon makes it a bit hard to use this program.

Thx for any help.

**Comment by pb-cdunn** [comment]
```cfg
job_type=slurm
pwatcher_type=fs_based
```
Sorry, the filesystem-based process-watcher is very difficult to maintain for all systems. Please switch to the [`blocking` pwatcher](https://github.com/PacificBiosciences/pypeFLOW/wiki/Configuration).
