### ISSUE TITLE
problems while  2-asm-falcon

### ISSUE THREAD

**Issue by X-WJ** [PacificBiosciences/FALCON#703]
i notice that scripts 2-asm-falcon/user_script.sh sometimes differs in different runs .
One run contains a file named preads.ovl ,and  the other contains a file named preads.m4 .
Can you tell me the different two runs ?
and i also got  a problem while 2-asm-falcon .log are here 
/bin/bash ${executable}
+ /bin/bash /export2/master2/xuwj/03_Assembly/01_preliminary/01_falcon/2-asm-falcon/run-P85123ac8d11a02.bash
+ '[' '!' -d /export2/master2/xuwj/03_Assembly/01_preliminary/01_falcon/2-asm-falcon ']'
+ cd /export2/master2/xuwj/03_Assembly/01_preliminary/01_falcon/2-asm-falcon
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
export PATH=$PATH:/bin
...skipping...
    nx.add_path(sg, one_path)
AttributeError: 'module' object has no attribute 'add_path'

**Comment by zeeev** [comment]
We've recently switched between `ovl` and `m4` extensions. It appears that you've updated your version of falcon mid run.

**Comment by B10inform** [comment]
Hi,

I am also having exactly similar error. The stderr in 2-asm-falcon/. has following message.
write sg_edges_list, c_path, utg_data, ctg_paths.

falconc m4filt-contained --in preads.m4 --out preads.filtered.m4 --min-len 1

    falconc m4filt-contained --in preads.m4 --out preads.filtered.m4 --min-len 1
    fatal.nim(49) sysFatal
    Error: unhandled exception: overlapParser.nim(75, 20) iSpace != -1 Bad input line '---'.
    (Be sure to delete the .idx file if written!) [AssertionError]
    2020-06-04 16:04:51,029 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
    2020-06-04 16:04:51,030 - root - INFO - CD: '/home/FALCON/Exam/2-asm-falcon' -> '/home/FALCON/Exam/2-asm-falcon'
    2020-06-04 16:04:51,030 - root - INFO - CD: '/home/FALCON/Exam/2-asm-falcon' -> '/home/FALCON/Exam/2-asm-falcon'
    2020-06-04 16:04:51,031 - root - CRITICAL - Error in /home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py with argv="{'json_fn': '/home/FALCON/Exam/2-asm-falcon/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
    Traceback (most recent call last):
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "main", mod_spec)
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in
    main()
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
    File "/home/.conda/envs/denovo_FALCON/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
    Exception: Call '/bin/bash user_script.sh' returned 256.
    +++ pwd
    ++ echo 'FAILURE. Running top in /home/FALCON/Exam/2-asm-falcon (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
    ++ rm -f top.txt
    ++ which python
    ++ which top
    ++ env -u LD_LIBRARY_PATH top -b -n 1
    ++ env -u LD_LIBRARY_PATH top -b -n 1
    ++ pstree -apl

real 0m1.339s
user 0m0.984s
sys 0m0.285s

    finish
    echo 'finish code: 1'

**Comment by pb-cdunn** [comment]
This was a mistake, to drop `---`.  It should be fixed now, I think.
