### ISSUE TITLE
Failed to parse config "fc_run.cfg"

### ISSUE THREAD

**Issue by linshengnan2020** [PacificBiosciences/FALCON#710]
hi , I ran the falcon and met an error. could you give me some advises, thank you very much !
**the log**
```py
ffalcon-kit 1.8.1 (pip thinks "falcon-kit 1.8.1")
pypeflow 2.3.0
[INFO]Setup logging from file "None".
[INFO]$ lfs setstripe -c 12 /data/fg1/linsn/30_genome_asm/16_xubao/03_falcon >
[INFO]Apparently '/data/fg1/linsn/30_genome_asm/16_xubao/03_falcon' is not in lustre filesystem, which is fine.
[INFO]fc_run started with configuration falcon.cfg
[WARNING]Option contains flags with "_":
 "falcon_sense_option=--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 18". Those should be "-", as in
 "falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 18". Auto-replaced.
[WARNING]Option contains flags with "_":
 "overlap_filtering_setting=--max_diff 100 --max_cov 100 --min_cov 10 --bestn 10 --n_core 18". Those should be "-", as in
 "overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 10 --bestn 10 --n-core 18". Auto-replaced.
[ERROR]Failed to parse config "falcon.cfg".
Traceback (most recent call last):
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 52, in main1
    config = run_support.parse_cfg_file(input_config_fn)
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 151, in parse_cfg_file
    update_defaults(config['General'])
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 392, in update_defaults
    clean_falcon_options(cfg)
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 112, in clean_falcon_options
    check_HPCdaligner_option(fc[dk])
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 99, in check_HPCdaligner_option
    raise Exception(msg)
Exception: HPC.daligner option "-dal" has changed to "-B".

Traceback (most recent call last):
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_run')()
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 52, in main1
    config = run_support.parse_cfg_file(input_config_fn)
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 151, in parse_cfg_file
    update_defaults(config['General'])
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 392, in update_defaults
    clean_falcon_options(cfg)
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 112, in clean_falcon_options
    check_HPCdaligner_option(fc[dk])
  File "/data/fg1/linsn/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/run_support.py", line 99, in check_HPCdaligner_option
    raise Exception(msg)
Exception: HPC.daligner option "-dal" has changed to "-B".
```
**the fc_run.cfg**
```ini
[General]

#job_type=local

# list of files of the initial subread fasta files
input_fofn = input.fofn
genome_size = 600000000
input_type = raw

pwatcher_type = blocking
job_type = string
job_queue = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 5000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 4000

# overlapping options for Daligner

skip_check = true
skip_checks = true
stop_all_jobs_on_failure = false

pa_HPCdaligner_option =  -v -dal4 -M32 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -M32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400

# error correction consensus options
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 18

# overlap filtering options
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 10 --bestn 10 --n_core 18

# For job-submission options, see https://github.com/PacificBiosciences/FALCON/wiki/Configuration
# These are old-style, but should still work, for now.

sge_option_da = -l nodes=1:ppn=9 -q cu
sge_option_la = -l nodes=1:ppn=9 -q cu
sge_option_pda = -l nodes=1:ppn=9 -q cu
sge_option_pla = -l nodes=1:ppn=9 -q cu
sge_option_fc = -l nodes=1:ppn=9 -q cu
sge_option_cns = -l nodes=1:ppn=9 -q cu

pa_concurrent_jobs = 3
cns_concurrent_jobs = 3
ovlp_concurrent_jobs = 3
```

**Comment by pb-cdunn** [comment]
> Exception: HPC.daligner option "-dal" has changed to "-B".

In the upstream repo, that option of `HPC.daligner` changed. So you have to change these settings:
```ini
pa_HPCdaligner_option =  -v -dal4 -M32 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -M32 -h60 -e.96 -l500 -s1000
```
from `-dal` to `-B`
