### ISSUE TITLE
quiver-run failed at variantCaller

### ISSUE THREAD

**Issue by yanboANU** [PacificBiosciences/FALCON#712]
Dear FALCON developers,

When I use FALCON and FALCON-unzip, I have an issue with the last step of the workflow, fc_quiver.py.

It reports:
[ERROR]Task Node(4-quiver/cns-output) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(4-quiver/cns-output)])

After I traceback, I found some folders in quiver-run seem work and others fail.
du -sh 4-quiver/quiver-run/*/uow-00/*fa*

0	4-quiver/quiver-run/000000Fp01_00001/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01_00001/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000000Fp01_00002/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01_00002/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000000Fp01_00003/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01_00003/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000000Fp01_00004/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01_00004/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000000Fp01_00005/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01_00005/uow-00/cns.fastq.gz
8.0K	4-quiver/quiver-run/000000Fp01_00006/uow-00/cns.fasta.gz
12K	4-quiver/quiver-run/000000Fp01_00006/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000000Fp01_00007/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01_00007/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000000Fp01/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000000Fp01/uow-00/cns.fastq.gz
0	4-quiver/quiver-run/000001Fp01_00001/uow-00/cns.fasta.gz
0	4-quiver/quiver-run/000001Fp01_00001/uow-00/cns.fastq.gz
12K	4-quiver/quiver-run/000001Fp01_00002/uow-00/cns.fasta.gz
12K	4-quiver/quiver-run/000001Fp01_00002/uow-00/cns.fastq.gz
12K	4-quiver/quiver-run/000001Fp01_00003/uow-00/cns.fasta.gz
12K	4-quiver/quiver-run/000001Fp01_00003/uow-00/cns.fastq.gz
...

In the failed cases, I found variantCaller is the reason. 

In 4-quiver/quiver-run/000000Fp01 run-P074fdf05ba6afa.bash.stderr:
...
variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 24 -r /path/4-quiver/quiver-split/./refs/000000Fp01/ref.fa aln-000000Fp01.bam -o cns.fasta.gz -o cns.fastq.gz --minConfidence 0 -o cns.vcf
Process ArrowWorkerProcess-6:
Traceback (most recent call last):
  File "/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/miniconda2/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/Worker.py", line 67, in run
    self._run()
  File "/miniconda2/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/Worker.py", line 48, in _run
    result = self.onChunk(datum)
  File "/miniconda2/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 164, in onChunk
    refContig, options.coverage, self.arrowConfig)
  File "/miniconda2/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 90, in consensusAndVariantsForWindow
    alnsUsed=alnsUsed)
  File "/miniconda2/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/arrow/utils.py", line 462, in consensusForAlignments
    mappedReads = [ arrowConfig.extractMappedRead(aln, refStart) for aln in alns ]
  File "/miniconda2/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/arrow/model.py", line 83, in extractMappedRead
    aln.read(aligned=False, orientation="native"),
  File "/miniconda2/lib/python2.7/site-packages/pbcore/io/align/BamAlignment.py", line 540, in read
    ungapped = reverseComplementAscii(clipped) if shouldReverse else clipped
  File "/miniconda2/lib/python2.7/site-packages/pbcore/io/align/_BamSupport.py", line 39, in reverseComplementAscii
    return complementAscii(a)[::-1]
  File "/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2051, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
TypeError: long() argument must be a string or a number, not 'NoneType'
Process ArrowWorkerProcess-1:
...
 
I use --log-level DEBUG: 
variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 24 -r /path/4-quiver/quiver-split/./refs/000000Fp01/ref.fa aln-000000Fp01.bam -o cns.fasta.gz -o cns.fastq.gz --minConfidence 0 -o cns.vcf --log-level DEBUG

[DEBUG] ArrowWorkerProcess-3 received work unit, coords=000000Fp01:12000-12500
[INFO] Arrow operating on 000000Fp01:11995-12505
[ERROR] Child process exited with exitcode=1.  Aborting.
[DEBUG] ArrowWorkerProcess-5 received work unit, coords=000000Fp01:12500-13000
[INFO] Arrow operating on 000000Fp01:12495-13005
[ERROR] Aborting
[INFO] exiting with return code -1 in 2.82 sec.

Could anyone please tell me where I am going wrong? It's weird to me some folders in quiver-run work and some not.

**Comment by pb-cdunn** [comment]
It's very difficult to continue to support FALCON, for a variety of reasons. We highly recommend adopting CCS reads and switching to **pbipa** in **Bioconda**.
