### ISSUE TITLE
error installing latest falcon--is this a problem?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#79]
when executing the following according to falcon_manual.md

git clone https://github.com/pb-jchin/pypeFLOW.git
cd pypeFLOW
python setup.py install

cd ..
git clone https://github.com/PacificBiosciences/FALCON.git
cd FALCON
python setup.py install

cd ..
git clone https://github.com/pb-jchin/DAZZ_DB.git
cd DAZZ_DB/
make
cp DBrm DBshow DBsplit DBstats fasta2DB ../fc_env/bin/

cd ..
git clone https://github.com/pb-jchin/DALIGNER.git
cd DALIGNER
git checkout 97b0c27a26164dbdd6dc52923855501ca3d14d45
make
cp daligner daligner_p DB2Falcon HPCdaligner LA4Falcon LAmerge LAsort  ../fc_env/bin
cd ..

I get the following error several times (below).  Is this a problem or can I push ahead?
Receiving objects: 100% (956/956), 1.96 MiB, done.
Resolving deltas: 100% (457/457), done.
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    'rdfextras >= 0.1'
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Initialized empty Git repository in /net/gs/vol1/home/dgordon/falcon150523/FALCON-master/install/FALCON/.git/

I just want to know if I can ignore this error and continue.

**Comment by pb-cdunn** [comment]
Hmm. I'm not sure whether that error is in **rdfextras** or **setuptools/distribute**. They are both 3p software. I suspect the latter.

Try to install **virtualenv** for your python. It should work fine for `2.7.3`, which I am using today. (I just did a fresh install without errors.) Then follow the instructions to activate it. If you've already done that, try to upgrade **setuptools** within your virtualenv first.

If all else fails, maybe it's safe to ignore.

**Comment by dgordon562** [comment]
Just to follow up, the error above was indeed a problem.

The solution was that virtualenv needed some python packages.  I didn't both tracking down exactly which--I just put a whole bunch in PYTHONPATH and all was well.
